### ISSUE TITLE
l10n v l20n

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#10]
https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/l10n
vs
http://l20n.org/

We are using l20n for testpilot. There is an issue, https://github.com/mozilla/testpilot/issues/557, to use l20n in the testpilot addon as well.

This addon shouldn't have much text to translate, I vote we use `sdk/l10n` for the mvp, and port to l20n once we get it integrated into the testpilot addon.

**Comment by 6a68** [comment]
I'd vote for waiting on localization (and accessibility) until we've passed the first round of validation in Test Pilot. We can figure out if this is a useful feature with just an en-US audience, and as you mentioned, there's not much text anyway, so intl users should be able to try this out without localizing.

**Comment by wresuolc** [comment]
Decision:  not doing this for MVP
