### ISSUE TITLE
[YouTube] No longer visible in new home page

### ISSUE THREAD

**Issue by victorhqc** [meandavejustice/min-vid#1016]
New (and optional) youtube home page is no longer displaying the min-vid icon.

<img width="1204" alt="screen shot 2017-08-28 at 5 10 56 pm" src="https://user-images.githubusercontent.com/726113/29779828-0774979a-8c14-11e7-82d6-4c7b6858cb66.png">

**Comment by SoftVision-CiprianMuresan** [comment]
While the overlay appears on the new Homepage, it does not appear for related videos and playlists. 
@meandavejustice, should we reopen this issue or do we want to have separate issues for overlay on related and playlists?

**Comment by victorhqc** [comment]
I can check that out

**Comment by Softvision-MariusComan** [comment]
The issue is no longer reproducible on the latest "Min-Vid" build (0.4.3 from 09/07/2017).
