### ISSUE TITLE
Commit 50fc8835ff9f46d42974835cc5f4d8f7bb393dbb breaks plugin

### ISSUE THREAD

**Issue by victorhqc** [meandavejustice/min-vid#1021]
After commit 50fc8835ff9f46d42974835cc5f4d8f7bb393dbb plugin seems to be broken. Previous commits tested and run.

Commits tested:
+ 4fdd988c17b58fcf9e98463852bdf11f943fee62
+ f92d9e8793a996c79b5cbc60a4fd1023c2df5a57
+ c248e399591e29c56b4033e671545b2e1ae869b1
+ 2ce83caedf672591e1f1cbf675cbacf22dceff31

OS:
Mac OS X 10.12.6

Firefox Version:
56.0b6

Ways to reproduce:

This should have a working plugin
```
git checkout working-commit
npm run package
```

Plugin no longer works at this point
```
git checkout 50fc8835ff9f46d42974835cc5f4d8f7bb393dbb
npm run package
```

**Comment by victorhqc** [comment]
No problem :) then this `PR` needs to wait for it
https://github.com/meandavejustice/min-vid/pull/1020 I'll update it once the commit is reverted :)

**Comment by meandavejustice** [comment]
reverted commit and rebased it out of existence
