### ISSUE TITLE
Can't play some of the youtube vids, but they are embeddable

### ISSUE THREAD

**Issue by Timothyyy** [meandavejustice/min-vid#1036]
https://www.youtube.com/watch?v=ENVwnZ5KDJo this vid for example.
![ec419954-cc00-49ef-81a6-555a64e479f1](https://user-images.githubusercontent.com/3677447/30280729-30c51dc6-9719-11e7-9524-b2b68784d375.png)

**Comment by meandavejustice** [comment]
Thanks for reporting @Timothyyy looks like this was messed up when we ported from sdk-addon to a webextension. I've just pushed a fix, it'll be fixed in the next release (this week)

**Comment by meandavejustice** [comment]
In this particular case the video was restricted by the publisher
