### ISSUE TITLE
[YouTube] Disable right click mouse events in the Min Vid player

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [meandavejustice/min-vid#1037]
[Affected versions]:
- Firefox 55 and up
- Min Vid v0.4.3

[Affected Platforms]:
- All Windows
- All Mac 
- All Linux

[Prerequisites]:
- Latest Min Vid add-on version (0.4.3) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to YouTube.
2. Send a video to Min Vid by clicking on "Play Now" overlay.
3. Right click the video in the player.

[Expected result]:
- Nothing happens.

[Actual result]:
- The YouTube video context menu is opened.

[Notes]:
- The context menu is too big to fit inside the Min Vid player and some options are unclickable. From our perspective the options from the context menu are not very useful after the video has been sent to the player.
- Even with the resolution set at 500x500 px, the "Stats for nerds" option can't be dismissed as it overlaps the "Open queue" button. 
![500 x 500 pixeli](https://user-images.githubusercontent.com/31244235/30316073-aef52f34-97ae-11e7-9b7f-9b9908cbce36.png)
- Attached a screen recording of the issue:
![min vid context menu](https://user-images.githubusercontent.com/31244235/30316109-d416bd3c-97ae-11e7-86d4-7ee9bc35f0b5.gif)

**Comment by meandavejustice** [comment]
It appears that disabling the context menu in iframes is not possible without placing a transparent div overtop of the video and intercepting all events. I don't think this is worth it at this time, closing

**Comment by meandavejustice** [comment]
maybe something to checkout much down the road if we decide to stop embedding videos and go with a dom reproduction approach
