### ISSUE TITLE
Cannot build Min Vid from master branch (09/19/2017)

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [meandavejustice/min-vid#1055]
**[Affected Platforms]:**
- Ubuntu 16.04 

**[Steps to reproduce]:**
1. Open terminal window.
2. Enter the following command "git clone https://github.com/meandavejustice/min-vid && cd min-vid/ && npm install && npm run package"
3. Observe the building process.

**[Expected result]:**
- Min Vid xpi is correctly built and saved in the min-vid clone folder.

**[Actual result]:**
- The repo cloning process stops with the following error:
"remote: fatal: unable to read 272cb1abc66c0302dcefc76dd38f180ef6cc3982
remote: aborting due to possible repository corruption on the remote side.
fatal: early EOF
fatal: index-pack failed"

**Comment by meandavejustice** [comment]
@SoftVision-PaulOiegas Looks like you may have caught a hiccup in github.. https://stackoverflow.com/questions/8691916/git-clone-error-fatal-git-upload-pack-aborting-due-to-possible-repository-co#8692934

feel free to reopen if continues to be an issue, I was unable to reproduce

**Comment by SoftVision-PaulOiegas** [comment]
Just managed to build Min Vid xpi today from master, so problem seems fixed. Thanks for the update.
