### ISSUE TITLE
Handle potential error cases for Vimeo/YouTube videos?

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#106]
Randomly spotted while doing another PR.

Currently our /lib/get-vimeo-url.js file looks like this:

```js
const Request = require('sdk/request').Request;

module.exports = getVimeoUrl;

function getVimeoUrl(videoId, cb) {
  Request({
    url: 'https://player.vimeo.com/video/' + videoId + '/config',
    onComplete: function (resp) {
      cb(null, resp.json.request.files.progressive[0].url);
    }
  }).get();
}
```

I looked at https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/request but didn't see anything resembling an `onError` function, but not sure if we need to handle a case where `onComplete` doesn't return a match like we're expecting.

We could do some hacky `try..catch`, but not sure if worth it:

```js
    onComplete: function (resp) {
      try {
        cb(null, resp.json.request.files.progressive[0].url);
      } catch (err) {
        cb(err);
      }
    }
```

**Comment by meandavejustice** [comment]
Need to handle error cases for fails in embeds and fetching embed urls.
