### ISSUE TITLE
Sound stutters

### ISSUE THREAD

**Issue by idsecurity** [meandavejustice/min-vid#1062]
Hello
When listening to music on Youtube using min-vid on FF 55.0.3 32-bit on Windows 10 Pro CU 64-bit the sounds stutters. If I send the video back to a tab the sounds plays without any stutter.

**Comment by meandavejustice** [comment]
Sounds like you may have run into this issue https://github.com/meandavejustice/min-vid/commit/509c17be1395c354deb982922365b7488b13d30b, the fix should be going out early next week.

**Comment by meandavejustice** [comment]
New version shipped, closing. Feel free to reopen if you are still experiencing this
