### ISSUE TITLE
Wrong video being played

### ISSUE THREAD

**Issue by SamuelMarks** [meandavejustice/min-vid#1075]
I click 'Play now' on the second video and I get the first video:
<img width="884" alt="screen shot 2017-10-05 at 4 17 02 pm" src="https://user-images.githubusercontent.com/807580/31211909-b4ab9e76-a9e8-11e7-9282-fa1092fb72fb.png">

Firefox Developer Edition 57.0b5 (64-bit) on macOS 10.12.6

**Comment by SoftVision-CarmenFat** [comment]
Hi @SamuelMarks

I tried to reproduce the issue ou described using Firefox Developer Edition 57.0b5 (64-bit) on macOS 10.12.6 and Windows 10 (64-bit), but without success.
Does this also happen on other Firefox versions, such as Nighty, Beta or release? 
Do you have any other add-ons installed, besides Min Vid? 
	
Thanks!

**Comment by SamuelMarks** [comment]
Tested in Developer Edition; only other addon was AdBlock Ultimate.

**Comment by victorhqc** [comment]
It's affecting me too. I'll investigate.
Firefox Developer Edition 57.0b7 (64-bit) MacOs

**Comment by victorhqc** [comment]
Found a way to reproduce the issue. 
1. Go to https://www.youtube.com/new to enable new UI
2. Go to youtube home page
3. Click in any video to open min-vid: Video is correctly sent
3. Click in youtube icon to refresh homepage
4. Click in any video to open min-vid: Video is incorrect.

I added a `console.log` and the `url` sent to the min-vid window it's incorrect. I think the plug-in
is not detecting any change in the website when the youtube icon is clicked. I'll add a patch for this issue.

**Comment by victorhqc** [comment]
For some reason, the new Youtube page, refreshes the videos without updating the DOM, so the `.min-vid` classes are still added, and the `eventListener` is pointing to the video previously rendered.

**Comment by Softvision-CristinaBadescu** [comment]
I have verified that the issue is no longer reproducible and that all songs are correctly sent and played in the Min-Vid player, using the latest version of Min Vid v.0.4.6, on latest Nighlty build 59.0a1 (2017-11-21), Firefox Beta 58.0b5 and Firefox Release 57.0, using Windows 10 x64, Mac 10.12 and Ubuntu 14.04 x64.
