### ISSUE TITLE
minimized view looks funny on mac os

### ISSUE THREAD

**Issue by 6a68** [meandavejustice/min-vid#108]
On Mac OS, if I minimize the player, I sometimes see this:

![](https://www.dropbox.com/s/5pjysms8lms6xz2/Screen%20Shot%202016-07-27%20at%202.12.27%20PM.png?dl=0&raw=true)

But I also sometimes see this:

![](https://www.dropbox.com/s/mn0srk3awggbvos/Screen%20Shot%202016-07-27%20at%202.26.36%20PM.png?dl=0&raw=true)

When the controls look funny, the `.controls div.right` isn't displayed in the minimized panel window, and the `.controls div.left` take up the full width of the minimized space. Need to dig further to find a root cause.

**Comment by meandavejustice** [comment]
fixed in #94
