### ISSUE TITLE
No option in the in-context controls to find Mid Vid after right click on links

### ISSUE THREAD

**Issue by anitajeziorska** [meandavejustice/min-vid#1084]
[Affected versions]
Firefox 56.0.1
Min Vid 0.4.5

[Affected platform]
Windows 10

[Steps to reproduce]
1. Open browser and look for for example "failarmy".
2. Select "videos" to see list of youtube links
3. Right click on any link to open the in-context controls

[Expected result]
Ability to choose "Send to mini player"

[Actual result]
No option in the in-context controls to send video to Mid Vid

[Notes]
Check menu on screenshot below

![2017-10-10 19_03_08-failarmy - szukaj w google](https://user-images.githubusercontent.com/32680244/31399811-d3ebb9e8-aded-11e7-9a32-8f1e843c522b.png)

**Comment by SoftVision-CiprianMuresan** [comment]
Hi @anitajeziorska, thanks for the report. However this is a dupe of #892.
