### ISSUE TITLE
Player panel is sometimes blank after opening

### ISSUE THREAD

**Issue by 6a68** [meandavejustice/min-vid#109]
Might be a watchpost bug.

Sometimes, often after switching git branches, when I send a video link to the player, an empty panel is displayed:

<img height="100" src="https://www.dropbox.com/s/h0o4dznvpzq1n1x/Screen%20Shot%202016-07-27%20at%202.37.33%20PM.png?dl=0&raw=true">

When this happens, I get this error twice in the console:

```
min-vid:TypeError: can't convert undefined to object
Stack trace:
@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://min-vid/data/controls.js:16:26
onEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://gre/modules/commonjs/sdk/content/content-worker.js:45:22
onEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://gre/modules/commonjs/sdk/content/content-worker.js:45:22
onChromeEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://gre/modules/commonjs/sdk/content/content-worker.js:91:16
```

It looks like the two errors correspond to `updatePanel` sending the `domain` and `ID`, then the `src` (determined async by get-youtube-url), over to the panel. Maybe workers aren't getting properly detached when watchpost updates the xpi?

**Comment by meandavejustice** [comment]
Sounds like this is an issue with the way we are watching, I assume when we switch branches `npm run watch-script` fails on a syntax error. This puts it into a state where it needs to be killed and restarted. I don't know if we can/should support switching branches in our build/watch scripts. Seems like an edge case. Then again if you or someone wants to make some changes to the watch script I would happily merge.

**Comment by meandavejustice** [comment]
haven't seen this in about a month, closing
