### ISSUE TITLE
The overlay isn't displayed on supported websites after installing Min Vid shield study version

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [meandavejustice/min-vid#1099]
[Affected versions]:
- Firefox 56 and up
- Firefox Min Vid v.0.4.5-study

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the following prefs: "xpinstall.signatures.required" set to "false" and "extensions.legacy.enabled" set to "true".

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to "about:addons" page.
2. Drag and drop the Min Vid v.0.4.5-study .xpi file and click on "Add" button.
3. Navigate to a supported website (Youtube, Vimeo or Soundcloud).
4. Hover over the video's thumbnails and observe the Min Vid overlay.

[Expected result]:
- The Min Vid overlay is correctly displayed.

[Actual result]:
- The Min Vid overlay isn't displayed.

[Notes]:
- This issue is only reproducible at first install of the add-on.
- This issue is also reproducible when installing the add-on through "about:debugging"
- This issue is not reproducible after restarting the browser.
- Here is a screen recording of the issue:
![min vid shield study](https://user-images.githubusercontent.com/31244235/32093664-e7b665ca-bb05-11e7-9ba5-c240ae432988.gif)

**Comment by 6a68** [comment]
It [looks like](https://github.com/meandavejustice/min-vid/blob/shield-study/Config.jsm#L35-L41) the existing code doesn't actually do anything to check eligibility. Might be a good idea to exclude existing minvid users from the study, like, check that the addon with id '@min-vid' isn't installed.

My understanding is that we need to add a pref that enables/disables minvid, and add a pref observer to bootstrap.js. Once that's done, the study can just flip the pref. I'll file a bug for this bit and we'll see if @Osmose has anything else to add :+1:

**Comment by 6a68** [comment]
Hmm, weird. It looks like `startup` isn't running on the initial pass because it's failing to load the Config.jsm file (Cu.import is failing).

**Comment by 6a68** [comment]
The chrome registration seems to be happening after startup() is called, so that the Cu.import fails inside a debugger paused at the startup method, but works afterwards.

These Cu.import problems are a recurring thing. I wonder if inlining Config.jsm would be the simplest workaround.

**Comment by Osmose** [comment]
> The chrome registration seems to be happening after startup() is called, so that the Cu.import fails inside a debugger paused at the startup method, but works afterwards.
> 
> These Cu.import problems are a recurring thing. I wonder if inlining Config.jsm would be the simplest workaround.

Chrome registration happens between when `install` and `startup` are called. So you can't use Config in any module-level stuff that happens as soon as `bootstrap.js` is loaded, but you can use it in `startup` and `shutdown`.

The usual workaround for this is to use `XPCOMUtils.defineLazyModuleGetter` to lazy-load the module. Then, as long as you're not referencing it until `startup` is called, things should work fine.

Inlining the config would also fix this. It's mostly a preference thing as to which one you use, although keeping `Config.jsm` would be in line with the style most other studies are using.

**Comment by 6a68** [comment]
This issue was fixed by inlining Config.jsm. Making sure two variations exist is a separate issue, tracked in #1103. Closing.
