### ISSUE TITLE
Is this repo still being maintained?

### ISSUE THREAD

**Issue by victorhqc** [meandavejustice/min-vid#1101]
I wrote a [PR](https://github.com/meandavejustice/min-vid/pull/1090) for a very annoying issue in Youtube, but not sure if this repo still active.

**Comment by meandavejustice** [comment]
hey @victorhqc I've been focusing on getting min vid ready for a [shield study](https://wiki.mozilla.org/Firefox/Shield/Shield_Studies). Sorry I haven't gotten to your pr yet, I appreciate the fix. I'll try and get it reviewed and merged this afternoon, or early next week

**Comment by victorhqc** [comment]
Awesome! 😀  no worries. I was just checking in glad to hear this is still alive 😄
