### ISSUE TITLE
[Shield study] Two telemetry events are sent when launching videos/tracks

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#1102]
[Affected versions]:
- Firefox 56 and up
- Firefox Min Vid v.0.4.5-study

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Min Vid" add-on version 0.4.5-study installed.
- Have the Browser console opened.

[Steps to reproduce]:
1. Open the browser with the profiles from prerequisites and go to a supported website.
2. Send a video/track to the mini player and observe the content of the Browser console.

[Expected result]:
- One telemetry event is sent.

[Actual result]:
- Two telemetry events are sent.
`	1509117820921	Toolkit.Telemetry	ERROR	TelemetryController::submitExternalPing - invalid ping type: [object Object]  Log.jsm:752
	Not a string  (unknown)
	Error: Invalid type string submitted.  TelemetryController.jsm:493:29
	"Warning: Unknown props 'minimized', 'loaded', 'error', 'currentTime', 'exited', 'duration', 'strings', 'visual', 'confirm', 'confirmContent', 'queue', 'history', 'set', 'videoId', 'launchUrl', 'domain', 'time', 'cc', 'trackAdded' on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by ReactPlayer)
    in ReactPlayer (created by Player)
    in div (created by Player)
    in Player (created by AppView)
    in div (created by AppView)
    in div (created by AppView)
    in AppView"  frontend.bundle.js:367:7
	Warning: a 'div' tag (owner: 'ReactPlayer') was passed a numeric string value for CSS property 'width' (value: '400') which will be treated as a unitless number in a future version of React.  frontend.bundle.js:367:7
	Warning: a 'div' tag (owner: 'ReactPlayer') was passed a numeric string value for CSS property 'height' (value: '260') which will be treated as a unitless number in a future version of React.  frontend.bundle.js:367:7
	1509117821394	Toolkit.Telemetry	ERROR	TelemetryController::submitExternalPing - invalid ping type: [object Object]  Log.jsm:752
	Not a string  (unknown)
	Error: Invalid type string submitted.  TelemetryController.jsm:493:29`

[Notes]:
- Two telemetry events are sent when launching a video/track using "Play now" and "Add to queue" buttons.
- One telemetry event is sent when clicking the following buttons: "Close", "Send to tab", "Next", "Previous", "Clear queue", "Clear history".
- Here is a screen recording of the issue:

![pings](https://user-images.githubusercontent.com/26000308/32108438-5d48047c-bb3a-11e7-8f67-b9cef09a0445.gif)

**Comment by Dexterp37** [comment]
Just a fly-by comment: the error in the console ("Invalid ping type") suggests that the wrong value is being passed as the ping type. See [here](http://searchfox.org/mozilla-central/source/toolkit/components/telemetry/TelemetryController.jsm#490).
