### ISSUE TITLE
Touch up onboarding branch modal ui 

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#1122]
The onboarding branch should have a dialog the first time the user visits youtube (or vimeo, whichever comes first)

We will accomplish this via a content script. we'll need to do two checks to see if we should should the dialog in the content script.

1. are we on the onboarding branch
2. have we already shown the dialog

Here is a little demo of what it might look like.

![](https://screenshots.firefoxusercontent.com/images/41316891-bced-4860-8f64-2b7b6606f033.png)

We'll get an actual mockup from ux before we ship.

The git branch for the demo modal is [here](https://github.com/meandavejustice/min-vid/tree/shield-onboarding-branch)

cc/ @johngruen @youwenliang

**Comment by youwenliang** [comment]
@meandavejustice I'll take a look at this!
By the way, for the gif image in the modal, I think it would be better if we can show a cursor clicking the MinVid icon.

**Comment by meandavejustice** [comment]
@youwenliang I agree, I was just throwing something in from the readme

**Comment by johngruen** [comment]
thanks @youwenliang i think we can keep this dead simple...we could even recycle an image from the test pilot onboarding maybe?

**Comment by youwenliang** [comment]
@johngruen Something like this? It'd be nice to have a GIF showing the MinVid player popping out.
![minvid_shield_study](https://user-images.githubusercontent.com/8919308/33061140-e9ce2f08-ced5-11e7-8b36-bce146bd9ad6.png)

**Comment by meandavejustice** [comment]
@youwenliang do we have a gif of the player popping out like from the readme?

**Comment by youwenliang** [comment]
![nov-23-2017-12-15-10-min-min](https://user-images.githubusercontent.com/8919308/33160033-0e8cf3e0-d054-11e7-97f2-435b8d3d1658.gif)
@meandavejustice Something like this?

**Comment by johngruen** [comment]
@youwenliang @meandavejustice we'll need to use a mozilla owned vidyo for the gif.

Other than that, let's make sure the modal isn't too tall...try to keep responsive down to 540px high.

**Comment by youwenliang** [comment]
Here:

width 620px height 540px
![minvid_shield_study](https://user-images.githubusercontent.com/8919308/33357225-e7024ae4-d4fb-11e7-95b1-6492e3795934.png)

GIF image: width: 500px height 273px
![nov-29-2017 11-50-53](https://user-images.githubusercontent.com/8919308/33357226-e76793a4-d4fb-11e7-89e4-106d083e1697.gif)

Would this work?

**Comment by johngruen** [comment]
Modal currently looks like this:

![screen shot 2018-01-11 at 4 56 20 pm](https://user-images.githubusercontent.com/3323249/34833875-c16b8d2e-f6f0-11e7-8299-f1334174c5b8.png)

**Comment by johngruen** [comment]
FWIW, we should not use Fira in the final implementation. Use `font: message-box` instead and then set sizes as needed.

**Comment by johngruen** [comment]
Also, The string needs work...

**Comment by johngruen** [comment]
I can firm up the UI here
