### ISSUE TITLE
Не включается min-vid

### ISSUE THREAD

**Issue by mihalich545** [meandavejustice/min-vid#1126]
При попытки установить, сообщает об ошибке установки в браузер. 
![8](https://user-images.githubusercontent.com/9008499/32861035-8f8aa5e6-ca64-11e7-9401-e12c104b9f67.png)

**Comment by mihalich545** [comment]
ver. 59.0a1 (2017-11-15) (64-бит)
Win10 64-бит версия-1709, сборка 16299.15

**Comment by spinda** [comment]
Reproduced. From the browser console:

```
1510782883276	addons.xpi	WARN	Download of https://testpilot.firefox.com/files/@min-vid/signed-addon.xpi failed: Error: Install manifest specifies unknown optionsType: 2 (resource://gre/modules/addons/XPIInstall.jsm:595:13) JS Stack trace: loadManifestFromRDF@XPIInstall.jsm:595:13 < async*loadFromRDF@XPIInstall.jsm:873:25 < async*loadManifestFromZipReader@XPIInstall.jsm:913:21 < async*loadManifest@XPIInstall.jsm:1596:26 < async*onStopRequest@XPIInstall.jsm:2427:9
```

Looks like https://bugzil.la/1414406 removed OPTIONS_TYPE_INLINE which the MinVid extension uses.

**Comment by 6a68** [comment]
Dupe of #1127, closing. This will be fixed in the wild as soon as we can get the addon QA'd, signed, and shipped.
