### ISSUE TITLE
Nightly breakage due to options page changes

### ISSUE THREAD

**Issue by 6a68** [meandavejustice/min-vid#1127]
For context: https://groups.google.com/forum/#!topic/mozilla.dev.platform/0PjhVa_oZKA

The options code (I guess the height/width code?) is no longer supported in nightly, so minvid is going to start breaking for nightly users. We should get a fix together and out as soon as possible.

**Comment by Mossop** [comment]
You just need to remove the <optionsType> from your install.rdf to fix this.

**Comment by meandavejustice** [comment]
https://github.com/meandavejustice/min-vid/blob/master/install.rdf#L23

**Comment by Softvision-CristinaBadescu** [comment]
I can confirm that this issue is no longer reproducible, and Min Vid v0.4.6 can be successfully enabled from the Test Pilot experiment page, using latest Nightly build 59.0a1(2017-11-21), on Windows 10 x64, Mac 10.12 and Ubuntu 14.04 x64.
