### ISSUE TITLE
Add support from Google search page

### ISSUE THREAD

**Issue by kaganjd** [meandavejustice/min-vid#114]
When I try to send YouTube vids to panel from Google, I get an endlessly loading panel.
<img width="780" alt="screen shot 2016-08-01 at 12 26 33 pm" src="https://cloud.githubusercontent.com/assets/9204835/17301080/3fc9b8b6-57e3-11e6-80af-e47fa2b8af21.png">

Error is: "qs.parse(...).url_encoded_fmt_stream_map is undefined"
Referencing [line 12 of get-youtube-url.js](https://github.com/meandavejustice/min-vid/blob/master/lib/get-youtube-url.js#L12).

**Comment by meandavejustice** [comment]
the best way to handle this may be to setup a context menu handler that uses [urlContext](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/context-menu#URLContext(matchPattern)) for `google.com/*` and when intercepting the link we can strip out all of their junk, and send to our correct video handler.
