### ISSUE TITLE
No way to resize the window.

### ISSUE THREAD

**Issue by rolandixor** [meandavejustice/min-vid#1150]
In Opera it is possible to resize the window if you need to. With this addon (very useful, btw, I love it!!!), you can't resize the window. That would be a nice feature to have.

**Comment by Softvision-CristinaBadescu** [comment]
Thank you for reporting this and for your feedback. However, this is a dupe of #69 and I'm going to close it for now.

Currently, the only way to change the size of Min Vid window is to navigate to "about:addons" page, go to "Extensions" and click the "More" link from the "Min Vid" experiment. You have there the option to change the Window Height and Width and save it.

**Comment by rolandixor** [comment]
Thanks!

I'll follow the other bug.
