### ISSUE TITLE
[Idea][Mac OSX]

### ISSUE THREAD

**Issue by victorhqc** [meandavejustice/min-vid#1152]
There is a feature in Sierra called `picture in picture` in safari, very similar to `min-vid`. The main difference is that the video is sticky. It remains in the same position even if I change desktop or go to a full screen app.
Not sure if this feature is mac exclusive or it came from another platform. But it would be amazing to have this. I'd like to contribute in that, any ideas where I can start looking for documentation?

Here's a reference to that.
https://support.apple.com/en-us/HT206997

**Comment by meandavejustice** [comment]
@victorhqc There is actually a spec being worked on here https://github.com/WICG/picture-in-picture, that's probably the best place to keep up with. In the future Min Vid could turn into a wrapper around this to extend the feature set.

**Comment by victorhqc** [comment]
@meandavejustice 
Awesome! thanks!
