### ISSUE TITLE
[SoundCloud] The songs are not paused nor played if clicking inside the mini player

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#1154]
[Affected versions]:
- Firefox Nightly 59.0a1 (2018-01-04)
- Firefox Developer Edition 58.0b13
- Min-Vid 0.4.7-dev (built on 01/04/2018)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid v.0.4.7 was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.soundcloud.com and send a song to the mini player.
3. Click inside the player and observe the behavior.

[Expected result]:
- The song starts playing.

[Actual result]:
- Playback does not start.

[Notes]:
- This is only reproducible on SoundCloud; on YouTube and Vimeo it works as expected.
- Attached a screen recording of the issue:

![click inside player](https://user-images.githubusercontent.com/26000308/34567197-e71c06ca-f169-11e7-874c-b17986f25e31.gif)

**Comment by wresuolc** [comment]
We're dropping support for soundcloud and vimeo
