### ISSUE TITLE
[SoundCloud] The sound volume doesn't change according to the mini player's volume slider

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#1156]
[Affected versions]:
- Firefox Nightly 59.0a1 (2018-01-04))
- Firefox Developer Edition 58.0b13
- Min-Vid 0.4.7-dev (built on 01/04/2018)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid v.0.4.7 was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.soundcloud.com and send a song to the mini player.
3. While the item is playing, move the volume slider to different positions.
4. Observe the volume.

[Expected result]:
- The volume goes up if the slider is moved up and it goes down if the slider is moved down.

[Actual result]:
- The volume doesn't change.

[Notes]:
- This is reproducible only on SoundCloud platform.
- This is not reproducible if fast forwarding the song.
- Attached a screen recording of the issue:

![soundcloud volume slider](https://user-images.githubusercontent.com/26000308/34567520-483784c4-f16b-11e7-94bf-df03d4b78eab.gif)

**Comment by wresuolc** [comment]
We're dropping support for soundcloud and vimeo
