### ISSUE TITLE
[SoundCloud] The progress doesn't change and the timestamp doesn't update if clicking the Progress bar when the song is paused

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#1157]
[Affected versions]:
- Firefox Release 57.0.4 and up
- Min-Vid 0.4.7-dev (built on 01/05/2018)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid v.0.4.7 was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.soundcloud.com and send a song to the mini player.
3. Click the "Pause" button.
4. Click various places on the Progress bar.
5. Observe the progress and timestamp.

[Expected result]:
- The progress is moved where the mouse is clicked and the timestamp is updated to reflect this.

[Actual result]:
- The progress and timestamp don't change nor update.

[Notes]:
- The progress and the timestamp are updated only after the song starts to play.
- This is not reproducible on YouTube and Vimeo platforms.
- Attached a screen recording of the issue:

![progress and timestamp](https://user-images.githubusercontent.com/26000308/34618343-228a2c5e-f247-11e7-8484-44da14cd6d61.gif)

**Comment by wresuolc** [comment]
We're dropping support for soundcloud and vimeo
