### ISSUE TITLE
[SoundCloud] "Replay" button from the "Play queue" doesn't work

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#1158]
[Affected versions]:
- Firefox Release 57.0.4 and up
- Min-Vid 0.4.7-dev (built on 01/05/2018)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid v.0.4.7 was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.soundcloud.com and send a song to the mini player.
3. Click the "Open Queue" button.
4. Click the "Replay" button and observe what happens next.

[Expected result]:
- Playback starts from the beginning.

[Actual result]:
- Nothing happens, the audio continues to play uninterrupted.

[Notes]:
- This is not reproducible on YouTube and Vimeo.
- Attached a screen recording of the issue:

![replay soundcloud](https://user-images.githubusercontent.com/26000308/34618487-95f0fad8-f247-11e7-82c8-5a2cfe5fc3a7.gif)

**Comment by wresuolc** [comment]
We're dropping support for soundcloud and vimeo
