### ISSUE TITLE
Create docs for extracting URLs/video IDs from different platforms

### ISSUE THREAD

**Issue by kaganjd** [meandavejustice/min-vid#116]
This will live on Mozilla Min-Vid wiki and make it easier for contributors to get involved.

**Comment by meandavejustice** [comment]
I think that this should live in the repo, I think that would make it easier to keep updated.

**Comment by pdehaan** [comment]
💯 for putting this in doc in https://github.com/meandavejustice/min-vid/tree/master/docs

**Comment by kaganjd** [comment]
Keeping this here to add to docs

**Adding support for a new domain**
Before you open a PR, make sure these work:

- [ ] "Send-to-tab"
- [ ] Overlay icon appears
- [ ] "Send to Min-Vid" appears in the context menu

**Comment by meandavejustice** [comment]
We've decided to go in a different direction for this. For now we will support domains through their embed apis, and are researching a fully clientside solution(dom or browser level) so we can bypass interacting with api entirely
