### ISSUE TITLE
Old Firefox logo is displayed on the feedback survey

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#1162]
[Affected versions]:
- Firefox Developer Edition 58.0b14
- Firefox Nighlty 59.0a1 (01/08/2018)
- Min-Vid Shield Study Onboarding 0.4.7 (built on 01/08/2018)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid v.0.4.7 Shield Study Onboarding was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Go to about:addons and click the "Remove" button for Min Vid experiment.
3. After redirected to survey page, observe the Firefox logo on top.

[Expected result]:
- The new Firefox logo is correctly displayed above the survey form.

[Actual result]:
- The old Firefox logo is still displayed above the survey form.

[Notes]:
- Attached a screen shot of the issue:

![old logo](https://user-images.githubusercontent.com/26000308/34682357-62a8a092-f4a7-11e7-89bb-c9a3ed76fd03.png)

**Comment by meandavejustice** [comment]
I pinged @johngruen about this to see if I can get access to update it. Luckily this is something we can fix post launch if neccessary, not a blocker.

**Comment by johngruen** [comment]
Aight, this is fixed
