### ISSUE TITLE
[Soundcloud]"NaN:Invalid Date" is displayed after you click several times the "Next" button

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [meandavejustice/min-vid#1163]
[Affected versions]:
- Firefox Developer Edition 58.0b14
- Firefox Nighlty 59.0a1
- Min-Vid Shield Study Onboarding 0.4.7-dev (built on 01/08/2018)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid v.0.4.7 Shield Study Onboarding was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.soundcloud.com and send 5 songs to the mini player.
3. Click the "Next" button until you reach the last song.
5. Observe the progress bar and timestamp.

[Expected result]:
- The songs are played one after another.

[Actual result]:
- The "NaN:Invalid Date" is displayed.

[Notes]:
- The issue is also reproducible if already having a YouTube video sent to the mini player and then sending a SoundCloud track. Clicking the "Next" button to reach to the SoundCloud track will display the error mentioned above.
- This is not reproducible on YouTube and Vimeo platforms.
- Attached a screen recording of the issue:
![min vid invalid time stamp](https://user-images.githubusercontent.com/31244235/34682324-43e20f18-f4a7-11e7-822f-5ba67b6be60b.gif)

**Comment by Softvision-CristinaBadescu** [comment]
After performing further investigations, I've realized that this issue is reproducible when you click the "Next" button right after you've just sent an audio from Soundcloud before it's loaded. See #1167.

**Comment by wresuolc** [comment]
We're dropping support for soundcloud and vimeo
