### ISSUE TITLE
The add-on is not installed correctly at the first attempt while having the "active" or "activeAndOnboarding" study variants

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [meandavejustice/min-vid#1165]
[Affected versions]:
- Firefox Developer Edition 58.0b14
- Firefox Nightly 59.0a1
- Min-Vid Shield Study Onboarding 0.4.7-study (built on 01/09/2018)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false" and "extensions.legacy.enabled" pref set to "true".

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:addons" page and select the "Extensions" section.
3. Drag and drop the Min Vid add-on and click the "Add" button.
4. Click the "More" link and observe the details page.

[Expected result]:
- The add-on details page is displayed.

[Actual result]:
- The add-on is removed.

[Notes]:
- The issue is also reproducible if you refresh the page.
- Also, the Min Vid overlay doesn't appear on the supported websites.
- This issue is not reproducible on the second attempt to install the add-on.
- Here is a screenshot with the errors from browser console at first install:
![activeandonboarding browser console error](https://user-images.githubusercontent.com/31244235/34719674-50a4dcf6-f544-11e7-9b97-c13ffe27856b.png)

- Here is a screen recording of the issue:
![min vid first attempt installation](https://user-images.githubusercontent.com/31244235/34719700-67998790-f544-11e7-8755-49d8030f1c2e.gif)

**Comment by meandavejustice** [comment]
I've not been able to reproduce this. Maybe its a sort of caching bug when testing/developing. We'll keep an eye on this as we get the other bugs for launch fixed.

**Comment by johngruen** [comment]
Let's talk to @gregglind about this to see if this is expected or if there is a test env to verify

**Comment by 6a68** [comment]
I can try to repro this

**Comment by 6a68** [comment]
@Softvision-CristinaBadescu When you reproduced this issue, did you set the override pref (`extensions.minvidstudy.override`), or just install the study repeatedly, until you got a profile that was in the right group?

**Comment by 6a68** [comment]
I just had this happen when I uninstalled, then reinstalled min-vid, where the new version had the IS_SHIELD_STUDY env var set:

1. install a copy of min-vid built from the shield-study branch with no env var set (`npm run package`)
2. uninstall min-vid
3. install a copy of min-vid built from the shield-study branch with the shield study env var set (`IS_SHIELD_STUDY=true npm run package`)
4. installation fails

I'll poke at this a bit more

**Comment by 6a68** [comment]
Answering my question above, I did have the `extensions.minvidstudy.override` pref set to 'active' when this occurred.

**Comment by 6a68** [comment]
OK, just reproduced this again on a fresh profile in today's Nightly. STR:

1. create profile
2. start nightly
3. inside about:config, set `xpinstall.signatures.required` to `false`, set `extensions.legacy.enabled` to `true`, and create a string pref `extensions.minvidstudy.override`, set to `active`.
4. create min-vid shield study *without* setting the env var: `npm run package`
5. install add-on
6. installation looks ok in about:addons, but addon disappears.

Interesting stuff in the browser console:

<img width="1109" alt="screen shot 2018-01-25 at 11 58 51 am" src="https://user-images.githubusercontent.com/96396/35409468-26ab77d6-01c7-11e8-8e45-3dd1087dda3d.png">

Unfortunately, the devtools remote debugging server keeps crashing in today's Nightly, so I can't access the debugger. I'll keep messing around.

**Comment by 6a68** [comment]
I'm seeing the same error in Dev Edition.

**Comment by 6a68** [comment]
The `this.extension is null` error doesn't seem to be relevant; `this.extension = null` is set by another async function, at [line 215](https://dxr.mozilla.org/mozilla-central/rev/e22e2c9eb8/toolkit/components/extensions/LegacyExtensionsUtils.jsm#215) of `LegacyExtensionsUtils.jsm`. The real error is at the line above it, the `enumerateZipFile` exception in the screenshot. The error is thrown at [line 386 of Extension.jsm](https://dxr.mozilla.org/mozilla-central/rev/e22e2c9eb8/toolkit/components/extensions/Extension.jsm#386), which iterates over the locales directories inside the webextension.

I don't know what is wrong with the location of those directories; I'll ask the addons folks for advice.

**Comment by 6a68** [comment]
This bug only affects a fresh profile on the first install.
