### ISSUE TITLE
The feedback survey is not opened after uninstalling the add-on

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [meandavejustice/min-vid#1166]
[Affected versions]:
- Firefox Developer Edition 58.0b14
- Firefox Nighlty 59.0a1
- Min-Vid Shield Study Onboarding 0.4.7-study (built on 01/09/2018)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid v.0.4.7 Shield Study Onboarding was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:addons" page and select the "Extensions" section.
3. Click on "Remove" button from the Min Vid experiment.
5. Observe the feedback survey opened in a new tab.

[Expected result]:
- A new tab with the feedback survey is opened and focused.

[Actual result]:
- The feedback survey is not opened.

[Notes]:
- This issue is reproducible for all the variants: "inactive", "active" and "activeAndOnboarding".
- Attached a screen recording of the issue:
![feedback survery uninstall add-on](https://user-images.githubusercontent.com/31244235/34721142-45fce356-f54a-11e7-9476-c77386d69125.gif)

**Comment by johngruen** [comment]
@Softvision-CristinaBadescu can you verify Dave's fix here?

**Comment by Softvision-CristinaBadescu** [comment]
Hello @johngruen ,

Yes, Dave's fix works. I've done the following:
1. Install the add-on.
2. Restart the browser using the Developer Toolbar.
3. Removed the add-on.

The survey feedback was opened in a new tab, but isn't focused. I've filed this issue here: #1182.

**Comment by meandavejustice** [comment]
Thanks @Softvision-CristinaBadescu, closing
