### ISSUE TITLE
The songs from Soundcloud are overlapping if the user clicks the "Next" button rapidly

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [meandavejustice/min-vid#1167]
[Notes]:
- This issue is only reproducible when you click "Next" button while an audio from Soundcloud is in the Min Vid player.
- This issue is not reproducible if you wait for the audio to load and only afterwards click the "Next" button.
- The track from Soundcloud is moved to History.

[Affected versions]:
- Firefox Developer Edition 58.0b14
- Firefox Nighlty 59.0a1
- Min-Vid Shield Study Onboarding 0.4.7-study (built on 01/09/2018)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid v.0.4.7 Shield Study Onboarding was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to YouTube and send a video to the Min Vid player.
3. Open a new tab and navigate to a Soundcloud audio link (for eg. https://soundcloud.com/wavey-hefner/lil-pump-gucci-gang-prod-bighead-gnealz).
4. Send the audio to the player using "Play Now" option and rapidly click the "Next" button.
5. Observe the behavior.

[Expected result]:
- The video previously sent starts playing again.

[Actual result]:
- The audio from Soundcloud overlaps with the first played video.

[Additional notes]:
- Also, the progress bar reflects the Soundcloud audio.
- If you click in different positions of the progress bar, the progress changes are applied to the video displayed in the player.
- The Start/Pause buttons are actionable for the video displayed in the Min Vid player (the YouTube video in our case).
- This issue is also reproducible with the latest Min Vid v0.4.7 installed from the Test Pilot Experiment page (https://testpilot.firefox.com/experiments/min-vid).
- Here is a screen recording of the issue:

![soundcloud overlapping songs](https://user-images.githubusercontent.com/31244235/34726426-a7531442-f55c-11e7-972e-2635496b07e2.gif)

**Comment by wresuolc** [comment]
We're dropping support for soundcloud and vimeo
