### ISSUE TITLE
[SoundCloud] The first and last items are displayed with a delay if scrolling up and down through the tracks

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#1168]
[Affected versions]:
- Firefox Developer Edition 58.0b14
- Firefox Nighlty 59.0a1 (01/08/2018)
- Min-Vid Shield Study Onboarding 0.4.7 (built on 01/09/2018)

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid v.0.4.7 Shield Study Onboarding was previously installed on a clean profile.
- A SoundCloud playlist (>20 tracks) was previously sent to the mini player.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Scroll up and down using the mouse wheel.
3. Observe the first and the last videos.

[Expected result]:
- The videos are correctly displayed.

[Actual result]:
- The videos are displayed with a delay.

[Notes]:
- This is also reproducible when sending tracks one by one;
- This is reproducible on both "Play Queue" and "History" sections;
- I wasn't able to reproduce this with YouTube and Vimeo videos;
- Attached a screen recording of the issue:

![playlist soundcloud](https://user-images.githubusercontent.com/26000308/34727026-565c3a62-f55e-11e7-8967-d3b107478320.gif)

**Comment by wresuolc** [comment]
We're dropping support for soundcloud and vimeo
