### ISSUE TITLE
[Vimeo] Min Vid overlay is wrongly displayed under the top left Homepage button

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#1169]
[Affected versions]:
- Firefox Developer Edition 58.0b14
- Firefox Nighlty 59.0a1 (01/08/2018)
- Min-Vid Shield Study Onboarding 0.4.7 (built on 01/09/2018)

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- Latest Min-Vid v.0.4.7 Shield Study Onboarding was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.vimeo.com
3. Hover the animation video from the Welcome area.
4. Observe the top left corner of the page.

[Expected result]:
- Vimeo Homepage button is displayed.

[Actual result]:
- The Min Vid overlay is displayed under the Homepage button.

[Notes]:
- Attached a screen recording of the issue:

![vimeo overlay](https://user-images.githubusercontent.com/26000308/34727038-632a0cec-f55e-11e7-8b4b-7cc7d0c34f7c.gif)

**Comment by wresuolc** [comment]
We're dropping support for soundcloud and vimeo
