### ISSUE TITLE
[SoundCloud] Performance issues are encountered if >20 tracks are sent to the mini player 

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#1170]
[Affected versions]:
- Firefox Developer Edition 58.0b14
- Firefox Nighlty 59.0a1 (01/08/2018)
- Min-Vid Shield Study Onboarding 0.4.7 (built on 01/09/2018)

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid v.0.4.7 Shield Study Onboarding was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.soundcloud.com
3. Send a track to the mini player.
4. Repeat step 3 for at least 20 times.
5. Observe the behavior of the player when sending more than 20 tracks.

[Expected result]:
- The tracks are successfully sent to the player;
- The user is able to click the overlay without issues.

[Actual result]:
- Some of the tracks are not sent to the mini player;
- The arrow cursor takes place of the hand pointer and the user can't click the overlay. 

[Notes]:
- I wasn't able to reproduce any performance issues by sending 40 videos to Youtube, so this seems to be related to the SoundCloud platform;
- I also noticed that the mini player went into an intermittent freeze state for a few seconds;  
- Attached a screen recording of the issue:

![performance soundcloud](https://user-images.githubusercontent.com/26000308/34730807-1ab672c4-f569-11e7-955f-6f84dd0f97cd.gif)

**Comment by meandavejustice** [comment]
We may be disabling soundcloud for the shield study #1173

**Comment by wresuolc** [comment]
We're dropping support for soundcloud and vimeo
