### ISSUE TITLE
[Intermittent] Telemetry errors appear in browser console while having the "active" or "activeAndOnboarding" study variants

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [meandavejustice/min-vid#1174]
[Notes]:
- You may also encounter this issue in the following scenarios:

First scenario:
- At the second attempt to install the add-on, when you select again the "Extensions" section and reinstall the add-on.

Second scenario:
- After second installation, when you navigate to a supported website (for eg. https://www.youtube.com).

[Affected versions]:
- Firefox Developer Edition 58.0b15
- Firefox Nighlty 59.0a1
- Min-Vid Shield Study Onboarding 0.4.7-study (built on 01/10/2018)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false" and "extensions.legacy.enabled" pref set to "true".
- Have the Browser Console open (Tools -> Web Developer -> Browser console).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:addons" page and select the "Extensions" section.
3. Drag and drop the Min Vid add-on and click the "Add" button.
4. Click the "More" link.
5. Wait a couple of seconds and observe the Telemetry data from the browser console.

[Expected result]:
- The browser console has no Telemetry errors.

[Actual result]:
- The browser console contains Telemetry errors.

[Additional notes]:
- At first attempt of installing the add-on you'll encounter #1165 issue while having "active" and "activeAndOnboarding" variants.
- Here is a screenshot with the Telemetry errors:
![activeandonboarding browser console error](https://user-images.githubusercontent.com/31244235/34776876-02ca13ec-f621-11e7-8642-3bc906aca056.png)

- Here is a screen recording of the issue:
![telemetry errors](https://user-images.githubusercontent.com/31244235/34776884-0765e412-f621-11e7-8fd3-01641f811f87.gif)

**Comment by meandavejustice** [comment]
This looks like it may also be an upstream bug, I'm gunna ask around with the people who created ShieldUtils.jsm and see if we can get to the bottom of it.
