### ISSUE TITLE
The modal is not rendered correctly to the zoom value of YouTube website 

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#1176]
[Affected versions]:
- Firefox Developer Edition 58.0b14
- Firefox Nighlty 59.0a1 (01/09/2018)
- Min-Vid Shield Study Onboarding 0.4.7 (built on 01/10/2018)

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Latest Min-Vid v.0.4.7 Shield Study Onboarding ("activeAndOnboarding" variant) was previously installed on a clean profile.
- YouTube's zoom in was previously set to 133%.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.youtube.com website.
3. Observe the way the modal behaves.

[Expected result]:
- The modal is responsive to the zoom value of the page and correctly renders.

[Actual result]:
- The modal is not rendered correctly, the bigger the zoom in is, the modal's bottom part gets more hidden and no scroll bar is displayed to navigate through it.

[Notes]:
- This issue was observed on a MacBook Pro device (2560 x 1600); on the other devices, the results were the following:
-> on Windows 10 device (1920 x 1080), the modal is hidden when zooming in reaches 200% value;
-> on Ubuntu 14.04 device (1680 x 1050) the modal is hidden when zooming in reaches 210% value;
- Please see the screen recording of the issue: https://goo.gl/CoHnqR

**Comment by meandavejustice** [comment]
@johngruen Can I get your opinion on this? I'm not sure how to handle this, or if we should at all. Seems like an edge case

**Comment by johngruen** [comment]
Yeah but i know that modal is not to spec...

**Comment by meandavejustice** [comment]
@johngruen The main detail I notice in that screenshot is the header, I actually fixed that this morning.

**Comment by johngruen** [comment]
I'm gonna close this one b/c i'll pound the modal into shape
