### ISSUE TITLE
[YouTube] The "Play/Pause" button is constantly switching states after clicking the "Play" button before the "Replay" one

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [meandavejustice/min-vid#1179]
[Affected versions]:
- Firefox 57.0.4 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min Vid v.0.4.7 (custom build 2017-01-11) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to https://youtube.com.
2. Send a video to the player using the "Play Now" button.
3. Fast forward the video at the end.
4. When the "Replay/Close" overlay is displayed, click the "Pause" button.
5. Click the "Replay" button from the "Replay/Close" overlay.
6. After the video starts, observe the "Pause" button.

[Expected result]:
- The "Pause" button is correctly displayed.

[Actual result]
- The "Play"/"Pause" button is constantly switching states and only the "Play" tooltip seems to be displayed.

[Notes]:
- The "Pause/Play" button isn't actionable while you encounter this error.
- This issue is no longer reproducible if you change the position of the progress bar.
- The issue is not reproducible on the others platforms (Soundcloud and Vimeo). 
- Here is a screen recording of the issue:

![min vid changing states](https://user-images.githubusercontent.com/31244235/34833471-27cffcb0-f6f8-11e7-8f5e-c0e2232ae593.gif)

**Comment by meandavejustice** [comment]
closed in #1202
