### ISSUE TITLE
The modal wrongly remains displayed after removing the experiment

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#1181]
[Notes]:
- This issue is related to #[994 ](https://github.com/meandavejustice/min-vid/issues/994).
	
[Affected versions]:
- Firefox Developer Edition 58.0b15
- Firefox Nighlty 59.0a1 (01/11/2018)
- Min-Vid Shield Study Onboarding 0.4.7 (built on 01/12/2018)

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Latest Min-Vid v.0.4.7 Shield Study Onboarding ("activeAndOnboarding" variant) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.youtube.com website.
3. In a new tab, go to "about:addons" and remove the Min Vid add-on.
4. Switch back to the YouTube tab and observe the behavior.

[Expected result]:
- The modal is no longer displayed.

[Actual result]:
- The modal is still displayed.

[Additional Notes]:
- The issue is no longer reproducible after the page is refreshed.
- Nothing happens when "X" button is clicked: the user is forced to refresh the page in order to get rid of the modal.
- Please see the screen recording of the issue: 

![modal remains after uninstall](https://user-images.githubusercontent.com/26000308/34870252-377658fe-f792-11e7-800c-59934625e9c3.gif)

**Comment by meandavejustice** [comment]
I would call this an edgecase.

This will be difficult to fix, the two ways for webextensions to detect when they are being uninstalled are not supported yet in firefox.
1. https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/onSuspend
2. https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/management/onUninstalled#Browser_compatibility
