### ISSUE TITLE
The feedback survey tab is not focused after uninstalling the add-on

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [meandavejustice/min-vid#1182]
[Affected versions]:
- Firefox Developer Edition 58.0b15
- Firefox Nightly 59.0a1
- Min-Vid Shield Study Onboarding 0.4.7-study (built on 01/12/2018)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false" and "extensions.legacy.enabled" pref set to "true".

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to "about:addons" page.
2. Select the "Extensions" section and drag and drop the Min Vid add-on.
3. Select the "Add" button and restart the browser.
4. Focus the "about:addons" page and click the "Remove" button from the Min Vid add-on.
5. Observe the newly opened feedback survey tab.

[Expected result]:
- The feedback survey tab is focused.

[Actual result]:
- The feedback survey tab is not focused.

[Notes]:
- While trying to install the add-on you might encounter this issue: #1165.
- Here is a screen recording of the issue:
![survey feedback](https://user-images.githubusercontent.com/31244235/34880293-ad338c30-f7b8-11e7-9999-5206cf1bda3e.gif)

**Comment by 6a68** [comment]
There's a bit of code missing from StudyUtils.jsm that can fix this. I'll submit the PR here, and we can chat with @gregglind async about whether he wants to upstream the changes or not
