### ISSUE TITLE
Min Vid icon is missing from YouTube video

### ISSUE THREAD

**Issue by SoftVision-VladBacia** [meandavejustice/min-vid#119]
[Affected versions]:
Firefox 45 and up
Latest Min Vid version (built from GitHub repo)

[Affected Platforms]:
All Windows
All Mac OS X
All Linux

[Prerequisites]:
Latest Min Vid add-on was previously installed on a profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Go to www.youtube.com .
3. Click on any video available.
4. Observe the Min Vid icon that is displayed on top of the video.

[Expected result]:
The Min Vid icon is overlaid in the upper right corner of the video.

[Actual result]:
The Min Vid icon is missing.

[Notes]:
1. If another video is opened in a new tab using the context menu or the middle mouse button, then the Min Vid icon is displayed.
2. [Here](https://drive.google.com/open?id=0B6QogV2AJFKieUpwWkhEZDVRUFU) is a screen recording describing the issue

**Comment by meandavejustice** [comment]
need to use either mutation observer or setInterval
