### ISSUE TITLE
Verify Metrics pings

### ISSUE THREAD

**Issue by johngruen** [meandavejustice/min-vid#1198]
And confirm that the version is coming though.

**Comment by meandavejustice** [comment]
example play ping

```json
{"an":"Min Vid Study",
"aid":"@min-vid-study",
"aiid":"testpilot",
"aip":"1",
"av":"0.4.7-study",
"cd19":"dev",
"cd20":"nightly",
"ds":"webextension",
"t":"event",
"tid":"UA-46704490-3",
"v":"1",
"cid":"7fd7ef1b-751c-44ce-b17c-bcfdb1be5da2",
"ua":"Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0",
"ul":"en-US",
"z":1516829281300,
"ec":"interactions",
"ea":"play",
"cd2":198,
"cd3":289,
"cd4":"400",
"cd5":"260",
"cd6":"youtube.com"
}
```

**Comment by meandavejustice** [comment]
still need to review docs and make sure they are up to date [docs](/docs/metrics.md)

**Comment by 6a68** [comment]
@meandavejustice Right now, the shield study [drops](https://github.com/meandavejustice/min-vid/blob/shield-study/webextension/lib/send-metrics-data.js#L16) all of the GA pings. Is that the intended behavior?

**Comment by 6a68** [comment]
I'm not sure what the intention is here, so I'm going to hand this one off

**Comment by meandavejustice** [comment]
@6a68 yes we will be sending all pings to telemetry instead. We can't send anything to GA for shield since the user doesn't actually install the addon
