### ISSUE TITLE
Security risk management tracking

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#12]
Need to create bugzilla bug assessing risk management. follow format of https://bugzilla.mozilla.org/show_bug.cgi?id=1201317

**Comment by wresuolc** [comment]
We're actually following a different (lighter-weight) process for test pilot.  I'll handle a security review once we have a bit more done.

**Comment by wresuolc** [comment]
we've got sign off from security for v1.  Thanks
