### ISSUE TITLE
Can't drag min-vid window

### ISSUE THREAD

**Issue by mirzmaster** [meandavejustice/min-vid#1200]
Running Firefox Developer Edition (build id 20180117222144), can't drag the min-vid around the window.  The window is locked to the top-left of the screen.  Experienced the same on macOS as well as Windows 7.

**Comment by meandavejustice** [comment]
hey @mirzmaster we just got a fix for this in today. I'm going to push out an update this week/early next week after it gets tested by our Q.A. team. Thanks for the report. https://github.com/meandavejustice/min-vid/pull/1197

**Comment by chrisrede** [comment]
Have the same problem, is there a solution to this?

**Comment by meandavejustice** [comment]
@chrisrede Can you elaborate on your issue? Also can you provide your os, firefox version etc..

**Comment by chrisrede** [comment]
It's working fine now for me. I use Windows 10, Firefox 59.0.1. The only difference i made now is changing the Screen! Seems like there is some sort of positioning problem when i add/remove a monitor?

**Comment by meandavejustice** [comment]
@chrisrede interesting, I made a commit to launch at a different position to avoid this bug all together, but hadn't gotten around to cutting a release for testpilot. https://github.com/meandavejustice/min-vid/commit/4970670d335a972985394d32704dcfce86d6fde6

Thanks for reminding me!
