### ISSUE TITLE
Add support for Vines from Vine.co homepage

### ISSUE THREAD

**Issue by kaganjd** [meandavejustice/min-vid#121]
We get the video URL from Vine embeds by loading the video on its single-video page on vine.co, then looking at the `twitter:player:stream` meta tag in the page header.

Unfortunately, on the vine.co homepage, videos are embedded as a preview jpeg, and when the user mouses over the video, some kind of Ember video player UI is overlaid on the preview image. The problem is that this video player is a single component shared by the whole vine.co homepage, so a right click on the playing image won't point to a useful part of the DOM. To make matters worse, after right-clicking and while mousing down to 'send to mini player', Ember detects the mouse movement and empties out the video player--so you wind up with a right click event on an empty element.

If we could somehow get around the Ember component, it looks like you can get from the video preview image to the vine ID as follows:
- `.video-container` contains the preview image), but its next sibling, `.info`, contains a couple of descendants that lead to the vine ID, `.post-metadata .time a`:
```
<div class="post-metadata">
  <span class="time">
    <a href="/v/5bzXw9zMQ0n" class="ember-view" id="ember1439">2h ago</a></span>
  </span>
```  

Maybe we could use the right-click's page coords to infer what element was actually right-clicked? That would let us get to the correct Vine card in the DOM.

**Comment by 6a68** [comment]
Actually, the video player doesn't clean out the URL when it loses focus, so if we can convert this awful-looking poster URL to a vine.co video URL, we'll be all set:

https://v.cdn.vine.co/r/thumbs/BADB0D95B11374464600027930624_5317be0c883.29.1.1E85681A-A5FF-40A7-A571-C49D9CE2A882.mp4.jpg?versionId=X0NAyKdy4_a01A10lpWwAu0VTp6XiBRy

**Comment by 6a68** [comment]
I guess we could also insert a page script that detects and listens for right clicks on the vine.co homepage. We'd probably have to use capturing to get to the events before ember has a chance to handle them. That could make this a lot easier, though.
