### ISSUE TITLE
The modal's gif wrongly displays the "Add to queue" button from the overlay

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#1217]
[Affected versions]:
- Firefox Developer Edition 59.0b3
- Firefox Nightly 60.0a1 (01/26/2018)
- Min-Vid Shield Study Onboarding 0.4.7 - Shield Study

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid v.0.4.7 Shield Study Onboarding ("activeAndOnboarding" variant) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.youtube.com website.
3. Observe the gif of the modal.

[Expected result]:
- The gif displays only the "Play Now" button from the overlay.

[Actual result]:
- The gif wrongly displays the "Add to queue" button from the overlay.

[Notes]:
- Attached a screenshot of the issue:

![add to queue wrong](https://user-images.githubusercontent.com/26000308/35444645-d9d22b84-02b7-11e8-8bc9-e91e873a10d9.png)

**Comment by wresuolc** [comment]
@meandavejustice can you link to an xpi please. thanks

**Comment by johngruen** [comment]
Closing this b/c i'v egot a pr that resolves both
