### ISSUE TITLE
The modal is not displayed if opening YouTube through middle click and not focusing the tab until it loads completely

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#1218]
[Affected versions]:
- Firefox Developer Edition 59.0b3
- Firefox Nightly 60.0a1 (01/26/2018)
- Min-Vid Shield Study Onboarding 0.4.7 - Shield Study

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid v.0.4.7 Shield Study Onboarding ("activeAndOnboarding" variant) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. From the new tab page, right click on the YouTube card.
3. Click on "Open Link in New Tab" option.
4. After the YouTube tab is completely loaded, focus it and observe what happens next.

[Expected result]:
- The modal is displayed.

[Actual result]:
- The modal is not displayed.

[Notes]:
- Attached a screencast of the issue:

![middle click youtube](https://user-images.githubusercontent.com/26000308/35446177-93e5ee94-02bc-11e8-91a1-4a63dc9e0639.gif)

**Comment by wresuolc** [comment]
thanks for filing.  this is edge-casey enough that we aren't going to fix it for the shield study
