### ISSUE TITLE
proposed: shield studies want all studies to end with @shield.mozilla.org

### ISSUE THREAD

**Issue by gregglind** [meandavejustice/min-vid#1257]
What would the impacts be for you? 
- break prefs?
- break assumptions / checking for co-install with the shield version?
- (anything else)?

Thanks!

Gregg

**Comment by meandavejustice** [comment]
I don't think it will affect us, it should be a very simple change. I'll do a test build with it now and comment if anything breaks.

**Comment by meandavejustice** [comment]
merged in #1258
