### ISSUE TITLE
Vimeo video doesn't load when clicking overlay icon

### ISSUE THREAD

**Issue by kaganjd** [meandavejustice/min-vid#127]
- clicked from https://vimeo.com/97364872
- error message: `"resp.json.request is undefined"`, line 9 of get-vimeo-url.js

<img width="400" alt="screen shot 2016-08-17 at 10 36 24 am" src="https://cloud.githubusercontent.com/assets/9204835/17740599/38a85264-6467-11e6-9324-32bfeb52570d.png">

- clicked from https://vimeo.com/96505122
- error message: `"resp.json.request is undefined"`, line 9 of get-vimeo-url.js
<img width="400" alt="screen shot 2016-08-17 at 10 51 25 am" src="https://cloud.githubusercontent.com/assets/9204835/17740995/b069f3a6-6468-11e6-885f-b182d3fb78d8.png">

**Comment by kaganjd** [comment]
Some videos do work with the overlay icon. Ex: sending this video to Min-Vid _does_ work: 
- https://vimeo.com/139433350

<img width="400" alt="screen shot 2016-08-17 at 10 55 39 am" src="https://cloud.githubusercontent.com/assets/9204835/17741201/4cb422fe-6469-11e6-83fb-8b425c3b071a.png">

**Comment by meandavejustice** [comment]
Ursula k le Guin is my hero

**Comment by meandavejustice** [comment]
we now have error handling for these cases (when the uploader has specified no embeds)
