### ISSUE TITLE
Min Vid remains open if the browser is closed with more than one tab opened

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#1271]
[Notes]:
- See also: [618 ](https://github.com/meandavejustice/min-vid/issues/618) and [539](https://github.com/meandavejustice/min-vid/issues/539).

[Affected versions]:
- Firefox 58.0.2 and up
- Min Vid 0.4.8 (built on 02/21/2018)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.4.8) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to YouTube and send a video to the player.
3. Click the "+" button from the tab strip in order to open a new tab.
4. Click the "x" button from the browser (#[618](https://github.com/meandavejustice/min-vid/issues/618)).
5. Click the "Cancel" option from the dialog box and send another video to the mini player.
6. Click on the "x" button from the browser and select "Close tabs" option.
7. Observe what happens next.

[Expected result]:
- The Min Vid player and the browser are both closed.

[Actual result]:
- The browser is closed, but the Min Vid player remains open.

[Additional Notes]:
- The issue is also reproducible with the Test Pilot and Shield Study versions of the add-on.
- The issue is not reproducible if setting the "browser.tabs.warnOnClose" pref to false.
- Attached a screen recording of the issue:

![min vid close](https://user-images.githubusercontent.com/26000308/36490626-57923c8e-1731-11e8-83c9-0676225db289.gif)

**Comment by 6a68** [comment]
@meandavejustice I can look at this one

**Comment by meandavejustice** [comment]
moving out of milestone, will apply fix to master and push update to test pilot before end of week
