### ISSUE TITLE
Automate uploads to s3

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#13]
What is our process for deploying/hosting the packaged and signed addon?
- amo?
- gh-releases?
- gh-pages?
- people.mozilla.org?

**Comment by 6a68** [comment]
Maybe just use the same S3 approach that one of the existing add-ons is using? Might be really nice to create some kind of command-line utility that test pilot add-ons (or other non-AMO-hosted add-ons) can reuse.

**Comment by wresuolc** [comment]
Let's use S3 w/ a script to sign from AMO and upload automatically

**Comment by meandavejustice** [comment]
example scripts => https://github.com/mozilla/testpilot/tree/master/addon/bin

**Comment by pdehaan** [comment]
FWIW, here's Activity Stream's fabfile for XPI signing and S3 deploying. Uses Node+Python, which may not be the most ideal solution here: https://github.com/mozilla/activity-stream/blob/master/fabfile.py

**Comment by meandavejustice** [comment]
I have received my aws keys, so this is back in progress

**Comment by wresuolc** [comment]
This is not important for the launch.  We can always do this manually.

**Comment by meandavejustice** [comment]
Signing is complete, right now we are handing off manually to wil.
