### ISSUE TITLE
Fix "send-to-tab" for vids that don't have a video ID

### ISSUE THREAD

**Issue by kaganjd** [meandavejustice/min-vid#130]
We send most videos to Min-Vid by using a video ID to construct a link to video or to make an API call to get the link we need. But with Vine videos sent from the Vine homepage, we just parse the MP4 link out directly; there's no video ID or API call. 

"Send-to-tab" works by using the `getPageUrl` function to reconstruct a regular URL from the `id`, `domain`, and `time`. 

How can we get "send-to-tab" to work when there's no ID? One option is sending the MP4 link straight to the browser. If we go that route, would it be worth figuring out how to make this option independent of the domain in case we have future situations where there's no ID and just a direct MP4 link?

**Comment by meandavejustice** [comment]
Let's put this off until after MVP. Vine support is our lowest priority until launch. If we are worried about it, we can just disable the `send-to-tab` button for videos that don't have an id

**Comment by meandavejustice** [comment]
I will probably hack together a version which will fetch vimeo and put it into an embed, like we are doing with youtube. @kaganjd don't worry about this for now. I will unassign you

**Comment by pdehaan** [comment]
+1 to this, trying to do this for a Vine.co video just sends me to https://vine.co/v/null, which is not a great user experience:

![vine](https://cloud.githubusercontent.com/assets/557895/18799093/bb09dd46-818a-11e6-8737-fde4986eb097.png)

**Comment by meandavejustice** [comment]
tested today. no longer an issue
