### ISSUE TITLE
Window is out of monitor

### ISSUE THREAD

**Issue by ROBsoer** [meandavejustice/min-vid#1308]
Each time when I launch the **min vid** it moves up. And if before the window of **min vid** was close to the top edge of the display next time it will be out of the edge. And I haven't found any possibility to get it back
[min vid position](https://monosnap.com/file/d4bBNmiHbNbr3j5qCq2zTpUFi71ZDz.png)

OS: Win 10

**Comment by Softvision-CristinaBadescu** [comment]
Thanks for reporting this issue. However, this is a dupe of #842 .
