### ISSUE TITLE
Video playback is stopped after maximizing a minimized video 

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [meandavejustice/min-vid#133]
[Affected versions]:
- Nightly 51.0a1
- Min-Vid v0.1.1

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on (v0.1.1) is installed and enabled on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a video from vimeo.com or youtube.com.
2. Click on the overlay icon to send the video to Min-Vid.
3. Press the play button in the Min-Vid player.
4. Click on the "Minimize" icon in the Min-Vid player.
5. After the player is minimized click on the maximize icon in the player.
6. Observe how to video is rendered.

[Expected result]:
- Video playback continues playing after maximizing.

[Actual result]:
- Video playback is stopped and cannot be restarted by clicking on play / pause button.

[Notes]:
- Skipping the video from the progressbar won't work neither, minimizing and maximizing Min-Vid won't restart the video playback.
- Video playback can be restarted only by choosing to send the video again to Min-Vid.
- Added a screen recording with the issue.
![minimize_issue](https://cloud.githubusercontent.com/assets/20083658/17779730/5c132c14-6571-11e6-8e7a-d215bfc25395.gif)

**Comment by kaganjd** [comment]
I know the bug says affected platforms = Windows. I tried but couldn't reproduce this on Mac OS X. Screen recording here: https://www.dropbox.com/s/fg0pexb8e5zhtsc/max-min-bug.mov?dl=0

**Comment by pdehaan** [comment]
I can repro in Nightly w/ min-vid 0.1.1 on macOS.
I'm trying to watch https://www.youtube.com/watch?v=CB-tFLCShyU and if I minimize the video in Min Vid, it loses audio and the video is paused (I was hoping to keep listening in background). After un-minimizing, it doesn't restart the video/audio, no matter if I toggle the play/pause button in the top-left, or click on the middle and toggle the built-in YouTube play/pause functionality.

**Comment by meandavejustice** [comment]
@pdehaan Would you mind testing again, I'm having trouble reproducing today on my linux machine. I'm looking into getting an osx testing machine but I've yet to make that happen.

**Comment by SoftVision-EmilPasca** [comment]
This issue is still reproducible on Nightly 51.0a1 using the latest Min-Vid add-on (v0.1.6) on Windows 10 x64.

**Comment by meandavejustice** [comment]
I just saw this on OSX in FF48 as well. Though it was more of a pause.

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest version (0.1.8).
