### ISSUE TITLE
Video playback is stopped when trying to resize the browser window

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [meandavejustice/min-vid#134]
[Affected versions]:
- Nightly 51.0a1
- Min-Vid v0.1.1

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on (v0.1.1) is installed and enabled on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a video from vimeo.com or youtube.com.
2. Click on the overlay icon to send the video to Min-Vid.
3. Press the play button in the Min-Vid player.
4. Resize the window a few pixels in any direction.
5. Observe the video playback.

[Expected result]:
- Video playback continues playing whatever the browser window size is.

[Actual result]:
- Video playback is stopped and cannot be restarted by clicking on play / pause button.

[Notes]:
- Skipping the video from the progressbar won't work neither, minimizing and maximizing Min-Vid won't restart the video playback.
- Video playback can be restarted only by choosing to send the video again to Min-Vid.
- Added a screen recording with the issue.
![onwindowscrollissue](https://cloud.githubusercontent.com/assets/20083658/17779816/b3ddd37c-6571-11e6-8004-1261f4760408.gif)

**Comment by meandavejustice** [comment]
The [resize handler](https://github.com/meandavejustice/min-vid/blob/master/index.js#L284) in `index.js` is the culprit here. I wonder if #136 could help with this here. Otherwise we will need to let the panel know if it needs to resume playback after being rerendered from window resize events.

**Comment by meandavejustice** [comment]
This may be fixed in #136

**Comment by meandavejustice** [comment]
@SoftVision-EmilPasca Would you mind verifying if this is still and issue?

**Comment by meandavejustice** [comment]
Okay this is cause by the same issue as #133. Hiding and showing the panel

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest version (0.1.8).
