### ISSUE TITLE
Hide the window shadow while dragging on Mac

### ISSUE THREAD

**Issue by 6a68** [meandavejustice/min-vid#137]
On MacOS, there's a box shadow chasing the player as it's dragged around.

The fix is to set `-moz-window-shadow: none` on the panel while dragging.

I wasn't able to test this in the debugger, some debugger bug, I think. But it should work, it's used a lot in dxr.

**Comment by meandavejustice** [comment]
How do you set css props on the actual `panel`? Do you have an example you can link to?

**Comment by 6a68** [comment]
@meandavejustice You can get the panel like this: `let el = getActiveView(panel)`. `getActiveView` comes from view/core.

To style it, you can just `setAttribute('style', inlineStyles)` to set inlineStyles. This is done in a couple places in dxr: https://dxr.mozilla.org/mozilla-central/search?q=panel.setAttribute+style&redirect=false

**Comment by 6a68** [comment]
Hmm, I think you might have to set the styles in the older style: `panelElement.style.property = value`. I can take this bug.

**Comment by 6a68** [comment]
This was fixed by #179. Closing :tada:
