### ISSUE TITLE
What should we call this thing?

### ISSUE THREAD

**Issue by 6a68** [meandavejustice/min-vid#14]
Ideas (feel free to insert others):

- picture in picture
- video multitasking
- video to go (v2g, confusingly close to b2g)

**Comment by meandavejustice** [comment]
I like picture in picture, mostly because I've always found pIpTVs fascinatingly absurd.

![](https://usercontent1.hubstatic.com/5785708_f496.jpg)
![](http://content.photojojo.com/wordpress/wp-content/uploads/2011/07/transparent-big.jpg)

**Comment by kaganjd** [comment]
throwing some more out there:
multiview
multiwatch
mini view
two view

**Comment by johngruen** [comment]
I've asked our new Firefox content strategist to look into this. I'll keep it assigned to me, but expect a brainstorming session after London to finalize. My vote: _There is a video that never goes out_

**Comment by 6a68** [comment]
@johngruen do we have final signoff on 'lil peeper' yet?

**Comment by 6a68** [comment]
Reassigning to Wil to make sure any copyright/legal/naming issues get resolved

**Comment by meandavejustice** [comment]
*bump*

**Comment by meandavejustice** [comment]
Finalizing on `Min Vid`
