### ISSUE TITLE
Specific videos from YouTube are not loaded in player

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [meandavejustice/min-vid#148]
[Affected versions]:
- Nightly 51.0a1
- Min-Vid v0.1.1

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on (v0.1.1) is installed and enabled on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a video from youtube.com.
2. Click on the overlay icon or right-click on a video from the side-bar and choose from the context menu "Send to mini player" to send the video to Min-Vid.
3. Wait for Min-Vid to load the video.

[Expected result]:
- Video is loaded into Min-Vid.

[Actual result]:
- "Loading video from youtube.com" message is displayed in Min-Vid no matter how long you wait. 

[Notes]:
- The web browser console throws the same error for YouTube videos that are not loaded. See the attached file: 
[min vid error for youtube videos.txt](https://github.com/meandavejustice/min-vid/files/436866/min.vid.error.for.youtube.videos.txt)

- The issue isn't reproducible with some youtube videos that are similar to the ones from the following channel:  https://www.youtube.com/channel/UCNkTUGmCDngofrGsjlnElFg/featured
- Added a screen recording with the issue: http://goo.gl/c3a9uU

**Comment by meandavejustice** [comment]
this is a pre-embed api bug, closing
