### ISSUE TITLE
The "Sent to mini player" option is displayed for YouTube and Vimeo homepage on New Tab tiles

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [meandavejustice/min-vid#152]
[Affected versions]:
- Nightly 51.0a1
- Min-vid v0.1.1

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-vid add-on version (v0.1.1) was installed on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to youtube.com page or vimeo.com.
2. Visit YouTube or Vimeo pages.
3. Open a new tab.
4. Right click on YouTube or Vimeo homepage tiles and observe the context menu.

[Expected result]:
- The "Sent to mini player" option is not displayed in context menu.

[Actual result]:
- The "Sent to mini player" is displayed in context menu. 

[Notes]:
- If you chose the "Sent to mini player" option, the player is opened even if there is nothing to play. The "Loading video from youtube.com" message is displayed no matter how long you wait.
- Added a screen recording with the issue: http://goo.gl/rBvogV.

**Comment by meandavejustice** [comment]
can't reproduce with version `0.1.3`. Though I did find https://github.com/meandavejustice/min-vid/issues/163
