### ISSUE TITLE
Overlay icon sometimes interacts with existing player interface on YT, Vimeo

### ISSUE THREAD

**Issue by kaganjd** [meandavejustice/min-vid#159]
YouTube example:
<img width="200" alt="3af99216-65fd-11e6-9305-d8601f7a1031" src="https://cloud.githubusercontent.com/assets/9204835/18101480/7a3cca00-6eb4-11e6-825e-92a6260400e3.png">

Vimeo example:
<img width="200" alt="41ffd610-65fd-11e6-86c3-676bb54ab813" src="https://cloud.githubusercontent.com/assets/9204835/18101503/840ca01e-6eb4-11e6-943d-c561658f94c3.png">

**Comment by meandavejustice** [comment]
Probably not a concern for mvp, what do you think @johngruen
