### ISSUE TITLE
MVP User Stories

### ISSUE THREAD

**Issue by 6a68** [meandavejustice/min-vid#16]
What are the core user stories for the MVP?

Here's a guess at one story:
- As a user, I want to watch videos in a persistent player in the corner of the screen as I browse the web using Firefox.

This doesn't describe whether we want the player to follow the application focus between windows. One viewer per Firefox is probably easier to understand than one viewer/playlist per window within Firefox.

**Comment by johngruen** [comment]
@6a68 @meandavejustice one thing @ryanfeeley turned me on to is doing user testing starting with "so that..." (for example: "so that I can watch videos while flipping between websites in firefox, i want a little video player in the corner of firefox that stays on top").

**Comment by meandavejustice** [comment]
@6a68 Do you think we can close this one?

**Comment by 6a68** [comment]
@meandavejustice sure, let's close it out
