### ISSUE TITLE
YouTube video ads can be very distracting

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#165]
<img width="379" alt="menubar" src="https://cloud.githubusercontent.com/assets/557895/18151022/5cf26fd0-6fa0-11e6-8d86-304c9f6d5973.png">

You can close the ad, but yeah...

**Comment by meandavejustice** [comment]
ugh

**Comment by meandavejustice** [comment]
Unfortunately they do not allow us to do anything about this in their terms. :(
