### ISSUE TITLE
Odd gap on the right of the video scrubber bar

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#166]
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/18151074/ec8317d0-6fa0-11e6-81ec-8f5e3dfd165c.png)

When I play the https://www.youtube.com/watch?v=iHzzSao6ypE video (nothing special, just a light colored background), I see a weird gap on the lower, right edge:

![_r_videos_and_browser_console_and_csv_parser___node_js_csv_project_and_blok_web-ext-artifacts_at_master_ _mozilla_blok](https://cloud.githubusercontent.com/assets/557895/18151067/ce41f912-6fa0-11e6-9e91-ab94cfddc0bc.png)

**Comment by kaganjd** [comment]
This is fixed in open PR #157. @meandavejustice would you mind reviewing?

**Comment by meandavejustice** [comment]
fixed in #157
