### ISSUE TITLE
Sometimes dragging min-vid player causes it to shift within the frame

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#167]
Continuing my trend of garbage bugs with not enough context or repro steps...

I've hit this 2-3 times this afternoon where I go to do something and interact w/ Min Vid player and end up accidentally dragging the window, but it doesnt move the video, but instead it shifts the video within the iframe/window that it's in, meaning the video just gets clipped and cropped in unexpected ways.

![_r_videos_and_browser_console_and_csv_parser___node_js_csv_project_and_blok_web-ext-artifacts_at_master_ _mozilla_blok](https://cloud.githubusercontent.com/assets/557895/18151284/e507e150-6fa2-11e6-974f-46eb89eb8ab0.png)

**Comment by pdehaan** [comment]
This gets funnier. I can't seem to fix it.
If I open a new tab, the video still follows me to the new tab, I cant right click the video and try and force close it (because it brings up the YouTube context menu).
I can't get the video to start scrolling vertically again so I can find the "X" button in the corner.

Wondering if I have to disable/enable the add-on from about:addons.

**Comment by pdehaan** [comment]
OK, progress! (it's like live-tweeting, but for GitHub issues)

I did fix it by removing the add-on, then hitting "undo" because i meant to disable, not remove it.

But I can reliably reproduce this in my FF Nightly by clicking on the video scrubber in Min Vid and then dragging. CLicking on the video itself just does the YouTube play/pause toggle dance.

![_r_videos_and_browser_console](https://cloud.githubusercontent.com/assets/557895/18151713/047196a0-6fa6-11e6-9f79-92a50723e9e0.png)

**Comment by meandavejustice** [comment]
@pdehaan Thanks for finding this. @6a68 is working on a big drag refactor right now. Once he is done we will be dropping our current buggy method of expanding the panel and dragging with react-draggable. Should take care of this bug.
