### ISSUE TITLE
Youtube video not playing on Nightly/Linux with 0.1.4

### ISSUE THREAD

**Issue by wresuolc** [meandavejustice/min-vid#176]
This is using 0.1.4 on Nightly on Linux.  I do have some other add-ons installed, and I can disable them if it comes down to it.

To reproduce:

1) Load https://www.youtube.com/watch?v=m3lF2qEA2cw (fails with all youtube videos for me)
2) Click the Min Vid icon in the top left of the video

The "Loading video from www.youtube.com" frame appears and just spins.  The console says a few interesting things like:

> Invalid URI. Load of media resource  failed.

> The resource from “https://www.youtube.com/api/stats/ads?device=1&ns=1&sdkv=h.3.0&ver=2.0&break_type=1&event=1&cpn=n19DkoDc78nhtHBe&content_v=m3lF2qEA2cw&mt=0&ei=ZcvJV8LrBIaUqQXR9q6IDA&lact=6250&vol=100&vis=0&p_w=854&p_h=480&rt=1472842603759” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).

> The resource from “https://www.youtube.com/player_204?rt=9.195&allowed=1_2_1%2C1_1%2C1_3%2C2_2_1%2C2_1%2C2_3&ex_ad=2%3D1_2%3B25%3D2_2%2C15_2%3B46%3D14_14%3B59%3D14_14%3B65%3D15_2%2C15_2_1%2C15_2_4%3B68%3D14_14&fs=false&volume=100&mos=0&fmt=244&afmt=251&plid=AAU7iuPQlB2fnQZQ&ei=ZcvJV6DpKoq0qgWu7rSgBg&cpn=n19DkoDc78nhtHBe&v=m3lF2qEA2cw&creationTime=9702.84&totalVideoFrames=203&droppedVideoFrames=0&corruptedVideoFrames=0&ns=yt&html5=1&el=detailpage&a-ch=UCORIeT1hk6tYBuntEXsguLg&a-id=f2e568ff-9ac1-4d28-afb5-da5b652d6b84&a-type=68&a-v=m3lF2qEA2cw&l-class=6&link=http%253A%2F%2Fwww.postmodernjukebox.com%2Fevents&xble=0&p-time=7.79&iv-event=8&event=iv&ux=1” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).

> HTTP “Content-Type” of “text/html” is not supported. Load of media resource https://www.youtube.com/embed/m3lF2qEA2cw/?autoplay=0&modestbranding=1&controls=0&disablekb=0&enablejsapi=1&fs=0&iv_load_policy=3&loop=0&rel=0&showinfo=0 failed.  WebRequest.jsm:217:11

> NS_BINDING_ABORTED: Component returned failure code: 0x804b0002 (NS_BINDING_ABORTED) [nsIStreamListener.onStartRequest]  WebRequest.jsm:217

> Cannot play media. No decoders for requested formats: text/html

**Comment by meandavejustice** [comment]
@clouserw I'm having trouble reproducing this one. I'm able to load the video both with the overlay icon and context menu. I'll keep messing with it to see if I can make it happen. Would you mind trying to kill firefox and start it again and see if you have the same issue? I've had similiar issues(probably caching) with my addon autoloader script.

**Comment by wresuolc** [comment]
I think the problem might be a bad build?  Does https://testpilot.firefox.com/files/min-vid/min-vid-0.1.4-fx.xpi work for you on any system?

I've reproduced this on:
Nightly + Linux
Nightly + OS X
Nightly + Linux (on different computer)
Nightly + Linux (on another different computer)
Firefox 44 + Linux (clean profile)
Firefox 47 + Linux (clean profile)
