### ISSUE TITLE
min-vid doesn't play all the way to end of video?

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#184]
Using the XPI that you sent earlier in the week (0.1.1) and this random video (from https://reddit.com/r/videos):
https://www.youtube.com/watch?v=hU2jPw0mjaE

Play the video all the way to the end and you see: 
<img width="397" alt="_r_videos_and_downloads" src="https://cloud.githubusercontent.com/assets/557895/18221560/17f940f8-7134-11e6-8a3a-dd8ed8739af9.png">

Not sure why the video ends and only goes to 1:29 / 1:30, but I'll blame Maths + rounding.

---

Using a **min-vid@0.1.6** that I built locally, I still see this, although now the footer area fully expands horizontally, and the playback scrubber bar no longer has rounded corners:

<img width="360" alt="_r_videos_and_min-vid_doesn_t_play_all_the_way_to_end_of_video__ _issue__184_ _meandavejustice_min-vid" src="https://cloud.githubusercontent.com/assets/557895/18221613/3311d14c-7135-11e6-8d86-ee5cb2e9e6a8.png">

**Comment by pdehaan** [comment]
Same w/ https://www.youtube.com/watch?v=Fxa3m6F89FQ
<img width="443" alt="_r_videos_and_min-vid_doesn_t_play_all_the_way_to_end_of_video__ _issue__184_ _meandavejustice_min-vid" src="https://cloud.githubusercontent.com/assets/557895/18221579/8aa60afa-7134-11e6-90cb-40885b435208.png">

**Comment by meandavejustice** [comment]
@pdehaan apparently youtube embeds stop themselves right one second before completion. Thanks for reporting this, we also aren't canceling our stepping function when this happens. So we've been creating never ending intervals.

**Comment by meandavejustice** [comment]
I've been messing with this on and off the past couple of days and youtube's iframe stuff just doesn't want to cooperate here. I'm going to fix the issue where the setInterval isn't being cancelled when youtube embeds end themselves, and put the actual "ends one second off" part off until all the other mvp issues are complete.

**Comment by meandavejustice** [comment]
Moving this into `post-mvp` since the important part of this is being addressed in #207

**Comment by pdehaan** [comment]
Interesting twist... While randomly watching https://www.youtube.com/watch?v=2LtjGL1DkTE (via a link on /r/videos), it appears like YouTube.com reports the video is 7:10 long, whereas min-vid is reporting the length as 7:11 (which may be why we're never playing all the way to the end):

![henning_wehn_on_would_i_lie_to_you_-_youtube_and_promotions__24_750__-_peterdehaan_gmail_com_-_gmail_and_https___archive_org_wayback_available_is_not_available](https://cloud.githubusercontent.com/assets/557895/18444743/59d83dd8-78cf-11e6-9654-8df025e6e34b.png)

**Comment by meandavejustice** [comment]
@pdehaan Interesting, without directly looking at it, looks like this may be solved if we just display with `Math.floor`

**Comment by pdehaan** [comment]
Re: `Math.floor()`, perhaps. I tried (and failed, naturally) to figure out where to do some rounding. When I was adding `console.log()` locally, it was telling me that the duration was 213 seconds, so it was already an integer.
