### ISSUE TITLE
Icon overlay: only show on hover?

### ISSUE THREAD

**Issue by 6a68** [meandavejustice/min-vid#186]
The icon overlay can sometimes be annoying when watching a video on youtube.

Maybe we could fade it out after a few seconds without a mouseover? Maybe a long CSS opacity transition?

**Comment by meandavejustice** [comment]
Yeah I like this, gunna mark it for post MVP

**Comment by trlkly** [comment]
I'd prefer hiding until you move the mouse. Since that will also bring up the seek bar, it seems the appropriate time to also bring up the button. In fact, having it synchronize with the seek bar would make sense, fading out when it does.

**Comment by hashhar** [comment]
Did it get fixed because as of today on Nightly I can only see the overlay if I hover on the video? Or am I misunderstanding?

**Comment by trlkly** [comment]
I presume this bug means only hovering over the actual button. Hovering over the video is the current case.

Problem is, when full screen, it's impossible not to hover the cursor over the video. Hence my suggestion to have it show up with mouse movement on top of the video, just like the seek bar does.

**Comment by meandavejustice** [comment]
fixed in #420
