### ISSUE TITLE
The Min-Vid player does not change its position to the bottom left corner after the browser is set in fullscreen (F11)

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#187]
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.1.6-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.1.6-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to a website with videos supported by Min-Vid player (eg: YouTube, Vimeo, etc).
3. Send a video to the mini player.
4. Put the browser in fullscreen mode.
5. Observe the Min-Vid player position.

[Expected result]:
- The Min-Vid player detects the extra space and moves closer to the edge of the screen.

[Actual result]:
- The Min-Vid does not change it's position.

[Notes]:
- On Windows there is enough space under the player for the Windows toolbar, but it is hidden and not actionable while the browser is in fullscreen.
- Attached a screenshot of the issue.
  ![normal browser window](https://cloud.githubusercontent.com/assets/18304511/18248871/906f4cd4-7383-11e6-887f-09d1ec35ba32.png)
  ![fullscreen browser window](https://cloud.githubusercontent.com/assets/18304511/18248873/941d3fa8-7383-11e6-8b46-15e077ed6f27.png)

**Comment by meandavejustice** [comment]
@SoftVision-CiprianMuresan is this still an issue with the new windowing code? from #475

**Comment by SoftVision-CiprianMuresan** [comment]
@meandavejustice nope, it is no longer reproducible on the latest version.
