### ISSUE TITLE
The volume speaker icon doesn't change according to the volume levels

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#189]
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.1.6-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.1.6-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to a website with videos supported by Min-Vid player (eg: YouTube, Vimeo, etc).
3. Send a video to the mini player.
4. Lower the volume to 25% and observe the volume icon.
5. Raise the volume to 50%(or 75%) and observe the volume icon.

[Expected result]:
- The volume icon represents the current volume levels.

[Actual result]:
- The volume icon doesn't change regardless of the volume levels.

[Notes]:
- Attached a screen recording of the issue http://goo.gl/78dDfT.

**Comment by meandavejustice** [comment]
Do we want the icon to change as described above @johngruen?

**Comment by meandavejustice** [comment]
We don't have this in the mockups. Closing as `wont fix`

**Comment by SoftVision-CiprianMuresan** [comment]
Based on [this](https://mozilla.invisionapp.com/share/8D7I15MZP#/screens/163789000) we do have mock-ups for the Volume icon. Our full functional test suite was made based on that mock-up.

**Comment by meandavejustice** [comment]
@johngruen Do you happen to have the assets for quarter and half volume for the speaker icons?

**Comment by meandavejustice** [comment]
ping @johngruen not a huge priority, but if we can get assets for the volume icon, this would be a `good-first-bug` for contributors. cc/ @youwenliang
