### ISSUE TITLE
Overlay is not available for related videos on YouTube

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#190]
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.1.6-dev

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on version (0.1.6-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to YouTube and click on a video to play it.
3. Hover over the related videos on the right side of the page.

[Expected result]:
- The Min-Vid overlay is shown for the videos in the list.

[Actual result]:
- The overlay is not shown, but the videos can be sent to the Min-Vid player from context menu.

[Additional Notes]:
- Attached a screen recording of the issue http://goo.gl/tC8P2r.

**Comment by meandavejustice** [comment]
I just reproduced this. Lower priority, but would be nice to get this in `post-mvp`

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest build (0.1.9).
