### ISSUE TITLE
Two clicks are needed to Start/Pause playback if the browser is unfocused

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#191]
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.1.6-dev

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on version (0.1.6-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to a website with videos supported by Min-Vid player (eg: YouTube, Vimeo, etc).
3. Send a video to the mini player and choose to play it.
4. Click anywhere outside the browser window (eg: Windows Start bar).
5. Hover mini player "Pause" button and click it.

[Expected result]:
- The video is paused.

[Actual result]:
- Nothing happens.

[Additional Notes]:
- The issue is not reproducible on Mac OS X.
- The native YouTube player works with just one click.
- Attached a screen recording of the issue http://goo.gl/JKCisV.

**Comment by meandavejustice** [comment]
Sounds like an upstream issue of firefox itself. I will do some digging in bugzilla so we can at least confirm/track it.

**Comment by SoftVision-CiprianMuresan** [comment]
I was able to reproduce the issue on older builds aswell. I went as far back as Nightly 45.0a1, Build ID 20151202115311. I can't go further to check since the add-on is not working on versions under 45.x, but don't think the issue is with Firefox itself.
However with builds downloaded through mozregression the issue can't be reproduced.

**Comment by meandavejustice** [comment]
I don't know if I classify this as a bug. It seems reasonable that firefox would want to establish focus in certain contexts before allowing click events through. That being said, this may have been fixed in #274 .

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest build (0.1.9).
