### ISSUE TITLE
add alternative method to move panel on linux

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#192]
In linux we have to disable the draggability of the panel, since it's support is so poor. We should
provide another minimal method for linux users to move the panel. I'm thinking a toolbar button which opens a panel with little buttons, `NW`, `SW`, `NE`, and `SE` which can be clicked to move the panel. We will save the users preference in simple-storage.

**Comment by 6a68** [comment]
We should also update the `system.platform` check in this bug, see this comment for details: https://github.com/meandavejustice/min-vid/pull/193#discussion_r77683819

**Comment by devanes** [comment]
I can drag it perfectly in Xubuntu by keeping Alt pressed when dragging it around. But I don't see any drag button. I just press alt and start dragging  (Like any other window)

**Comment by alxpl** [comment]
Same thing on Fedora (so far I've only tested on F23) with Gnome and  "Window Action Key" set to "Alt" in Gnome Tweak Tool. The min vid panel can be dragged anywhere on the desktop.

**Comment by 6a68** [comment]
#475 made the panel draggable (and resizable!) on linux
