### ISSUE TITLE
I can drag the video inside the draggable xul box thing

### ISSUE THREAD

**Issue by johngruen** [meandavejustice/min-vid#197]
Not quite sure how to describe this bug but it's pretty bad. Maybe @meandavejustice old dragging code is still present w/in the new draggable?

https://www.dropbox.com/s/ku37nhe4s8qfd1g/Screen%20Shot%202016-09-06%20at%206.01.56%20PM.png?dl=0

**Comment by meandavejustice** [comment]
fixed in #193
