### ISSUE TITLE
Min-Vid player continuously flickers when hovered it if the drag bar is moved under the Windows taskbar

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#199]
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.1.6-dev

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on version (0.1.6-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to a website with videos supported by Min-Vid player (eg: YouTube, Vimeo, etc).
3. Send a video to the mini player and choose to play it.
4. Move the player down so that the drag bar is a bit under the Windows taskbar.
5. Hover the Min-Vid player.

[Expected result]:
- Nothing out of the ordinary happens.

[Actual result]:
- The player keeps rapidly shifting up and down, not settling on a position and the player controls are unactionable.

[Additional Notes]:
- Attached a screen recording of the issue http://goo.gl/b8OL9Z.

**Comment by 6a68** [comment]
This is a great bug report, thank you!

**Comment by meandavejustice** [comment]
@6a68 Was this fixed in #214 ?

**Comment by 6a68** [comment]
This might have been fixed. I'll leave it open for now, and we can verify after MVP ships.

**Comment by 6a68** [comment]
Should be fixed by #475

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest build (0.3.3).
