### ISSUE TITLE
Make video view draggable

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#2]
We need to find a component ([like panel](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/panel)) that is draggable.

**Comment by kaganjd** [comment]
I spent a few days researching/trying different ways to make the panel draggable. I didn't make any progress, but here are some resources I found:

[Content panels](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Tutorial/Content_Panels)

[Panels](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/panel)

[Popup panels, XUL](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/PopupGuide/Panels)

[Floating popup panels, XUL](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/PopupGuide/Floating_Panels)

[XUL panel on StackOverflow](http://stackoverflow.com/search?q=xul+panel)

[Discourse thread about draggable panel objects](https://discourse.mozilla-community.org/t/how-to-make-panel-objects-resizeable-and-or-draggable/5753/4)

**Comment by 6a68** [comment]
This was eventually fixed by #179 :tada:
