### ISSUE TITLE
Doesn't work for youtu.be links?

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#20]
Randomly browsing https://www.reddit.com/r/videos and noticed that it seems to work for www.youtube.com videos, but not shortened youtu.be URLs:

Good: https://www.youtube.com/watch?v=pA42DpvDbMs
Bad: https://youtu.be/fp3Hr2wwjzg

**Comment by meandavejustice** [comment]
I love that I can test/reproduce this just by right clicking links in the issue description.

**Comment by pdehaan** [comment]
![](http://s.mlkshk-cdn.com/r/2HR7.gif)

**Comment by kaganjd** [comment]
fixed with #29
