### ISSUE TITLE
The Minimized player maximizes itself after resizing the browser window

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#201]
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.1.6-dev

[Affected Platforms]:
- All Windows
- All Mac 
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.1.6-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to a website with videos supported by Min-Vid player (eg: YouTube, Vimeo, etc).
3. Send a video to the mini player.
4. Click the "Minimize" player button and resize the browser window.
5. Observe the Min-Vid Player behavior after resizing the browser window.

[Expected result]:
- The player remains in minimized state after resizing the window.

[Actual result]:
- The player maximizes when resizing the window and wrongly displays the appearance for the minimized state

[Additional Notes]:
- The Minimize button still appears as if the player is minimized even if it is not.
- The issue is also reproducible if you send a different video to the mini player while it is minimized.
- The issue is also reproducible if you send the window in fullscreen (F11)
- Attached a screen recording of the issue http://goo.gl/fwhs5R.

**Comment by 6a68** [comment]
Fixed by #214

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest version (0.1.8).
