### ISSUE TITLE
Replicate player state for vimeo embeds

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#206]
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.1.6-dev

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on version (0.1.6-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to Vimeo and click on a video.
3. Send it to the mini player from the overlay.
4. Observe the Vimeo video player.

[Expected result]:
- Clicking the Min-Vid overlay has no effect on the Vimeo video player.

[Actual result]:
- Clicking the Min-Vid overlay also starts the Vimeo video player.

[Additional Notes]:
- Attached a screen recording of the issue http://goo.gl/m5HF7d.

**Comment by meandavejustice** [comment]
related to #215

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is still reproducible on the latest build (0.1.9) with #215 merged. In my opinion this issue should be moved to mvp because Min-Vid's behavior should be consistent regardless of the source the video is playing from.

**Comment by meandavejustice** [comment]
@6a68 was still seeing this on mac and windows. I need to reproduce on my windows machine and fix from there.

**Comment by SoftVision-CiprianMuresan** [comment]
I'm not seeing this on the latest signed build (0.2.8) on Firefox release, neither on Windows 10 or on Mac 10.11.
However, @meandavejustice could the same thing that was implemented in #215, for YouTube videos, be implemented for Vimeo videos as well?

**Comment by meandavejustice** [comment]
@SoftVision-CiprianMuresan Yes that is definitely the goal for vimeo as well. It will probably be included in the first big update
