### ISSUE TITLE
Disable right click mouse events in the Min-Vid player

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#210]
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.1.6-dev

[Affected Platforms]:
- All Windows
- All Mac 
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.1.6-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to YouTube.
3. Send a video to the mini player and chose to play it.
4. Right click the video in the Min-Vid player.

[Expected result]:
- Nothing happens.

[Actual result]:
- The Youtube video context menu is opened.

[Notes]:
- The context menu is to big to fit inside de Min-Vid player and some options are unclickable. From our perspective the options from the context menu are not very useful after the video has been sent to the player.
- Attached a screen recording of the issue http://goo.gl/4av3Ex.

**Comment by meandavejustice** [comment]
Thanks @SoftVision-CiprianMuresan good find

**Comment by meandavejustice** [comment]
related to #216

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest version (1.0.8).
