### ISSUE TITLE
Version 0.1.6 really likes to disappear

### ISSUE THREAD

**Issue by johngruen** [meandavejustice/min-vid#213]
This is the signed XPI we gave Sharon for user testing. 

# STR

start a min vid video, and click anywhere or do anything. Video disappears, audio remains. Only fix is to quit the browser.

https://www.dropbox.com/s/qn3g3ilflxagb4z/min-vid-disappear-error.mov?dl=0

**Comment by wresuolc** [comment]
I uninstalled the add-on which stopped the audio. :)  but yeah, this is busted. talking on IRC now to get something before the user testing.
