### ISSUE TITLE
Clicking the middle of the video to play/pause doesn't update the controls

### ISSUE THREAD

**Issue by wresuolc** [meandavejustice/min-vid#218]
This is with min vid 0.1.8

STR:

0) Linux + Nightly, load https://www.youtube.com/watch?v=m3lF2qEA2cw
1) Click min-vid button
2) pause main player
3) click middle of min-vid to start playing
4) observe the progress bar and play button.  Play button doesn't change to pause, and progress bar doesn't move

You can play/pause the video from here without any updates to our UI.  I don't know if this is related to #216 as there isn't much detail there, but it might be.

**Comment by meandavejustice** [comment]
Yeah this is the same as #216 I'll copy over your description and close this as a dupe
