### ISSUE TITLE
Vimeo videos can not be played by clicking on the video area

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#220]
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.1.8-dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.1.8-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to Vimeo and send a video to the mini player.
3. Click inside the Min-Vid player.

[Expected result]:
- The video starts playing.

[Actual result]:
- Nothing happens.

[Additional Notes]:
- Attached a screen recording of the issue http://goo.gl/Hz2fKh.

**Comment by meandavejustice** [comment]
Should be addressed in #216

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest build (0.1.8).
