### ISSUE TITLE
YouTube links that have "attribution_link" don't work after being sent to the mini player

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#221]
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.1.8-dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.1.8-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Open the test case found [here](https://jsfiddle.net/ko48py5u/).
3. Send the second link to the mini player through the context menu option.
4. Click the "Play" button from the player controls.

[Expected result]:
- The video is played.

[Actual result]:
- Nothing happens.

[Additional Notes]:
- "Play"/"Replay" buttons don't work.
- Attached a screen recording of the issue http://goo.gl/4dlWvk.

**Comment by 6a68** [comment]
Thanks very much for the great test case, @SoftVision-CiprianMuresan :beers:

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest version (0.1.8).
