### ISSUE TITLE
Min-Vid video player has white borders on Mac

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#222]
![white border on mac](https://cloud.githubusercontent.com/assets/18304511/18435115/f41cec02-78f9-11e6-816b-e61908acb7c0.png)

[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.1.8-dev

[Affected Platforms]:
- All Mac

[Prerequisites]:
- Latest Min-Vid add-on version (0.1.8-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to a website with videos supported by Min-Vid player (eg: YouTube, Vimeo, etc).
3. Send a video to the mini player.
4. Observe the edges of the Min-Vid player container.

[Expected result]:
- The video fills the whole container.

[Actual result]:
- There is a white border surrounding the Min-Vid player container.

[Additional Notes]:
- The build from 09.09.2016 did not have this border.
- Attached a screenshot of the issue.

**Comment by meandavejustice** [comment]
Any idea of what might have changed here? @6a68

**Comment by 6a68** [comment]
This looks fixed to me, now that #214 has landed.

@SoftVision-CiprianMuresan, could you try to repro again?

**Comment by 6a68** [comment]
I can't repro this on my mac or on win 10. @meandavejustice said he was seeing it on linux.

**Comment by SoftVision-CiprianMuresan** [comment]
Can no longer repro on the latest build, neither on Mac or Ubuntu 15.04.
