### ISSUE TITLE
Submit upstream fix for parsing attribution_link youtube urls to get-video-id

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#226]
refs #221

**Comment by radiovisual** [comment]
Ok, get-video-id now supports attribution links via version `1.1.0` via npm.

🎉

**Comment by meandavejustice** [comment]
Woah thanks @vickychijwani and @radiovisual

**Comment by meandavejustice** [comment]
@vickychijwani would you want to submit a pr to bump our `get-video-id` dependency to `1.1.0`?

**Comment by vickychijwani** [comment]
@meandavejustice sure
