### ISSUE TITLE
npm watchpost not detaching workers?

### ISSUE THREAD

**Issue by 6a68** [meandavejustice/min-vid#233]
See discussion in #195, seems like workers might be getting left behind when npm watchpost uninstalls/reinstalls the dev addon.

**Comment by meandavejustice** [comment]
Probably an issue with how we are unloading the addon. Should put in place `onUnload` handler like we have in the [testpilot addon](https://github.com/mozilla/testpilot/blob/master/addon/index.js#L342)

https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Listening_for_load_and_unload
