### ISSUE TITLE
Ads displayed inside the Min-Vid player cannot be closed

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#234]
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.1.8-dev

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on version (0.1.8-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to YouTube.
3. Send a video to the Min-Vid player and play the video.
4. Close the ad displayed on top of the video inside the Min-Vid player.

[Expected result]:
- Ads can be closed.

[Actual result]:
- When clicking on the Close "X" button for the ads, the video is paused/resumed.

[Additional Notes]:
- This behaviour may be side effect of #228 .
- [Here](https://github.com/meandavejustice/min-vid/files/469248/cannot.close.ads.zip) is a video of the issue.

**Comment by 6a68** [comment]
yup, this definitely could be a consequence of swallowing mouse events (#228)

**Comment by 6a68** [comment]
@Softvision-VladBacia Hey, could you verify that this is fixed? I wasn't able to get youtube to show me an ad in the player.

**Comment by Softvision-VladBacia** [comment]
@6a68 , I've verified this issue and it is no more reproducible on latest version (0.1.8).
