### ISSUE TITLE
min-vid should work on more than one window

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [meandavejustice/min-vid#236]
[Affected versions]:
- Nightly 51.0a1
- Min-Vid v0.1.8

[Affected Platforms]:
- All Linux
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on (v0.1.8) is installed and enabled on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to youtube.com.
2. Click on the overlay icon or right-click on a video and choose "Send to mini player" option from the context menu.
3. Open a new window and navigate again to youtube.com.
4. Repeat step 2 for one of the displayed videos.

[Expected result]:
- Min-Vid overwrites the first video and loads the second one.

[Actual result]:
- Min-Vid doesn't load the video, player displays a white colored background and the controls are missing.

[Notes]:
- Depending on what we want, we could either overwrite the video or open a second mini-player since whe have two different windows. But I assume the above expected behavior would be the less complicated.
- Added a screen recording with the issue: http://goo.gl/DLfx5s
- Attached the browser console error report:
[minvid_browser_console_error.txt](https://github.com/meandavejustice/min-vid/files/469723/minvid_browser_console_error.txt)

**Comment by 6a68** [comment]
Talked this over with @meandavejustice in IRC. Here's the plan:

- Rather than create one min-vid player per browser window, create one per-Firefox instance.
- Send requests from any window to that same player.
- Position the window relative to the viewport, not any given browser window, but do start it off in the corner of the opening window.

**Comment by 6a68** [comment]
FWIW, the actual implementation is: when you switch windows, destroy and re-create the panel at the same coordinates. This is what we could get done, that worked nicely, in time :beers:

**Comment by SoftVision-EmilPasca** [comment]
The issue is still reproducible on the latest build (0.1.9), however, the actual results has changed, now, instead of displaying a white colored background, the player isn't displayed at all and the only way to bring it back is by restarting the browser.

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest build (0.1.9).
