### ISSUE TITLE
Vimeo videos are not loading after being sent to the Min-Vid player

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#237]
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.1.8-dev

[Affected Platforms]:
- All Windows
- All Mac 
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.1.8-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to Vimeo.
3. Send a video to the mini player and chose to play it.

[Expected result]:
- The videos is played.

[Actual result]:
- The Min-Vid player is stuck on the "Loading video from vimeo.com" screen.

[Notes]:
- On yesterday's build this worked as expected (09.12.2016).
- Attached a screenshot of the error in the browser console.
- Attached a screen recording of the issue http://goo.gl/qCXVl3.

![vimeo videos are not loading](https://cloud.githubusercontent.com/assets/18304511/18473347/1adc6cc0-79c5-11e6-98a5-2fac0567002a.png)
![vimeo videos are not loading1](https://cloud.githubusercontent.com/assets/18304511/18473350/1c648f8c-79c5-11e6-9be7-dcfb48e037c8.png)

**Comment by meandavejustice** [comment]
possibly related to #211

**Comment by meandavejustice** [comment]
@SoftVision-CiprianMuresan can you see if this is still an issue now that #211 has been resolved?

**Comment by meandavejustice** [comment]
Not able to reproduce

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest build (0.1.8). I had to use Friday's Nightly in order to test this.
