### ISSUE TITLE
Dragging fast causes UI icons to flicker

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#242]
Ref: https://github.com/meandavejustice/min-vid/pull/214#issuecomment-246501255

> My eyes also see that when you hover over the _move-icon_ all the other controls disappear (which I assume is on purpose), but due to dragging lag when I drag the video player window around quickly, it's possible that my mouse speed is faster than the repaint speed, so I'm seeing controls fade in and out as I'm dragging that video popup quickly.
> 
> Sorry, hard to explain in words, but I don't know of a good way to capture a video/GIF screenshot and post it here.
> 
> ![min-vid-pr214](https://cloud.githubusercontent.com/assets/557895/18453805/d0ec6658-78f5-11e6-9826-3450946b69b6.gif)

**Comment by 6a68** [comment]
This should be fixed by #475
