### ISSUE TITLE
Dragging icon behavior is different on minimized vs maximized players

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#247]
When dragging a "regular" (maximized) video player, all the controls are hidden when you hover/drag using the move icon.

![r_gaming](https://cloud.githubusercontent.com/assets/557895/18494555/9b642aa8-79cb-11e6-93d9-f72dcc32e7a4.png)

But when you drag a minimized player, the controls are _not_ hidden. Not a big deal, but a bit inconsistent:

![r_gaming](https://cloud.githubusercontent.com/assets/557895/18494598/e76de98e-79cb-11e6-8d71-7b1b9886075f.png)

**Comment by 6a68** [comment]
#475 removed the drag icon; closing
