### ISSUE TITLE
Panel doesn't move when window is resized

### ISSUE THREAD

**Issue by 6a68** [meandavejustice/min-vid#25]
I guess the panel is getting positioned relative to the top left corner of the window, since it doesn't move if you reduce the window's height by dragging the bottom edge upward (see screenshots).

We should either position the panel relative to the bottom left, add a window resize listener to reposition the panel as the window's resized, or consider positioning the panel somewhere else.

<img width="584" alt="screen shot 2016-05-18 at 5 32 54 pm" src="https://cloud.githubusercontent.com/assets/96396/15379113/b1caaae2-1d1e-11e6-854f-1e1a67421a34.png">
<img width="700" alt="screen shot 2016-05-18 at 5 33 21 pm" src="https://cloud.githubusercontent.com/assets/96396/15379114/b1cbfa14-1d1e-11e6-89ff-73f47cb9f3ea.png">

**Comment by meandavejustice** [comment]
This seems like an upstream bug that we may not address, need to checkout addon-sdk bug tracker(bugzilla) and verify.
