### ISSUE TITLE
Min-Vid Player position is affected by the resizing of the browser window

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#253]
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.1.8-dev

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on version (0.1.8-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Resize the browser window to half the screen.
3. Drag and drop the Min-Vid Player outside the browser window to the left.
4. Horizontally resize the browser window towards the left.

[Expected result]:
- The browser window is resized and the Min-Vid player remains in its place.

[Actual result]:
- The Min-Vid player is moved towards the left together with the browser window.

[Additional Notes]:
- Attached a screen recording of the issue https://goo.gl/TP1LKC.

**Comment by 6a68** [comment]
This is exactly how the panel is currently positioned: it's relative to the bottom left of the browser window. So it's not a bug.

However, we're going to change to _one_ min-vid panel per Firefox, not per browser window, so the positioning will be relative to the user's screen, not any browser window.

Up to @meandavejustice if he wants to leave this open or close.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is still reproducible on the latest build (0.1.9). See [here](https://goo.gl/4KRqsd).
