### ISSUE TITLE
Player drag handle is not working when browser is set to fullscreen mode

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [meandavejustice/min-vid#254]
[Affected versions]:
- Nightly 51.0a1
- Min-Vid v0.1.8

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on (v0.1.8) is installed and enabled on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to youtube.com.
2. Hover over a video and click the overlay icon or right-click on a video and choose "Send to mini player" option from context menu.
3. Press the "F11" key for fullscreen mode and hover the min-vid player.
4. Move the player on the screen by clicking and holding the player drag "handle" button.

[Expected result]:
- Min-Vid moves to the new mouse cursor position.

[Actual result]:
- Min-Vid doesn't change it's position.

[Notes]:
- Added a screen recording with the issue: https://goo.gl/KAPIzL

**Comment by 6a68** [comment]
This will also be fixed when we switch to one globally positioned panel.

**Comment by 6a68** [comment]
Fixed by #475

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest build (0.3.3).
