### ISSUE TITLE
Flash embeds don't work inside panel element

### ISSUE THREAD

**Issue by 6a68** [meandavejustice/min-vid#26]
There's a known bug filed about this: https://bugzilla.mozilla.org/show_bug.cgi?id=952578

The last comment in that bug from anyone on the FF team: "There is no progress on this problem, nobody is assigned to look at it, and as far as I know it's not a high priority."

Unless we figure out the SDK bug, or figure out if the bug occurs on a non-SDK panel, we won't be able to support any video sites that are flash based.

**Comment by meandavejustice** [comment]
@clouserw mentioned this in the etherpad. He basically said if we can't support flash then ¯\_(ツ)_/¯. Which I'm cool with. I say if we can get it working rather easily then :+1: otherwise, we'll just do modern video.

**Comment by wresuolc** [comment]
flash is dead.  let it RIP

**Comment by meandavejustice** [comment]
![](https://images.duckduckgo.com/iu/?u=http%3A%2F%2F1.bp.blogspot.com%2F_spYrFr9P7ms%2FTMbuL0dOazI%2FAAAAAAAAAZQ%2FZ_VD0gqFZPc%2Fs1600%2Fflash-tombstone.jpg&f=1)
