### ISSUE TITLE
The same Vimeo video will not load in the Min-Vid player if it was previously sent to a new tab

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#261]
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.1.8-dev

[Affected Platforms]:
- All Windows
- All Mac 
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.1.8-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to Vimeo.
3. Send a video to the mini player and chose to play it.
4. Click "Send to tab" from the player controls.
5. From the newly opened tab send the video used at step 3 to the mini player.

[Expected result]:
- The videos is played.

[Actual result]:
- The Min-Vid player is stuck on the "Loading video from vimeo.com" screen.

[Notes]:
- Attached a screen recording of the issue https://goo.gl/LkQLGZ.

**Comment by meandavejustice** [comment]
The issue was in the upstream `get-video-id` library we are using.
I've opened an upstream issue https://github.com/radiovisual/get-video-id/issues/3
Will be fixing for us and submitting an upstream fix on monday morning.

**Comment by radiovisual** [comment]
Things in `get-video-id` should be resolved now. Just update to version `1.0.1` and you should be good to go.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest build (0.1.8).
