### ISSUE TITLE
Min-Vid player is displayed wrongly sized when sending a video to it [windows nightly]

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [meandavejustice/min-vid#266]
[Affected versions]:
- Nightly 51.0a1
- Min-Vid v0.1.8

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on (v0.1.8) is installed and enabled on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to youtube.com.
2. Hover over a video and click the overlay icon or right-click on a video and choose "Send to mini player" option from context menu.
3. Observe the Min-Vid player.

[Expected result]:
- Min-Vid player is displayed normally sized and correctly positioned on the screen.

[Actual result]:
- The player is displayed wrongly sized. It has a square shape and a very small frame.
- Only the "play", "move" and "audio" buttons are visible.
- The player cannot be resized or closed.

[Notes]:
- Sending videos multiple times also moves the player upwards until is almost completely hidden.
- Added a screen recording with the issue: https://goo.gl/cZf3S3
![minvid_player_error_wrongly_sized](https://cloud.githubusercontent.com/assets/20083658/18631790/bc1281fe-7e7c-11e6-8f6f-6530e4f54ff2.gif)

**Comment by SoftVision-EmilPasca** [comment]
This issue is a blocker, because of this we cannot test other functionalities.

**Comment by SoftVision-EmilPasca** [comment]
Fresh install with a new profile.

**Comment by SoftVision-EmilPasca** [comment]
We have investigated this issue and performed a regression on Windows 10 x64, here are the results:

Last good revision: e3fa462347c8c863e310d4e0e45e470c9775bdcd
First bad revision: 1430290455ed94109e973fd17c7f62865e1695c9
Pushlog:
https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=e3fa462347c8c863e310d4e0e45e470c9775bdcd&tochange=1430290455ed94109e973fd17c7f62865e1695c9

Looks like the following bug has the changes which introduced the regression:
https://bugzilla.mozilla.org/show_bug.cgi?id=1294199

**Comment by ckprice** [comment]
Our numbers are showing < 2% of our visitors are using Nightly. Moving this to post-MVP.

**Comment by 6a68** [comment]
This should have been fixed by #315, I think.

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest build (0.2.8).
