### ISSUE TITLE
Min-Vid icon background, is displayed up to the upper border of the video thumbnail

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#269]
[Affected versions]:
- Nightly 52.0a1
- Min-Vid v0.1.8

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on (v0.1.8) is installed and enabled on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.youtube.com .
2. Hover over the video thumbnails.
3. Observe the Min-Vid icon and icon background.

[Expected result]:
- The Min-Vid icon background is displayed under the Min-Vid icon with a small border.

[Actual result]:
- The Min-Vid icon background is displayed from the icon until the top of the video thumbnail.

[Notes]:
- Added a screen recording with the issue: 

![min-vid icon background](https://cloud.githubusercontent.com/assets/9248513/18669692/ee9c8868-7f44-11e6-971d-334a431479ad.gif)

**Comment by meandavejustice** [comment]
I believe this is intentional, cc/ @johngruen

**Comment by johngruen** [comment]
Yeah, intentional
