### ISSUE TITLE
Videos are not loading in Min-Vid player, if they are sent consecutively

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#275]
[Affected versions]:
- Firefox Dev 50.0a2 (Build ID: 20160919004008)
- Min-Vid v0.1.8

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on (v0.1.8) is installed and enabled on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.youtube.com .
2. Send a video to the Min-Vid player.
3. Repeat step 2 multiple times, with random videos from the page.

[Expected result]:
- The Min-Vid player with video thumbnail and play button are displayed.

[Actual result]:
- After repeating step 2 multiple times (about 5 times) the video thumbnail is not loaded inside the video container and the "Loading video from youtube.com" message persists. The video will load after Min-Vid player is restarted of the video is sent again to the player.

[Notes]:
- [Here](https://drive.google.com/file/d/0B6QogV2AJFKiQ3dXRnRqYVdVV28/view?usp=sharing) is a screen recording with the issue:

**Comment by Softvision-VladBacia** [comment]
Maybe this issue is related to #273.

**Comment by meandavejustice** [comment]
Not related to #273. That is specific to vimeo.

I'm seeing an error when trying to get the video's duration when this happens.
I'm guessing it loads snappy when clicking around then gets to a larger video and `onLoaded` is called before the duration info has been determined by the embed player. Will probably visit this `post-mvp`

**Comment by meandavejustice** [comment]
Closing for #328. As it includes the console error and includes more up to date info
