### ISSUE TITLE
A specific YouTube video cannot be played in Min-Vid player

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#276]
[Affected versions]:
- Firefox Dev 50.0a2 (Build ID: 20160919004008)
- Min-Vid v0.1.8

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on (v0.1.8) is installed and enabled on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.youtube.com .
2. Go to https://goo.gl/6aooce .
3. Send the video to Min-Vid player.
4. Play the video.

[Expected result]:
- Video has successfully started playing.

[Actual result]:
- Inside the video container is displayed an error because the video could not be loaded.

[Notes]:
- [Here](https://drive.google.com/file/d/0B6QogV2AJFKiTVF0TVNsbDRhalk/view?usp=sharing) is a screen recording with the issue.
- The video can be played without issues in YouTube.

**Comment by wresuolc** [comment]
I can reproduce this.  I assume something the rights-holder chose about disallowing embedding

**Comment by meandavejustice** [comment]
I can also repro. @wresuolc We should handle that error case. I'll add this to #280 meta bug.

**Comment by meandavejustice** [comment]
Error handling for this case landed in #292

**Comment by Softvision-VladBacia** [comment]
The issue is no longer reproducible on the latest build (0.1.9).
