### ISSUE TITLE
Clicking on the video seek bar changes video state and Play/Pause buttons are flickering

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#277]
[Affected versions]:
- Firefox Dev 50.0a2 (Build ID: 20160919004008)
- Min-Vid v0.1.8

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on (v0.1.8) is installed and enabled on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.youtube.com .
3. Send the video to Min-Vid player.
4. Click on the video seek bar at random positions.
5. Repeat step 4 (about 3-5 times).
6. Observe the Play/Pause button and video state.

[Expected result]:
4. When clicking on the video seek bar the video player does not change state from play to pause and vice versa. If the video is on pause it should not play if the seek bar is clicked and the same for play state. It should play only when the user selects play and it should pause only when the user selects pause.
6. Play/Pause button are correctly displayed.

[Actual result]:
4. When clicking on the seek bar the video changes state to play or paused.
6. Play/Pause button is flickering.

[Notes]:
- [Here](https://drive.google.com/file/d/0B6QogV2AJFKidk1aR2llU2FCdzg/view?usp=sharing) is a screen recording with the issue.
- The video cannot be put on pause from the Pause button.
- If Play/Pause button is flickering when the video has ended, the video will be automatically restarted.

**Comment by 6a68** [comment]
Looks like this bug is still occurring in master if you pause, then click the time slider:

![](https://www.dropbox.com/s/7uxiv8cgoem1imn/minvid-play-pause-bug.gif?dl=0&raw=true)

**Comment by pdehaan** [comment]
To clarify, I was able to reproduce this on a random YouTube video, but NOT for Vimeo or Vine videos.
@meandavejustice thinks it may possibly be this code: [client-lib/yt-ctrl.js:77](https://github.com/meandavejustice/min-vid/blob/master/client-lib/yt-ctrl.js#L77)

**Comment by Softvision-VladBacia** [comment]
The issue is no longer reproducible on the latest build (0.2.8).
