### ISSUE TITLE
Clicking on the timeline pauses the video instead of jumping and playing

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#284]
### Steps to reproduce:
1. Go to https://www.youtube.com/watch?v=gDDorMeDvII
1. Send video to video player.
1. Enjoy a few seconds of amusement.
1. While video is actively playing back, click on the timeline bar to skip ahead to a future time.

### Actual results:
The video jumps ahead, but pauses playback. Now I need to start playback again.

### Expected results:
If the video was actively _playing_ while i did a seek, it should resume playback after the video jumped ahead/back.

**Comment by Softvision-VladBacia** [comment]
Hi @pdehaan , this issue seems to be a dupe of #277

**Comment by pdehaan** [comment]
@Softvision-VladBacia Sounds legit. Closing this as a dupe. :+1:
