### ISSUE TITLE
The context-menu option and the overlay icon are missing from gaming.youtube.com

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [meandavejustice/min-vid#291]
[Affected versions]:
- Nightly 51.0a1
- Min-Vid v0.1.9

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on (v0.1.9) is installed and enabled on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to https://gaming.youtube.com/.
2. Right-click or hover with the mouse on a video.

[Expected result]:
- Both the context-menu option and the video overlay icon are available on gaming.youtube.com

[Actual result]:
- Both the context-menu option and the video overlay icon are missing from gaming.youtube.com

[Notes]:
- After navigating to a video from gaming.youtube.com, the overlay icon is available only in the main video.
- Added a screen recording with the issue: https://goo.gl/EAW3GE
  ![issue_youtube_gaming](https://cloud.githubusercontent.com/assets/20083658/18753932/8f292efc-80ef-11e6-8c38-54e51b5f39a0.gif)

**Comment by Softvision-MariusComan** [comment]
On the latest Min Vid (built on 09/07/2017), the overlay is now correctly displayed on video thumbnails and playing videos. However we're still missing context menus, but that's due to #892.
