### ISSUE TITLE
Too many things can be sent to min-vid from YouTube site

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#304]
### Steps to reproduce:
1. Go to https://www.youtube.com/watch?v=WATSFMnnZPE
2. Right click on the "Upload" button in the upper-right corner.
3. Right click the submitter name.

![high_fiven_white_guys_catch_mariners_fever_-_youtube_and_rawgit](https://cloud.githubusercontent.com/assets/557895/18796856/ff4fa8b0-817f-11e6-9f95-2ee7c668afe5.png)

![fullscreen_9_23_16__11_23_am](https://cloud.githubusercontent.com/assets/557895/18796920/50399150-8180-11e6-93dd-84995045c76f.png)

**Comment by meandavejustice** [comment]
Thanks @pdehaan I think my scope for the context menus is too large for the watch page.

**Comment by meandavejustice** [comment]
Some fixes for this are in #325. There are still a couple of cases where the menu option is applied when it shouldn't be. The upload button is one example.

**Comment by SoftVision-CiprianMuresan** [comment]
I found some more ways you can send channels to the player:

1. Navigate to YouTube.
2. Search for a channel name (eg. movies).
3. Right click the channel and observe the context menu option.
![after searching for a channel name](https://cloud.githubusercontent.com/assets/18304511/18917154/8dfe8716-859f-11e6-98c1-072281588f9b.png)


And:

1. Navigate to YouTube.
2. Click on a channel name.
3. Click on the "Channels" tab.
4. Right click on the channel names and observe the context menu option.
![yt channels tab](https://cloud.githubusercontent.com/assets/18304511/18917165/937cc39c-859f-11e6-8ed9-ba470af781b1.png)

**Comment by SoftVision-CiprianMuresan** [comment]
Found one more way to do this:

1. Navigate to YouTube.
2. Hover a channel name.

**Comment by johngruen** [comment]
I think this is resolved at this point
