### ISSUE TITLE
Set timeout for "loading video" page

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#306]
I sent a YouTube video to the mini player a few minutes ago, and then resumed watching a bunch of Vines on vine.co, and noticed that my original YouTube video never loaded and is still stuck at the spinner.

Not sure if we want to set some `setTimeout()` where we display an error message with a link to the YouTube source video after 10-20s if we can't play the video for whatever reason. But being stuck on that loading page kind of smells, since I have zero recollection of what video it was.

![thomas_cannon_iii_-_vine_and_min-vid_package_json_at_master_ _meandavejustice_min-vid](https://cloud.githubusercontent.com/assets/557895/18799433/60d92172-818c-11e6-9a80-08f0f5881aab.png)

**Comment by pdehaan** [comment]
I'm still seeing this in the signed v0.2.8 build.
I've been staring at this for the past few minutes.

<img width="359" alt="set_timeout_for__loading_video__page_ _issue__306_ _meandavejustice_min-vid" src="https://cloud.githubusercontent.com/assets/557895/18895686/55c789ee-84d0-11e6-9eb0-b7de07d2e570.png">

<img width="677" alt="add-ons_manager" src="https://cloud.githubusercontent.com/assets/557895/18895701/77f34134-84d0-11e6-9d1b-9efe7fa5b3d4.png">

**Comment by Softvision-VladBacia** [comment]
I can also reproduce this issue in v0.2.8 build. The loading video screen is displayed indefinitely when the error `TypeError: window.YTPlayer.getDuration is not a function...bundle.js:120:15` occurs.

**Comment by meandavejustice** [comment]
I think this is fixed. Would yall mind taking another look?

**Comment by meandavejustice** [comment]
https://github.com/meandavejustice/min-vid/blob/master/components/player-view.js#L43
