### ISSUE TITLE
Player not displaying in Beta, Dev Edition, or Nightly

### ISSUE THREAD

**Issue by 6a68** [meandavejustice/min-vid#307]
In current Nightly, if you try to load a video, nothing happens, and you'll eventually see an error in the browser console: `unable to find panel after 10 seconds`.

I think the problem is with the code that detects whether the panel is ready or not: seems like the panel's `backgroundFrame` no longer has its `src` attribute set to that of the frame; instead we need to check `panel.backgroundFrame.contentWindow.location`.

**Comment by 6a68** [comment]
Hmm, looks like the SDK now constructs the panel differently, and making the panel draggable assumes the old way of constructing the XUL DOM. I think I'll need to rearrange some operations, but I'm out of gas for today.

**Comment by 6a68** [comment]
One of the problems I'm seeing is that the panel now appends a new `<browser>` element each time show() is called. This is a known bug (https://bugzil.la/1304379, filed 2 days ago). I can just clean out any extra frames as a workaround.

**Comment by 6a68** [comment]
Current nightly is 52, which is [scheduled](https://wiki.mozilla.org/RapidRelease/Calendar) to hit dev edition (aka aurora) on November 7, so we have a lot of time to figure this out.

**Comment by Softvision-VladBacia** [comment]
@6a68 ,

**Comment by pdehaan** [comment]
@ckprice Do we know the % of Test Pilot users on Release vs all other channels?

**Comment by 6a68** [comment]
# Current Plan

1. Right now, I'm going to get a branch together that just uses the regular SDK panel, removing all our (now broken) XUL hacks that make the panel transparent, draggable, and always on top.
2. I'll screenshot it in Mac and Windows, so JSON_voorhees can get a look at it.
3. I'll also package that branch as an xpi, so that QA can test it overnight. I'll reply to the thread Wil is going to start about this issue, and include a link to the xpi.
4. Once that's done, I'll go back to debugging the fancy panel and see how far I can get before we have to make the call on which to use.

If you have questions, ping me here or in #min-vid.

I'll keep this bug updated as I go through the steps.

**Comment by 6a68** [comment]
OK, I've got a working version of the addon with the standard panel styling.

Download the unsigned xpi here: http://people.mozilla.org/~jhirsch/min-vid-addon/

The branch is here: https://github.com/6a68/min-vid/tree/307-unstyled-panel

I've opened a pull request, in case we decide to merge this branch: https://github.com/meandavejustice/min-vid/pull/314

**Comment by 6a68** [comment]
This bug is due to changes in just two files in the addon SDK. If we copy over the last working versions of those two files, everything works like it used to.

https://github.com/meandavejustice/min-vid/pull/315 is a branch that does exactly this.

It's a very unusual approach, but it would buy us time to find a permanent fix, without sacrificing the niceness of draggability.

I'll add this unsigned xpi to the same people page: https://people.mozilla.org/~jhirsch/min-vid-addon/

I think it might make sense for QA to bang on both and see if one seems more robust.

**Comment by Softvision-VladBacia** [comment]
@6a68, we've tested both Min-Vid builds (#314, #315) and from our point of view we would suggest that the Min-Vid build with the fancy panel (#315) is the best approach. #315 has the drag and always on top feature enabled, while #314 has some minor issues like: #201 and #191.

**Comment by 6a68** [comment]
@Softvision-VladBacia Thanks very much for the feedback! It's very appreciated.

Looks like Dave landed #315 earlier this morning, so I'm going to close this bug. I'll reopen another bug to clean up the copy-pasted files.
