### ISSUE TITLE
Min vid pings missing object/method

### ISSUE THREAD

**Issue by wresuolc** [meandavejustice/min-vid#311]
We're seeing a bunch of Min Vid pings where object=overlay_icon and method=launch, but we're also seeing a lot of pings which are missing object, method, and domain completely...  I found this example in my about:telemetry from the 23rd:

```
{
  "test": "@min-vid",
  "version": "0.1.9",
  "timestamp": 6996,
  "variants": null,
  "payload": {
    "video_x": 1489,
    "video_y": 10,
    "video_width": 430,
    "video_height": 190
  }
}
```

Let's verify stats are being sent as documented in the metrics doc.

**Comment by wresuolc** [comment]
We're also missing the `played_count` field in all pings

**Comment by rayborn** [comment]
We don't have a ton of launch data yet, but I wanted to raise a potential issue early.  I'm not seeing all the listed object/method combos (see [this Re:dash chart](https://sql.telemetry.mozilla.org/queries/1321#2314))

The majority of pings are still still missing **both** fields: 

I haven't seen the following metrics.md states either:
- contextmenu/activate - _this should be the a somewhat common state_
- error_view/render
- loading_view/render
- loading_view/close
- player_view/render
- player_view/send_to_tab
- player_view/mute - _but we did see ‘unmute’_
- overlay_icon/available - _this should be the most common state_

**Comment by rayborn** [comment]
I'll continue investigating tomorrow morning when our cron jobs load another day of data.  Ilana thinks that it's unlikely that this is a Spark bug mid-pipeline since we have quite a few correct states flowing through without issue.
