### ISSUE TITLE
Our x's and y's are whack-a-doodle

### ISSUE THREAD

**Issue by wresuolc** [meandavejustice/min-vid#312]
The documentation says:
```
    "video_x": 1200,                 // Distance in pixels from top of browser window
                                     // to top of Min Vid panel
    "video_y": 1150,                 // Distance in pixels from left side of browser
                                     // window to left side of Min Vid panel
```
And it looks like we're reporting that accurately in the pings, but x should be from the left, not the top, and y should be from the top.  

We should swap X and Y in the docs and in the code.

**Comment by rayborn** [comment]
Also, there are some negative y values (which are actually x values per this bug).  Is that a partially offscreen window?

**Comment by meandavejustice** [comment]
@rayborn Yes, you have the ability to position the panel outside of the browser window

**Comment by meandavejustice** [comment]
Looks like we aren't reporting correctly either https://github.com/meandavejustice/min-vid/blob/master/lib/send-metrics-data.js#L28
