### ISSUE TITLE
Bad performance on Vimeo after moving the progress bar in the Min-Vid player

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#316]
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.2.0-dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.2.0-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to Vimeo and play a video.
3. Send the video to the mini player and play it.
4. Move the video progress bar forward.
5. Hover the related videos up and down and right click one of the videos.

[Expected result]:
- The videos are highlighted and the context menu appears instantly.

[Actual result]:
- The videos are slowly highlighted and the context menu takes a while to appear.

[Notes]:
- After pausing and playing the video seems to fix the issue.
- Attached a screen recording of the issue https://goo.gl/5LH9M4.

**Comment by meandavejustice** [comment]
This may be fixed in #319

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is not reproducible on the latest build (0.2.8) on Firefox release (49.0.1) and on the latest Nightly with e10s disabled.
However it is reproducible on the latest Nightly with e10s enabled, so this leads me to believe this is an e10s compatibility issue.

**Comment by meandavejustice** [comment]
@SoftVision-CiprianMuresan Would you mind checking this one out again?

**Comment by 6a68** [comment]
Might be fixed by #475

**Comment by SoftVision-CiprianMuresan** [comment]
Lgtm. Verified on the latest Nightly (53.0a1) with the latest Min-Vid (3.3.0) build.
