### ISSUE TITLE
Min-Vid player buttons are not centered in the minimize state on Ubuntu 14.04 

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#332]
**[Affected versions]:**
-Firefox 45.0 and up
-Min-Vid 0.2.8 signed

**[Affected Platforms]:**
-All Linux

**[Prerequisites]:**
-Min-Vid add-on version (0.2.8) was previously installed on a clean profile.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to www.youtube.com. 
2. Send a video to the Min-Vid player.
3. Minimize the Min-Vid player.
4. Hover the mouse cursor over the minimized player.

**[Expected result]:**
-All buttons are displayed properly and are centered.

**[Actual result]:**
-Min-Vid player buttons are displayed in the lower part of the minimized player.

**[Notes]:**
-Volume slider button is truncated.

Fx Release
![2](https://cloud.githubusercontent.com/assets/9248513/18918226/c7a9c23e-85a2-11e6-889a-85ae488bd7b6.png)

Fx Nightly
![1](https://cloud.githubusercontent.com/assets/9248513/18918270/e237e48c-85a2-11e6-8dcc-ee8cb9dea182.png)

**Comment by vickychijwani** [comment]
I think this is fixed by #435.

**Comment by Softvision-VladBacia** [comment]
I have verified this issue with Min-Vid latest dev build and it is not reproducible. However, when I've tried with the Min-Vid build from Test Pilot, this issue was present.
