### ISSUE TITLE
Min-Vid player window can be resized on Ubuntu

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#334]
**[Affected versions]:**
-Firefox 45.0 and up
-Min-Vid 0.2.8 signed

**[Affected Platforms]:**
-All Linux

**[Prerequisites]:**
-Min-Vid add-on version (0.2.8) was previously installed on a clean profile.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to www.youtube.com. 
2. Send a video to the Min-Vid player.
3. Move the mouse cursor at the bottom of the Min-Vid window.
4. When the cursor has changed to drag state, drag the Min-Vid player to the bottom of the screen.
5. Release the mouse button.

**[Expected result]:**
-Min-Vid player windows cannot be resized.

**[Actual result]:**
-Te Min-Vid player can be resized and the player is displayed on the monitor height.

**[Notes]:**
-The min-Vid player can be resized on width and height.
-[Here](https://drive.google.com/open?id=0B6QogV2AJFKiX1E3TTdYQUZldlk) is a video of the issue.

**Comment by devanes** [comment]
Isn't this intentional? Readme:
> You can pop out, sticky, **resize**, and drag videos anywhere within the browser

Actually, within Xubuntu (xfwm), this doesn't work.

**Comment by CoWinkKeyDinkInc** [comment]
@devanes How do you resize the video?  It's too small for me to find it useful right now, anything will be helpful!

**Comment by devanes** [comment]
@CoWinkKeyDinkInc Unfortunately I can't either. And it's too small for me too. But according to the readme it should be possible.

**Comment by Softvision-VladBacia** [comment]
The resize feature will be implemented in #69 and it should be across all platforms (Mac, Linux, Windows). For now, the behavior described above is a bug.

**Comment by meandavejustice** [comment]
gunna `wontfix` this since real support is coming in #69 and this is more like a hidden feature
