### ISSUE TITLE
Volume is incorrectly set when Mute/Unmute actions are made, if the volume was previously set by the user

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#335]
[Affected versions]:
-Firefox 45.0 and up
-Min-Vid 0.2.8 signed

[Affected Platforms]:
-All Linux

[Prerequisites]:
-Min-Vid add-on version (0.2.8) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.youtube.com. 
2. Send a video to the Min-Vid player.
3. Move the volume slider button to 75%.
4. Click on "Volume" button in order to mute the sound.
5. Click again on "Volume" button in order to unmute the sound.

[Expected result]:
-The volume is set at 75%, at the volume level set by the user.

[Actual result]:
-The volume is set at 50%.

[Notes]:
-If the volume is set at 100% the mute/unmute option works correctly.
- If the volume is set between 51% and 99% when mute/unmute action is done the volume is set at 50%.
- If the volume is set between 0% and 49% when mute/unmute action is done the volume is set at 50%.
  -[Here](https://drive.google.com/open?id=0B6QogV2AJFKiTFpEdlFVTWNDUk0) is a video of the issue.

**Comment by Softvision-VladBacia** [comment]
This issue is also reproducible on Windows and Mac OS .

**Comment by SoftVision-PaulOiegas** [comment]
@meandavejustice - when you'll pick this up, we should consider a fix for all platforms and for all major supported websites since now we have multiple behaviors.

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible on the latest Min Vid version built on 4/11/2017.
