### ISSUE TITLE
Moving the browser window to a new position, leaves Min-Vid player behind even if it wasn't dragged before

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [meandavejustice/min-vid#337]
[Affected versions]:
-Firefox 45.0 and up
-Min-Vid 0.2.8 signed

[Affected Platforms]:
- All Linux
- All Windows
- All Mac OS

[Prerequisites]:
- Latest Min-Vid add-on (v0.2.8) is installed and enabled on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to youtube.com.
2. Click on the overlay icon or right-click on a video and choose "Send to mini player" option from the context menu.
3. Change the browser window position.

[Expected result]:
- Min-Vid player follows the browser window position.

[Actual result]:
- Min-Vid player remains at the same position.

[Notes]:
- Added a screen recording with the issue: https://goo.gl/w6zQtv

**Comment by meandavejustice** [comment]
fixed in #475

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest build (0.3.3).
