### ISSUE TITLE
[Nightly] 360 videos are scrambled whether in the min-vid window or not

### ISSUE THREAD

**Issue by Verdi** [meandavejustice/min-vid#338]
It seems just having min-vid installed makes 360 videos scrambled - you don't even have to pop it out into the min-vid player.  Here's a video to try this with - https://youtu.be/Ch3vVp1V3Ws
![screen shot 2016-09-28 at 12 34 58 pm](https://cloud.githubusercontent.com/assets/107992/18925111/333d9c08-8578-11e6-9702-6bc5ba15f06b.png)

**Comment by pdehaan** [comment]
Fascinating. I wasn't able to reproduce in latest Nightly and **min-vid@0.3.0** on macOS El Capitan. (But I have seen some similarly distorted min-vid videos in the past, but never the main embedded video).

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/18926413/8e0d4996-856c-11e6-8baf-cd1c4225e260.png)

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/18926487/d6f8cde2-856c-11e6-94e1-cb174a7bf286.png)

![min-vid-3d](https://cloud.githubusercontent.com/assets/557895/18926353/55c724e4-856c-11e6-9426-ab57a3ef6139.gif)
**Figure 1:** 3.6MB GIF: https://cloud.githubusercontent.com/assets/557895/18926353/55c724e4-856c-11e6-9426-ab57a3ef6139.gif

**Comment by Verdi** [comment]
Oh I'm using Sierra - maybe that's the difference.

**Comment by pdehaan** [comment]
@Verdi Are you using Firefox Release, Beta, Aurora/Dev Edition, or Nightly?

**Comment by Verdi** [comment]
Nightly - today's - same version as in your screenshot.

**Comment by meandavejustice** [comment]
This probably has something to do with how sdk `<panel>'s` are not hardware accelerated. This will probably be fixed up once #340 (switching to a window) is addressed.

**Comment by meandavejustice** [comment]
fixed in #475
