### ISSUE TITLE
Why a <panel>?

### ISSUE THREAD

**Issue by mstange** [meandavejustice/min-vid#340]
Panels aren't hardware accelerated on most platforms so video performance will be bad. It would be nice if you could use a top level window instead. Is the ability to mark a top level window as floating the only thing that's preventing you from using a top level window? If so, we can add the necessary capabilities to Gecko.

Another advantage of a regular window would be the ability to use the `-moz-window-dragging` property which gets you native dragging behavior on Windows and Mac without any lag.

**Comment by 6a68** [comment]
@mstange Great suggestion!

We started with an SDK panel, then wound up customizing it to make it draggable, and by the time I realized a window could work better, there wasn't quite enough time left before launch.

I'll start work on a window-based branch and ping you with questions. Hopefully we can get this working in time for a followup release next week.

**Comment by mstange** [comment]
Thanks!

Funnily enough, in yesterday's gfx meeting, we decided that "nobody should ever need to put a video in a panel", so this is an interesting data point.

**Comment by trlkly** [comment]
Will you remove the title bar for the window? I hope so.

**Comment by meandavejustice** [comment]
@trlkly Yes

**Comment by vickychijwani** [comment]
This will also make it possible to make Min-vid stay always-on-top, but not Firefox :+1:. Right now if I set always-on-top on the Min-vid panel (using Ctrl+Space to bring up the titlebar menu), Firefox as a whole appears on top.

**Comment by Noitidart** [comment]
One possible drawback with using a window - in the system taskbar, like on Windows, you'll see another icon for the window that opened. You can hide that, but that will require ctypes which I think you want to avoid.

**Comment by meandavejustice** [comment]
fixed in #475
