### ISSUE TITLE
[Linux - Gnome] Not in foreground when other application running

### ISSUE THREAD

**Issue by rugk** [meandavejustice/min-vid#346]
The window is only in foreground when switching between tabs in Firefox. It is even not on top when I just open the history window in Firefox.

Firefox 49.0.1 (installed as Mozilla binaries)
Gnome
Debian x64

I've read that it should be on the top even when other applications are running.

**Comment by 6a68** [comment]
@rugk Hi, thanks for filing this bug. Unfortunately, the behavior on Linux can be a bit irregular. We're working on moving from a panel to a window (#40), which should hopefully resolve this issue. Keep an eye out for another release in the next few weeks.

**Comment by trlkly** [comment]
@6a68 Did you get the bug wrong? That one points to updating the README and says it's already fixed.

And when you say "moving to a window," will you be hiding the titlebar? On LInux and windows?

**Comment by meandavejustice** [comment]
fixed in #475
