### ISSUE TITLE
Min-Vid player vanishes when accessing TestPilot menu

### ISSUE THREAD

**Issue by MonsieurLanza** [meandavejustice/min-vid#347]
Hello, I'm on ArchLinux' firefox 49.0.1 and just installed TestPilot mainly to test minvids. 
So I started testing it, and lanched this video http://www.blendernation.com/2016/09/28/import-svg-inkscape-blender/ 

Worked well, I was able to switch tabs... and decided to see what others testpilots were like. And poof ! My Minvid player vanished. The sound is still here, but the video itself is nowhere. I searched in all tabs, behind the window... No player.

**Comment by gusowski1** [comment]
i had this issue to with Firefox 49.0.1 64bit on Windows 8.1 and with an youtube video

**Comment by pdehaan** [comment]
Also reported as #343 (on Nightly + macOS El Capitan).
Seems specific to Test Pilot icon. Couldnt reproduce w/ Pocket, Activity Stream, or Page Shot door hangers.

**Comment by 6a68** [comment]
@MonsieurLanza Hi, thanks for the bug report. What window manager are you using?

**Comment by synotna** [comment]
Ditto in 49.0.1 32bit Windows with a youtube video

**Comment by schalkneethling** [comment]
Also 49.0.1 on MacOS Sierra

**Comment by synotna** [comment]
@6a68 did you overlook the non-Linux reports before renaming the issue, or should we open separate issues for other platforms? :)

**Comment by Softvision-VladBacia** [comment]
This issue is also reproducible on Windows 8.1, Windows 10 with Mozilla Firefox latest release 49.0.2 and latest Firefox Nightly 52.0a1 (Build ID: 20160928030201) using Min-Vid add-on v 0.3.0.

**Comment by MarkWisselink** [comment]
I had this same issue on windows 7 with latest firefox dev edition
this not only happens when clicking test pilot in the toolbar, but also some other apps ("Desktop notifications for Android" is where I first noticed it)

**Comment by freaktechnik** [comment]
I had this happen when opening the pushbullet panel from within the hamburger menu.

**Comment by mattyc3** [comment]
fwiw also reproducible on
ffox 52.0a1 (2016-09-23) (64-bit)
Ubuntu 16.04.1
Gnome 3.20
video disappears but audio continues when trying to drag player - everytime.

**Comment by meandavejustice** [comment]
This will be fixed in #340

**Comment by Doc94** [comment]
Also in:
W10 - Firefox 49.0.1
The Min-Vid is invisible or "minimize"

**Comment by meandavejustice** [comment]
fixed in #475
