### ISSUE TITLE
Mini Vid never complete "Enabling"

### ISSUE THREAD

**Issue by BritAmerican** [meandavejustice/min-vid#350]
I've tried 3 times now and have still managed to enable it.  I already have 3 other test pilot experiments active in 49.0.1 so I don't think it's the version or config but....

**Comment by ckprice** [comment]
@BritAmerican thank you for the report! I'm going to close this in favor of https://github.com/mozilla/testpilot/issues/1474. Please restart and try again. If you think it's something separate feel free to reopen.
