### ISSUE TITLE
Min-Vid page and uMatrix

### ISSUE THREAD

**Issue by karlcow** [meandavejustice/min-vid#352]
Hello.

If you go to the current page 
https://testpilot.firefox.com/experiments/min-vid

with this settings in uMatrix (aka blocking the telemetry), the page content never ever initializes.

![capture d ecran 2016-09-29 a 12 08 34](https://cloud.githubusercontent.com/assets/505230/18939755/95ea0df8-863d-11e6-9264-88977b78517b.png)

It stays in this state:

![capture d ecran 2016-09-29 a 12 10 07](https://cloud.githubusercontent.com/assets/505230/18939764/b1e8aec4-863d-11e6-8a87-dd24dc39ef6a.png)

**Comment by wresuolc** [comment]
It fails if it can't do the analysis-output.telemetry.mozilla.org ping.  That's a test pilot bug, not min vid.  Can you file this at https://github.com/mozilla/testpilot/issues ?  Thanks

**Comment by karlcow** [comment]
Thanks! Will do.
