### ISSUE TITLE
min-vid window disappears when clicking Test Pilot in toolbar

### ISSUE THREAD

**Issue by davehunt** [meandavejustice/min-vid#353]
Steps to reproduce:

1. Start a video playing in min-vid
1. Click the Test Pilot button in the toolbar

Expected:
min-vid window is unaffected

Actual:
min-vid window disappears, but audio continues to play. The only way I've found to restore the window is to start a new video playing.

**Comment by Softvision-VladBacia** [comment]
@davehunt, thank you very much for reporting this to us. 

Unfortunately this issue is a dupe of #347 .

**Comment by davehunt** [comment]
Thanks! Somehow I missed that when looking to see if it had already been reported.
