### ISSUE TITLE
Mini player stays black 

### ISSUE THREAD

**Issue by lhirlimann** [meandavejustice/min-vid#355]
- Load https://vimeo.com/183609858
- click the mini player icon and start the movie
- switch tab 
  -- mini player is visible
  -- controls are visible and active (eg somehting happens when I click on it)
  -- video is not visible, it plays fine in the original vimeo tab

Env : Fedora/24 , latest nightly, dom.ipc.processCount set to 100.

**Comment by meandavejustice** [comment]
Can't reproduce, after #475, closing
