### ISSUE TITLE
Strobe Light Effect

### ISSUE THREAD

**Issue by emilykaywhite** [meandavejustice/min-vid#357]
My player seems to be spazzing out and will switch back and forth between showing the video and the content behind the video in rapid fire.

**Comment by Softvision-VladBacia** [comment]
Hey @emilykaywhite  thanks for reporting this. Can you give me a little more info?
- Operating system
- Firefox version
- Link to video link (if u feel comfortable sharing)
- Any further steps to reproduce

**Comment by emilykaywhite** [comment]
Macbook OS X Yosemite 10.10.3
Firefox 48.0.1
I tried it with a bunch of different videos, and it kept happening. They were all on YouTube, though, if that information helps.

**Comment by Softvision-VladBacia** [comment]
I cannot reproduce this issue on Macbook OS X 10.10.5 using Firefox release version 49.0.1 and lates Nightly 52.0a1 (Build ID: 20160929030426). I've opened a random video from www.youtube.com and started playing it. While the video is playing I've opened 20 tabs with different content and switched between them using the keyboard buttons or the mouse. For my tests I've used a clean Firefox profile.

Please retest this using a use a new clean Firefox profile, maybe even safe mode, to eliminate custom settings as a possible cause and report back the results.
