### ISSUE TITLE
Player controls can be highlighted even if the pointer is around the control

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#359]
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.3.0-dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.3.0-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to a website with videos supported by Min-Vid player (eg: YouTube, Vimeo, etc).
3. Send a video to the mini player and choose to play it.
4. Hover the mouse cursor a bit under the player controls and observe the behaviour.

[Expected result]:
- The controls are not highlighted unless the mouse cursor is hovering them.

[Actual result]:
- Depending on where the mouse cursor is, the player control is highlighted and actionable.

[Additional Notes]:
- Attached a screen recording of the issue https://goo.gl/8GIyzr.

**Comment by johngruen** [comment]
@SoftVision-CiprianMuresan this is by design to increase the size of the hit targets
