### ISSUE TITLE
Some videos appear distorted after sending them to min vid player

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#364]
Found in 594953e (via `$ git rev-parse --short HEAD`)

---

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/18972584/9e6463d2-864e-11e6-9fe3-77ca62548a98.png)

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/18972595/aa4d7652-864e-11e6-8974-c735adea8727.png)

---

Looking through a few random /r/videos while working on a PR, and found a few more videos that looked distorted for me:
1. https://www.youtube.com/watch?v=yDsL5cHLWUg
2. https://www.youtube.com/watch?v=ymltNm4p2VY
### Actual results:

Both videos look fine on YouTube.com, but look distorted in the min vid player.
1. https://www.youtube.com/watch?v=yDsL5cHLWUg
   - YouTube: ![isininca_kuru_kafa_cikan_egzoz___exhaust_skull_hot_-_youtube](https://cloud.githubusercontent.com/assets/557895/18972618/d0e50942-864e-11e6-801e-6ba7f106d86e.png)
   - Min Vid: <img width="388" alt="isininca_kuru_kafa_cikan_egzoz___exhaust_skull_hot_-_youtube_and_new_issue_ _meandavejustice_min-vid_and_package_json_ _min-vid" src="https://cloud.githubusercontent.com/assets/557895/18972553/77b9f508-864e-11e6-852b-2f1b55f4c087.png">
2. https://www.youtube.com/watch?v=ymltNm4p2VY
   - YouTube: ![tough_crowd_with_colin_quinn__leary_vs__giraldo_-_youtube](https://cloud.githubusercontent.com/assets/557895/18972697/0ff56a00-864f-11e6-9859-fa1b5999655c.png)
   - Min Vid: <img width="408" alt="_r_videos_and_new_issue_ _meandavejustice_min-vid_and_package_json_ _min-vid" src="https://cloud.githubusercontent.com/assets/557895/18972526/5dd524dc-864e-11e6-9b62-3c0a441526bd.png">

I can't explain _why_ the videos get distorted in our player yet, but did notice both those images are square or 4:3 looking aspect. But probably a red herring considering the sheer number of videos I've stared at and how many of them must have been 4:3 and not widescreen aspect.

**Comment by Softvision-VladBacia** [comment]
We have verified this on Windows 8.1 using latest Nightly 52.0a1 with Min-Vid v0.3.0 and didn't encounter the issue. 
We **can reproduce** this issue on Mac OS X 10.12 using latest Nightly 52.0a1 with Min-Vid v0.3.0.

**Comment by meandavejustice** [comment]
This may have to do that we are still using an sdk <panel> which are not hardware accelerated. This may be solved when we move to using a window in #340

**Comment by meandavejustice** [comment]
fixed in #475
