### ISSUE TITLE
jeffmap in fullscreen prevents minvid from showing

### ISSUE THREAD

**Issue by asurkov** [meandavejustice/min-vid#368]
open http://www.thekillarneymap.com/ in chrome, enter into fullscreen, while minvid is showing, minvid is not visible anymore

**Comment by Softvision-VladBacia** [comment]
@asurkov thank you for reporting this. 
We have verified this on Windows 8.1 using latest Nightly 52.0a1 with Min-Vid v0.3.0 and didn't encounter the issue. 
We **can reproduce** this issue on Mac OS X 10.12 using latest Nightly 52.0a1 with Min-Vid v0.3.0.

**Comment by meandavejustice** [comment]
closing stale issue

**Comment by Softvision-VladBacia** [comment]
reopening due to #669

**Comment by meandavejustice** [comment]
@Softvision-VladBacia Can we not just leave #669 open and close this issue? I'm trying to get rid of dupes

**Comment by Softvision-VladBacia** [comment]
Closing this as dupe of #619 and #669 . Thank you.
