### ISSUE TITLE
all minvid area should be draggable

### ISSUE THREAD

**Issue by asurkov** [meandavejustice/min-vid#371]
I shouldn't be forced to look for a small '+' to move the window, instead a video area (at least that part that doens't have control should be draggble). In other words: click - stop/start video, drag - move the window (no pause)

**Comment by meandavejustice** [comment]
I agree having the whole video be draggable would be optimal. We had to go with the drag button because of limitations with the sdk <panel> api. After converting to a window in #340, we may be able to switch back to the behavior you're describing.

**Comment by Dapid** [comment]
Alt + drag works, at least on LXDE/Openbox. I cannot see the "+", though, is it perhaps a bug?

**Comment by Jubin01** [comment]
Alt + drag works for me too. But, I can't see the +. I'm on Ubuntu 14.

**Comment by vickychijwani** [comment]
I think the missing + icon is intentional - apparently they couldn't support dragging officially (see #375), but it works with the default desktop env shortcut.

**Comment by meandavejustice** [comment]
little update to this came in #475 the whole controls header bar is now draggable, when mousing over, you should see the cursor change to the grabbing icon.

**Comment by 6a68** [comment]
If we make the whole window draggable, clicks aren't sent through to the video--which means you can no longer click to dismiss ads shown on top of the video. I think the draggable controls bar is probably as good as it's going to get; closing.
