### ISSUE TITLE
double click should bring minvide to fullscreen

### ISSUE THREAD

**Issue by asurkov** [meandavejustice/min-vid#372]
that'd be a handy feature to bring a video to fullscreen, when you are interested in the video for a short period, double click again to minimaze. It'd be also nice to have a 'fullscreen mode' button too.

**Comment by meandavejustice** [comment]
We have the `send-to-tab` button for now , which allows you to send back to the original page and fullscreen from there. We may add a fullscreen option down the road after we convert to a using a window #340
