### ISSUE TITLE
[Feature] Can it be made available even though I minimize firefox?

### ISSUE THREAD

**Issue by anshulguleria** [meandavejustice/min-vid#373]
For chrome I use `Floating for Youtube` for this kind of feature but in firefox when I minimize it also gets minimized. Can it be made available irrespective of firefox window position and state?

**Comment by meandavejustice** [comment]
@anshulguleria You are asking for the min vid window to be minimized when firefox is?

**Comment by GeraldNDA** [comment]
I'm assuming @anshulguleria means that minVid doesn't minimize even if firefox is minimized. Currently you can alt-tab but if firefox is minimized, minVid closes.

**Comment by anshulguleria** [comment]
@GeraldNDA Yups you are right. I wanted it to persist on top even if I minimizes firefox like it happens with `Floating for Youtube` plugin in chrome.

**Comment by meandavejustice** [comment]
fixed in #475
