### ISSUE TITLE
Can't drag MinVid in Arch Linux

### ISSUE THREAD

**Issue by jorgesca** [meandavejustice/min-vid#375]
I can't seem to move minvid's window. There is no control button dedicated to this and dragging doesn't work
Firefox 49.0.1
Linux 4.7.5-1-ARCH #1 SMP PREEMPT Sat Sep 24 13:04:22 CEST 2016 x86_64 GNU/Linux
8 GB RAM

**Comment by Slomo17** [comment]
Same here on Arch Linux

**Comment by meandavejustice** [comment]
Dragging in Linux is currently not supported. This will probably be addressed when we move to a window instead of an sdk <panel>. You can track that bug here #340

**Comment by vickychijwani** [comment]
@jorgesca @Slomo17 try Alt + mouse drag - it works in MATE desktop environment (that's the default shortcut for dragging windows on MATE). Your desktop environment may have a different shortcut.

**Comment by jorgesca** [comment]
Doesn't seem to work on gnome. I can't find a "drag window" shortcut. Thanks for the suggestion anyway

**Comment by jorgesca** [comment]
I did search a bit more and found it! In Gnome <super> + click will drag a window, and this works also for minvid's window as suggested by @vickychijwani . Thanks!
