### ISSUE TITLE
We should have a consistent behavior in how Min Vid player controls should or should not affect the browser window

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#376]
[Notes]:
- Currently some of the player controls affect browser window focus while it is hidden behind other windows. Volume bar and Drag handle can be actioned upon and the browser remains hidden in the background. However, if any of the other controls (Play/Pause/Volume icon/Minimize/Maximize/Close/Progress bar) are clicked the browser is brought into foreground, on top of all other windows.
- In my opinion we should have some consistency here. Either all the player buttons should affect the browser window focus or none of them.
- On Mac OS it's a bit different because if you have 2 other windows on top of the browser, only one of the windows will be sent into background, but the browser becomes the active window.

[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.3.0-dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.3.0-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to a website with videos supported by Min-Vid player (eg: YouTube, Vimeo, etc).
3. Send a video to the mini player and choose to play it.
4. Focus a different application/window so that the browser is in background.
5. Pause the mini player and observe the browser behaviour.

[Expected result]:
- The browser stays in background.

[Actual result]:
- The browser is brought into foreground.

[Additional Notes]:
- Attached a screen recording of the issue https://goo.gl/hgOAMv.

**Comment by 6a68** [comment]
I bet this is fixed or improved by #475

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest build (0.3.3).

**Comment by SoftVision-CiprianMuresan** [comment]
Closing this because the player controls no longer affect the browser window focus.
