### ISSUE TITLE
Unable to play certain "protected" videos (Vevo)

### ISSUE THREAD

**Issue by Coder206** [meandavejustice/min-vid#377]
While using min-vid in FireFox 49.0.1 I (and a few others) noticed that videos that are from YouTube Vevo channels and some from certain other places just throw an error like #342's. It appears as though there is some sort of protection against using them. I already reported this for Activity Stream (https://github.com/mozilla/activity-stream/issues/1079). 

I noticed that Polymer App.Route seems to be able to circumvent this: https://elements.polymer-project.org/elements/app-route?view=demo:demo/index.html&active=app-route

**Comment by meandavejustice** [comment]
@Coder206 the polymer-project doesn't seem to be using the iframe embed api, we need to use this currently until #331 is complete in order to follow YouTube's terms of service. Polymer is a google project, so they can do special things with YouTube.

**Comment by Coder206** [comment]
@meandavejustice  Thanks for the insight, in favor of #331, I am closing this.
