### ISSUE TITLE
Unable to play live videos

### ISSUE THREAD

**Issue by gamaroot** [meandavejustice/min-vid#378]
![screenshot](https://cloud.githubusercontent.com/assets/1787179/19020866/caac8094-888a-11e6-940c-700a300a93ab.PNG)

**Comment by GeraldNDA** [comment]
I think this also applies to videos after they are live as well ...

**Comment by SoftVision-CiprianMuresan** [comment]
@gamaroot, thank you very much for reporting this to us.

Unfortunately this issue is a dupe of #341.
