### ISSUE TITLE
Popups makes Min-Vid disappear

### ISSUE THREAD

**Issue by rugk** [meandavejustice/min-vid#380]
STR:
1. Play video in Min-Vid.
2. Use the other testpilot experiment Page Shot to create a screenshot.
2. (optional, not tested without this step) Make page shot showing an error. (it always does in my case)

What happens: The page shot error popup makes the min vid video go away. Audio keeps playing.

What should happen: Do not hide the min vid video window.

**Comment by pdehaan** [comment]
Related: #347

Oddly, when I tested w/ Page Shot, it _wasn't_ closing the Min Vid player (see https://github.com/meandavejustice/min-vid/issues/347#issuecomment-250317019). But I don't think I was getting any Page Shot errors, so maybe it's specific to that flow.

@rugk What version of Firefox are you using, and what OS are you on?

Also, would you mind filing an issue in the Page Shot repo (https://github.com/mozilla-services/pageshot/issues) with the error that you're seeing and your system details and we can investigate.

Thanks

**Comment by Moh-Said** [comment]
For me Min-Vid is hidden (but continue to play) when : 
- the Test Pilot add-on icon is clicked on the toolbar, and showing the pop-up.
- uBlock is clicked and showing pop-up.
- Other add-ons pop-ups.

Thank you.

**Comment by rugk** [comment]
Firefox 49.0.1
Linux x64

**Comment by zer09** [comment]
Same here Min-Vid will close but the audio is still playing if I click the test pilot icon and pops-up.
Firefox 49.0.1
Window 7 x64

thanks

**Comment by SoftVision-CiprianMuresan** [comment]
I was able to reproduce the issue with the Page Shot overlay but only if an error appears, a simple way to do this is to make a shot of a saved shot (this will always result in an error).
I was also able to reproduce this with the Gecko Profiler doorhanger and with the Test Pilot one both on Firefox release, using the released version of Test Pilot and on the latest Nightly using the latest Min-Vid addon on Windows 10 x64.
@meandavejustice said this will be solved once #340 is fixed.

**Comment by lasr21** [comment]
Hello, I reproduce it  while open the add on last pass menu

Firefox 50.0b5
Mac OS 10.11.6

**Comment by yfdyh000** [comment]
Test Pilot toolbar button's popup make this issue too.

**Comment by meandavejustice** [comment]
fixed in #475

**Comment by Softvision-VladBacia** [comment]
This issue is no longer reproducible with the latest Min-Vid build v0.3.3-dev using latest Firefox release 50.0 and latest Nightly build (Build ID: 20161120030205).
