### ISSUE TITLE
Invalid video length

### ISSUE THREAD

**Issue by zer09** [meandavejustice/min-vid#382]
It is showing invalid video length on min-vid, it showing 23h+.
ff 49.0.1
Win 7 x64

thanks

**Comment by SoftVision-CiprianMuresan** [comment]
@zer09, are you watching a video shorter than 23h and it shows 23h+? Could you also post a link to the video in question?

**Comment by zer09** [comment]
@SoftVision-CiprianMuresan  yes, the video is short.
Youtube links:
- https://www.youtube.com/watch?v=ETzusMQBZIc
- https://www.youtube.com/watch?v=DyTA8nVSP4U

I also upload a print screen
![Uploading ps 1.png…]()
![Uploading ps 2.png…]()

**Comment by zer09** [comment]
@SoftVision-CiprianMuresan

**Comment by zer09** [comment]
@SoftVision-CiprianMuresan  yes, the video is short.
Youtube links:
- https://www.youtube.com/watch?v=ETzusMQBZIc
- https://www.youtube.com/watch?v=DyTA8nVSP4U

I also upload a print screen
![ps 1](https://cloud.githubusercontent.com/assets/780780/19071374/5bab5a88-8a62-11e6-8096-7831372c601d.png)
![ps 2](https://cloud.githubusercontent.com/assets/780780/19071375/5bb2b8e6-8a62-11e6-810f-fb800b70452b.png)

**Comment by SoftVision-CiprianMuresan** [comment]
@zer09, I was unable to reproduce your issue on the latest Firefox release with the addon installed from Test Pilot, nor the latest Nightly with the latest addon version.

**Comment by pdehaan** [comment]
I wasn't able to reproduce w/ Nightly and a clean-ish profile either.

<img width="347" alt="invalid_video_length_ _issue__382_ _meandavejustice_min-vid_ _github_and_invalid_video_length_ _issue__382_ _meandavejustice_min-vid" src="https://cloud.githubusercontent.com/assets/557895/19083910/0fb1ed98-8a19-11e6-8e0b-c02e22d4e735.png">

@zer09 Odd question, but where do you live and/or what is your time zone? I think we're using a `Date()` object to calculate durations, and I'm wondering if we're somehow overflowing that and the dates are just wrapping and may this is some odd daylight savings issue.

**Comment by zer09** [comment]
@pdehaan , @SoftVision-CiprianMuresan  issue persist even on clean profile and latest nightly build.
I tried changing to other different timezone and the issue is gone. but the issue will come back if I change it back only to UTC +8 Kuala Lumpur, Singapore.

**Comment by joaomsa** [comment]
To replicate you need to set your system's timezone to one that has daylight savings time active on January 1 and not active on the current date.

Like UTC -9:00 Alaska, UTC -7:00 Chihuahua, UTC -6 Easter Island, UTC -5 Chetumal, UTC -3 Brasilia, etc...
