### ISSUE TITLE
Breaks VimFx addon keyboard capture

### ISSUE THREAD

**Issue by joaomsa** [meandavejustice/min-vid#383]
Steps to reproduce:
Popout a video to min vid, and vimfx stops responding to all keyboard commands

Versions:
Firefox 49.0.1
With addons:
Min Vid 0.3.0
VimFx 0.20.0

**Comment by meandavejustice** [comment]
@joaomsa This may be fixed with the new windowing code that just got merged in #475, wanna give that a shot and see if you're still having the issue?

**Comment by joaomsa** [comment]
Thanks, resolved
