### ISSUE TITLE
Need to make the screen to be dragged and dropped

### ISSUE THREAD

**Issue by shashikumarraja** [meandavejustice/min-vid#386]
The most convenient way for any user to handle and popup like screen is if he/she can drag and drop it to any corner of the screen.Currently it is not allowed to do so.

**Comment by SoftVision-PaulOiegas** [comment]
Are you using Linux ? The functionality was temporarily disabled on it until we find a fix for some issues.
However, the drag functionality correctly works on Windows and Mac OS. if you hover the player, you'll see a cross type handle on the right side of volume. That allows you to drag it anywhere on the screen.

**Comment by shashikumarraja** [comment]
Yes, I am using Linux.
My testing environment is-
OS- Ubuntu 16.04 LTS
Browser- Firefox 49.0

**Comment by meandavejustice** [comment]
closing for #192
