### ISSUE TITLE
Min-Vid seek bar stops showing progress when fast-forwarding with keyboard for more than 5 seconds

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#387]
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.3.0-dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.3.0-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to YouTube.
3. Send a video to the mini player and choose to play it.
4. Hold the right arrow down for 5 seconds to fast forward the video.

[Expected result]:
- The seek bar and timestamp accurately display the progress of the video while fast forwarding.

[Actual result]:
- The seek bar and timestamp progress is updated only on key release.

[Additional Notes]:
- The issue is also reproducible when going fast backwards.
- This will affect users that are listening to / watching long videos with the mini player.
- Attached a screen recording of the issue https://goo.gl/9Hauah.

**Comment by meandavejustice** [comment]
no longer able to reproduce

**Comment by SoftVision-CiprianMuresan** [comment]
I am still able to reproduce the issue on longer videos (>10 mins). Tested on the latest Min-Vid version 0.3.3b built on 12/27/2016.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is still reproducible on the latest master, built on 4/11/2017. 

![timestamp update](https://cloud.githubusercontent.com/assets/18304511/24902171/01debdc6-1eb2-11e7-8987-834bd62122f0.gif)

Here is a screenshot of the browser console after I held the right key for a few seconds:

![image](https://cloud.githubusercontent.com/assets/18304511/24901349/8011fff8-1eaf-11e7-95e2-f7a33a82b0c8.png)

**Comment by SoftVision-CiprianMuresan** [comment]
This issue is no longer reproducible ever since #747 took out the YouTube part of keyboard navigation.
