### ISSUE TITLE
Min Vid closes itself.

### ISSUE THREAD

**Issue by Alpactus** [meandavejustice/min-vid#389]
When using Min Vid, the video randomly closes itself but keeps playing the audio with no way to reopen the video unless i create a new Min Vid video.

**Comment by freedompower** [comment]
I had this issue when I dragged the window out of my Firefox window.

**Comment by Softvision-VladBacia** [comment]
@Alpactus , thank you for reporting this.

Can you give us a little more info?
- Operating system
- Firefox version
- Link to video link (if u feel comfortable sharing)
- Any further steps to reproduce

**Comment by iliaskomp** [comment]
I also have this issue. Ubuntu Gnome 16.04, Firefox 49.

Steps to reproduce: 
1) Start playing any video in minivid. 
2) Click on an addon icon in Firefox bar (addons I reproduced the issue are Test Pilot, Video DownloadHelper and Mind The Time) 
3) Minivid doesn't show anymore but audio keeps playing.

**Comment by Softvision-VladBacia** [comment]
@iliaskomp, thank you very much for reporting this to us.

The issue that you describe is a dupe of #347.

**Comment by meandavejustice** [comment]
fixed in #475

**Comment by Softvision-VladBacia** [comment]
This issue is no longer reproducible with the latest Min-Vid build v0.3.3-dev using latest Firefox release 50.0 and latest Nightly build (Build ID: 20161120030205).
