### ISSUE TITLE
Fullscreen button

### ISSUE THREAD

**Issue by Aymkdn** [meandavejustice/min-vid#393]
Hi,

I'm on Windows 10 Anniversary Update, with Firefox 49.0.1 and MinVid 0.3.0.

I don't see a "Fullscreen" button that will permit to switch from the MinVid to the fullscreen in one click, without passing first by the Youtube website. Is it a missing feature?

The video is really small, and sometimes I just want to correctly watch a sequence of the playing video. Right now I have to send it back to Youtube website, and then click on FullScreen, and when the sequence is done I have to resend to MinVid.

Thanks

**Comment by Softvision-VladBacia** [comment]
@Aymkdn, thank you for reporting this.

For now we have the send-to-tab , which allows you to send back to the original page and fullscreen from there. A fullscreen option may be added down the road after convert to using a window #340
