### ISSUE TITLE
no-resource-uri-leak hides icon

### ISSUE THREAD

**Issue by rugk** [meandavejustice/min-vid#394]
When [this addon](https://addons.mozilla.org/de/firefox/addon/no-resource-uri-leak/) is installed it breaks the icon of Min-Vid. Instead of an icon in the top left of the video, just a black rectangle is shown.

Reported to other addon too: https://notabug.org/desktopd/no-resource-uri-leak/issues/7

**Comment by meandavejustice** [comment]
It seems that `no-resource-uri-leak` is doing exactly what it says it should. We are serving the min-vid icon from `resource://`. As far as I'm aware, serving icons from `resource://` seems to be the standard for add ons. Do you not see with with other addons?

**Comment by rugk** [comment]
Well... I've several other add-ons installed and they work.
But [I've asked](https://notabug.org/desktopd/no-resource-uri-leak/issues/7#issuecomment-2838) what could be a better way. I suggest you to follow the issue there.

**Comment by meandavejustice** [comment]
Seems as if this is going to continue to be blocked, explanation [here](https://notabug.org/desktopd/no-resource-uri-leak/issues/7#issuecomment-2839).
