### ISSUE TITLE
Changing the volume with keyboard shortcuts do not affect the volume slider and icon

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#397]
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.3.0-dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.3.0-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to YouTube and send a video to the mini player.
3. Choose to play it by clicking on the video area.
4. Hold the down arrow down for 5 seconds to mute the video.
5. Hover the "Volume" slider.

[Expected result]:
- The "Volume" slider is in the muted state.

[Actual result]:
- The "Volume" slider is at 50%, but no audio can be heard.

[Additional Notes]:
- Attached a screen recording of the issue https://goo.gl/a3jBVI.

**Comment by meandavejustice** [comment]
closing for #67

**Comment by SoftVision-CiprianMuresan** [comment]
#67 is now closed, but the scenario here is still reproducible on the latest master, built on 4/11/2017. 
If I click the drag-able part of Min-Vid and then I try to change the volume with Up/Down, the keys don't do anything. It's only when I click inside the player that the keys affect the volume. 
I think we're actually using the YouTube controls. 
The same goes for our mute/unmute key. If I click the drag part of the player and hit M the icon and volume are changed accordingly, but if I click inside and do the same thing the video is muted, but the icon is not updated.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest master, built on 5/5/2017.
