### ISSUE TITLE
Implement UI for basic controls

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#4]
* close
* mute
* play/pause
* send back to tab and bring into focus

**Comment by 6a68** [comment]
Oh yeah, 'send back to tab' is a great idea :+1:

**Comment by meandavejustice** [comment]
In progress, working branch here => https://github.com/meandavejustice/min-vid/compare/controls?

**Comment by johngruen** [comment]
@meandavejustice, rooting around the UX org for any existing ff-friendly video controls. @shorlander did these 3 years ago, but they're still pretty great looking.

http://people.mozilla.org/~shorlander/files/video-controls-i03/videoControls-i02.html

**Comment by johngruen** [comment]
Don't think that's exactly what you're looking for, but i bet these could be updated to meet your needs.
