### ISSUE TITLE
Unable to play a video on some youtube channel

### ISSUE THREAD

**Issue by zer09** [meandavejustice/min-vid#405]
I stumble upon on this video https://www.youtube.com/watch?v=n8ZRTJQAcjU and try to play it in min-vid but I got the "Something's gone wrong with this video, Try again later." But it is playing fine in a firefox tab. the same happen on all the video on that channel(Bloomberg).

**Comment by SoftVision-CiprianMuresan** [comment]
@zer09, thank you very much for reporting this to us.

Unfortunately this issue is a dupe of #331.
