### ISSUE TITLE
Video disappearing when I open my history.

### ISSUE THREAD

**Issue by Falcoholic** [meandavejustice/min-vid#406]
When I have a video playing, and I open my history bar, the video disappears. The audio plays on, but the video just vanishes, and I can't get it back. Hope this little issue report helps.

**Comment by Falcoholic** [comment]
Oops, this was reported before. How do you delete posts?

**Comment by SoftVision-CiprianMuresan** [comment]
@Falcoholic, thank you very much for reporting this to us.

Unfortunately this issue is a dupe of #380.
