### ISSUE TITLE
Opening a new tab causes floating youtube video to go background

### ISSUE THREAD

**Issue by prafullpd2** [meandavejustice/min-vid#416]
I opened a YouTube video in floating window of min-vid. when I tried to open a new tab, the floating video gone to background. It was unable to find it. Only audio was playing.

**Comment by Softvision-VladBacia** [comment]
Hey @prafullpd2  thanks for reporting this. Can you give me a little more info?

- Operating system
- Firefox version
- Link to video link (if u feel comfortable sharing)
- Any further steps to reproduce

**Comment by meandavejustice** [comment]
Closing after no response for over a month
