### ISSUE TITLE
Min-vid halts progress on Youtube playlists

### ISSUE THREAD

**Issue by indrekln** [meandavejustice/min-vid#417]
Unable to play a Youtube playlist with Min-vid. At the end of the video one needs to manually open the page, click next, click the Min-vid open again for new video.
This is a problem with a long list of 2-minute videos.

**Comment by vickychijwani** [comment]
One nice use-case this will enable is using Min Vid as a floating music player: I can pop-out the first video in my playlist and minimize the panel. That way I can easily play/pause music when a co-worker wants to discuss something, without switching to the tab and potentially displaying the distracting video for all to see. @meandavejustice your thoughts on this? I can try to tackle this if you think it's not a huge undertaking.

As a follow-on to this it would be great to also have previous/next controls for playlists.

**Comment by meandavejustice** [comment]
Playlist support is in the planning stages right now, we plan to support creating your own playlists with videos from multiple domains as well as youtube playlists. I'll be creating issues for this today, will link here when they are up.
