### ISSUE TITLE
Min-vid performance impact.

### ISSUE THREAD

**Issue by mhoye** [meandavejustice/min-vid#418]
I'm seeing a significant performance impact on the whole browser while minvid's installed. It's notably severe when Twitter or the Wordpress editor are open; about:performance reports CPU usage of 65% or more for min-vid, and browser interactions including typing or switching tabs frequently cause pinwheels lasting several seconds at a time. 

This occurs on both current nightly and current release, on OSX Sierra. I'm also using No More 404s, PageShot and Tracking Protection, as well as UBlock Origin, Imageblock and Tree Style Tabs.

**Comment by Softvision-VladBacia** [comment]
@mhoye thank you for reporting this. I've done a bit of testing on this issue and is happening also when browsing facebook. I've started playing a video from youtube in Min-Vid and opened another tab with a facebook profile and started scrolling through timeline. The video from Min-Vid player is jerky and my CPU usage rises to 40%-50% from 15%-20%. I have installed only Min-Vid add-on from Test Pilot. I've tried with UBlock Origin enabled and disabled but the outcome was the same.

I've tried also another scenario. I have about 15 tabs opened and the video played in Min-Vid is jerky also when switching between tabs.

**Comment by meandavejustice** [comment]
Thanks for reporting @mhoye. We are currently testing a branch switching the sdk <panel> to a window(#340). This should work more naturally while sitting on top of gpu heavy pages. As well as provide hardware acceleration  for playback when neccessary. We'll continue to test and update this bug to make sure we address this.

cc/ @6a68

**Comment by hmijail** [comment]
Similarly here: I have a ton of tabs open (though unloaded), no video played in this session as far as I can remember. About 50 extensions loaded, of which Min-vid has the worst performance impact according to about:performance. macos Sierra, Firefox 50.0b10.

**Comment by meandavejustice** [comment]
@mhoye @hmijail I believe we have found the issue here, it looks like it's an issue with how we've been reporting availability on certain pages. We hope to get this into the next release, you can track the bug here #494

**Comment by 6a68** [comment]
This should be fixed by #475, since we are now offloading video playback to the GPU
