### ISSUE TITLE
hide overlay icon in fullscreen mode

### ISSUE THREAD

**Issue by 6a68** [meandavejustice/min-vid#419]
Issue reported [on discourse](https://discourse.mozilla-community.org/t/how-can-we-make-min-vid-better/11136/5):

> I've got one thing I'd like to see changed, when viewing a video on YouTube in full-screen mode the Min Vid icon still appears (and remains during playback), I find this fairly annoying and I would like it to be hidden during full-screen playback.

**Comment by meandavejustice** [comment]
dupe of #185
