### ISSUE TITLE
gather all info for testpilot detail page

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#42]
- [ ] screenshots
- [ ] description
- [ ] developers
- [ ] contribute link
- [ ] issues link
- [ ] privacy policy
- [ ] metrics doc link
- [ ] deployment stragegy (xpi and update.rdf links) #13 
- [ ] decide on a name
- [ ] get logo from @jgruen
- [ ] gather resources for tour #43

**Comment by johngruen** [comment]
Hey @meandavejustice All this stuff should go in here: https://docs.google.com/spreadsheets/d/170wRKBJ6LV67wIwAm8flkyYaweYNejuuiZU6tENgbcg/edit?usp=sharing

**Comment by johngruen** [comment]
There's a "wave 2" tab with a Min Vid area

**Comment by meandavejustice** [comment]
How do I switch tabs?

**Comment by johngruen** [comment]
on the bottom

**Comment by meandavejustice** [comment]
oh duh, okay thanks
