### ISSUE TITLE
Show on mouse hover

### ISSUE THREAD

**Issue by davidhedlund** [meandavejustice/min-vid#423]
I would like to hide the min-vid's completely and show them on mouse hover. This way min-vid's won't interupt my browsing experience with a otherwise cluttered window.

**Comment by davidhedlund** [comment]
[mylabel:enhancement](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aenhancement%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by meandavejustice** [comment]
Hey @davidhedlund a fix for this actually _just_ landed today with help from a contributor. https://github.com/meandavejustice/min-vid/pull/420 We'll probably push an update either friday or monday.

**Comment by davidhedlund** [comment]
@meandavejustice Thank you.
