### ISSUE TITLE
Min-Vid player controls are not rendered in High Contrast mode (Windows theme)

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#425]
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid v0.3.1

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on version (0.3.1-dev) was previously installed on a clean profile.
- High Contrast theme is enabled from Windows settings.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to a website with videos supported by Min-Vid player (eg: YouTube, Vimeo, etc).
3. Send a video to the mini player and choose to play it.

[Expected result]:
- The player controls are rendered correctly.

[Actual result]:
- Only the drag handle icon is rendered.

[Additional Notes]:
- Attached a screenshot of the issue.
  ![min-vid player controls are not rendered](https://cloud.githubusercontent.com/assets/18304511/19394456/f2d91fe4-9241-11e6-8492-009211360ccf.png)

**Comment by 6a68** [comment]
This *may* be fixed by #475

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest build (0.3.3).

**Comment by SoftVision-CiprianMuresan** [comment]
Closing this because all the player controls are rendered correctly.
