### ISSUE TITLE
conflict with Stylish

### ISSUE THREAD

**Issue by wresuolc** [meandavejustice/min-vid#426]
from test pilot issue:

----------8<-----------cut and dump----------8<-----------
Conflict with Stylish directive:
audio, video { min-width: 380px; max-width: 100% !important; }
Some sites have media player with progress bar, so user can rewind the record forward/backward.
Some stupid sites have media player 3cm wide for 60 minutes record. E.g. radio stream record.
Therefore I really need that Stylish directive to make players' width a bit more reasonable.
So... Youtube player starts to shift video to the right, leaving black band at the left of the player. If I try to specify 800px of minimal width, almost entire video disappears below right edge. 380px is a minimal width Youtube can tolerate.
As a result I have:
mini-video of MinVid extension shifted right by black space.
My priority is Stylish, therefore I must renounce using MinVid.
Thank you!
----------8<-----------cut and dump----------8<-----------

**Comment by meandavejustice** [comment]
If I understand this correctly, our css conflicts with the custom css the user wrote. If this is the issue we can't support user written css
