### ISSUE TITLE
Minimized height in linux

### ISSUE THREAD

**Issue by ASCIIbreakdown** [meandavejustice/min-vid#427]
The height of the player when minimized appears to be shorter than the buttons.
![screenshot at 2016-10-14 20-35-29](https://cloud.githubusercontent.com/assets/17417793/19406107/1d3da4ba-924e-11e6-8692-298a8f3179f4.png)
If I replace `minimizedHeight: 40` with `minimizedHeight: 50`, it seems to look better.
![screenshot at 2016-10-14 20-34-35](https://cloud.githubusercontent.com/assets/17417793/19406117/42e0828c-924e-11e6-98f1-1a88992c13f2.png)
These screenshots seem to be consistent with those found in issue #286. I think it has to do with the small triangle found in the top left corner of the window, which I presume is included in the dimensions.
The current machine im using has Linux Mint 18 installed on it, but it appears to be the same across all linux boxes.

**Comment by meandavejustice** [comment]
Thanks for reporting @ASCIIbreakdown
