### ISSUE TITLE
no controls of MinVid playaer

### ISSUE THREAD

**Issue by valch85** [meandavejustice/min-vid#429]
Hello I can't see any control neither icon nor item in right-click menu on site by link https://goo.gl/rxYsSl 
screenshot:
![vvaui](https://cloud.githubusercontent.com/assets/1758849/19412377/74d1c0e2-931d-11e6-9176-3a2d3c1b38b4.png)

[Affected versions]:
- Firefox 49.0.1
- Min-Vid v0.3.1

[Affected Platforms]:
- macOS Sierra 10.12

**Comment by meandavejustice** [comment]
Min Vid is not currently supported on Flash players. Try YouTube and Vimeo videos for now. Wider support is planned.
