### ISSUE TITLE
Something's gone wrong with this video: Error: ytCtrl

### ISSUE THREAD

**Issue by kumar303** [meandavejustice/min-vid#433]
This reproduces it for me on Firefox Dev Edition 51.0a2 (2016-10-15) (64-bit), Mac OS X:
* Load this in a tab: https://www.youtube.com/watch?v=ZBSxtLCMKKw&t=0
* Click the min-vid icon to pop it into a mini player

The video pops out but says "Something's gone wrong with this video, Try again later." (see screenshot)

I see this error in the browser console:
````
min-vid:Error: ytCtrl:  Object { target: Object, data: 150 }  bundle.js:430
````

![screenshot 2016-10-17 10 00 10](https://cloud.githubusercontent.com/assets/55398/19443030/0dd9b22a-9451-11e6-92dc-2d95ee732b54.png)

**Comment by meandavejustice** [comment]
It appears that the uploader has not allowed embedding for this video

**Comment by vickychijwani** [comment]
@meandavejustice I'm able to embed [this video](https://www.youtube.com/watch?v=x4AaYr1t3TA&t=0), but min-vid can't play it (same error as OP). I don't see any errors in the console though. Can this be re-opened?

Video: https://www.youtube.com/watch?v=x4AaYr1t3TA&t=0
Embedded video: http://jsbin.com/vozomeheja/edit?html,output

**Comment by kumar303** [comment]
@meandavejustice if the video truly cannot be embedded, I would advise displaying an error message to prevent future bug reports :) At the very least, an informative log message in Browser Console would have explained the situation.

**Comment by dogancelik** [comment]
I have this error too:

```
min-vid:Error: ytCtrl:  Object { target: Object, data: 150 } (bundle.js:1)
```
