### ISSUE TITLE
Airmozilla video cannot be popped out

### ISSUE THREAD

**Issue by kumar303** [meandavejustice/min-vid#434]
If you go to https://air.mozilla.org/mozilla-weekly-project-meeting-20161017/ and hover over the video, there are no controls to pop it out into a new window.

I assume this type of video isn't supported yet? I didn't see any open issues (at a glance).

It would be really nice to get min-vid controls for the weekly Mozilla meetings. I always use an awkward new window in my second monitor which takes some fiddling to get right every time.

**Comment by meandavejustice** [comment]
closing for #331
