### ISSUE TITLE
Playlist UI

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#453]
For the initial version of the playlist feature we just need a really simple ui for creating/editing playlists, viewing watched/created playlists, and sharing.
### Creation/Editing
- Enter/edit name of playlist
- button to share playlist (more on this below)
- drag to reorder videos/audio in playlist
- created/modified date should be visible
- previews/thumbnails will be pulled from videos themselves when applicable
- default thumbnail for videos
- default thumbnail for audio
- should work offline
- ability to remove from playlist
- would be nice to be able to preview the playlist, or individual playlist from the editing/creation view
- Items should be able to be added to a playlist from the Min Vid player
- you should be able to create a new playlist from the Min Vid player (see YouTube/Spotify playlist creating in context menu
- Would be nice to have ability to add a video to playlist from the context menu while browsing (just as you can launch min vid this way)
### Watched/Created
- We should have a list of playlists recently watched and "your playlists"
- recently watched will include playlists that were shared with you and your own.
- playlists created by user in "recently watched' should have some sort of indication that it was your own
- YouTube/Vimeo playlists viewed in the player should also show up here, with indication that they are different
### Sharing
- Sharing should be a button that opens a dialog with a copy-able url
### In player
- next/prev buttons when viewing a playlist
- ability to add to existing or new playlist
- a playlist icon we can use here and in other screens

**Comment by meandavejustice** [comment]
cc/ @johngruen @6a68 for discussion.

**Comment by youwenliang** [comment]
Hi @meandavejustice,

I have a few questions about "recently watched" and "my playlists", how does Min Vid store the viewing history data for users? Would they expire? And how does sharing work? What happens when another user open the shared URL?

Thanks.

**Comment by meandavejustice** [comment]
@youwenliang 

> how does Min Vid store the viewing history data for users? Would they expire?

They will be stored locally in the user's browser. No server. It will act the same as browser history

> how does sharing work? What happens when another user open the shared URL?

All of the playlist data will be encoded in a url with a `min-vid://` protocol. When another min-vid user opens this url, they will be shown the playlist and be able to launch it into their browser.

**Comment by johngruen** [comment]
Hey, just my two cents... @youwenliang should explore a few variations of a possible playlist UI, possibly removing or adding different feature sets in different versions. The list @meandavejustice described above aren't necessarily hard requirements, so Mark, you can share them in the issue and all three of us can decide on the feature set we want to implement.

**Comment by youwenliang** [comment]
Hi @meandavejustice,

Just a quick question for you, when you said "We should have a list of playlists recently watched", does it include individual videos you watched but do not belong to any lists, like a watched history?

Thanks.

**Comment by meandavejustice** [comment]
@youwenliang We can include those as well

**Comment by youwenliang** [comment]
@meandavejustice @johngruen 
Here's the current design for queue & history with annotation: https://mozilla.invisionapp.com/share/2P9TVX2DV

Go to this link for the full mockup:
https://mozilla.invisionapp.com/share/B79TVXB6T

Feel free to comment on the mockups or discuss here.
Thanks!

**Comment by johngruen** [comment]
Thanks @youwenliang. @meandavejustice take a look at the UI proposal and let us know if you have questions. @youwenliang it looks like there may be some new icons in this proposal. can you make sure to throw svg assets in this issue?

**Comment by youwenliang** [comment]
@johngruen 
Will do. Fang will review the current proposal and prepare the icon svg files.

**Comment by youwenliang** [comment]
[Icon.zip](https://github.com/meandavejustice/min-vid/files/673681/Icon.zip)
@meandavejustice @johngruen 
Here are the icons from the current proposal. We can start from these and Fang will update the icons if needed.

**Comment by meandavejustice** [comment]
Thanks @youwenliang

**Comment by fangshih** [comment]
Updated the icon set, here are the final icons 
[Icon Assets.zip](https://github.com/meandavejustice/min-vid/files/681932/Icon.Assets.zip)

- Add icon
- Close Menu
- Open Menu
- Next Video
- Prev Video
- Repeat song icon
- Drag list item icon

Thanks!

**Comment by youwenliang** [comment]
@meandavejustice 

By the way, here's the visual measurement from Fang:
https://mozilla.invisionapp.com/share/MW9ZGBL5U
And the icon assets is in the above comment.

Let me know if you have any questions!

**Comment by meandavejustice** [comment]
I'm pretty happy with this UI other than two little things:

I'd like to have the playlist popout actually overlay the minvid player

![playlist-my-update](https://cloud.githubusercontent.com/assets/1844554/21860124/42801c86-d7fd-11e6-91cc-d85d60330deb.png)

I'd also like to maintain a similar height with the current minimized view. The new ui proposed actually doubles the height.

![minimized-new-ui](https://cloud.githubusercontent.com/assets/1844554/21859866/5398a25a-d7fc-11e6-9dac-75ece891c3ac.png)

**Comment by youwenliang** [comment]
Hi @meandavejustice 

Can I ask why using overlay playlist instead of expanding outside the view? Are there going to be Implementation problems? One of the reasons we decided to use expanding panel is to let users be able to view the contents while checking the playlist.

Thanks.

**Comment by meandavejustice** [comment]
@youwenliang it will greatly simplify the implementation to have the overlay instead of the expanding view. Since min-vid is an experiment we wanna be able to get the idea out quickly, and this method will allow us to move faster.

The minimized view doesn't have any limitations, just making a suggestion

**Comment by youwenliang** [comment]
@meandavejustice 
Thanks for the clarification, we will work on the overlay version soon. Ideally we still want to see the expanded view version, we can discuss that after our first implementation.

**Comment by youwenliang** [comment]
@meandavejustice 

Here's a new proposal for the overlay version:
![005v](https://cloud.githubusercontent.com/assets/8919308/21976416/ab0e5c28-dc0c-11e6-9c13-4b7a5c8a0ab3.png)

You can check out the visual details here:
https://mozilla.invisionapp.com/share/Q5A1JD4RX

As for the menu behaviors, check out this video:
![ezgif com-crop](https://cloud.githubusercontent.com/assets/8919308/21976662/dbaa3126-dc0d-11e6-8b9c-09f931d7c4fe.gif)

1. Users can click Open_menu icon to display the overlay panel, and click Close_menu icon to dismiss.
2. If users left the frame while the menu is opened, it will stayed opened.
3. Users can also click out side of the panel to dismiss the overlay panel.

Let me know if you have any questions!
Thanks.

**Comment by meandavejustice** [comment]
@youwenliang Been working on this today, first off I wanna say I really love the way this turned out. Thanks for your work. This is a great UX

I've realized one option we may want to add is the ability to add a song to the queue(back of queue) from the embedded overlay icon. I'm thinking we can just have a little plus sign icon `➕`  beside the existing overlay icon. What do you think about that?

**Comment by youwenliang** [comment]
@meandavejustice 

Do you mean something like this? (It could also be beside instead of below)
![image](https://cloud.githubusercontent.com/assets/8919308/23195997/acefc16a-f8f1-11e6-8d46-37c4cc9f61f0.png)
https://mozilla.invisionapp.com/share/CQAK74LFR

And for the screen you mentioned, it's a repeat icon so after the song ended it will jump back and play again until a user toggles off the repeat icon.

Thanks.

**Comment by meandavejustice** [comment]
@youwenliang This works great, thanks for the clarification on the repeat icon.

**Comment by meandavejustice** [comment]
@youwenliang Is there an icon for the drag handles in the queue list?

**Comment by youwenliang** [comment]
Yes, here:
﻿https://www.dropbox.com/s/ypxdh28hlwv3664/drag.svg?dl=0

thanks.
