### ISSUE TITLE
evaluate tooltip placement

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#461]
**[Affected versions]:**
-Firefox 45.0 and up
-Min-Vid v0.3.1

**[Affected Platforms]:**
-All Windows
-All Mac

**[Prerequisites]:**
-Latest Min-Vid add-on version (0.3.1-dev) was previously installed on a profile.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to a website with videos supported by Min-Vid player (eg: YouTube, Vimeo, etc).
3. Send a video to Min-Vid player.
4. Move the Mouse pointer over the "Minimize" button.
5. Click on Minimize button.
6. Move the mouse pointer over the "Minimize"or "Send to tab" buttons.

**[Expected result]:**
-The tooltip is clearly visible and the text is readable.

**[Actual result]:**
-"Drag" button is displayed on the tooltip, in foreground and not in background.

**[Additional Notes]:**
-Here is a screenshot of the issue.

![drag button is over the tooltip](https://cloud.githubusercontent.com/assets/9248513/19648584/2ffacb72-9a0b-11e6-908b-1983f663a0f1.jpg)

**Comment by flodolo** [comment]
Can I suggest to amend the title of this issue? It's not just the Drag button.
A quick-and-dirty fix would be to increment the opacity of the tooltip's background.

**Comment by Softvision-VladBacia** [comment]
The main issue is that the "Drag" handler is displayed on top of the tooltip, the other buttons are barely visible. The guys are working on #475 and in the window version of the Min-Vid, the "Drag"button has been removed. For the Min-Vid version from Test Pilot this issue is still reproducible.

**Comment by meandavejustice** [comment]
drag button removed in #475

**Comment by flodolo** [comment]
Passing by note: The issue is not only with the Drag Button, and other issues were duped against this.

**Comment by meandavejustice** [comment]
@flodolo updated the title and reopening, thanks for catching that
