### ISSUE TITLE
Tooltip is missing for "Drag" button 

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#462]
[Affected versions]:
-Firefox 45.0 and up
-Min-Vid v0.3.1

[Affected Platforms]:
-All Windows
-All Mac

[Prerequisites]:
-Latest Min-Vid add-on version (0.3.1-dev) was previously installed on a profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to a website with videos supported by Min-Vid player (eg: YouTube, Vimeo, etc).
3. Send a video to Min-Vid player.
4. Move the Mouse pointer over the "Drag" button.

[Expected result]:
-The tooltip for "Drag" button is clearly visible and the text is readable.

[Actual result]:
-Tooltip for "Drag" button is missing.

**Comment by meandavejustice** [comment]
drag button removed in #475
