### ISSUE TITLE
YouTube video only pauses and min-vid does not appear

### ISSUE THREAD

**Issue by rugk** [meandavejustice/min-vid#463]
Test video: https://www.youtube.com/watch?v=C0DPdy98e4c

What happens: Pauses on click, but does not show min vid window.

![youtubeminvidissue](https://cloud.githubusercontent.com/assets/11966684/19655891/dbbc7ae8-9a1d-11e6-91a1-de78ec91796a.gif)

Note that I could only reproduce this once in one browser session (with all YouTube videos, other platforms not tested). After a restart (I assume Firefox restart would have worked, but I had to do a device restart.) everything worked again.

Linux x64, Firefox 49.0.2 (Mozilla binaries)

**Comment by risoul** [comment]
Same here, same config.

**Comment by rugk** [comment]
Can you reproduce it?

**Comment by risoul** [comment]
Soory, can't reproduce, no more issue for me.

**Comment by meandavejustice** [comment]
Is this still a bug?

**Comment by 6a68** [comment]
Closing. If this bug is still occurring, feel free to reopen
