### ISSUE TITLE
Min-Vid 0.3.2 from Test Pilot is not working on latest Firefox release 49.0.2 

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#466]
**[Affected versions]:**
-Firefox User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
-Firefox Build ID: 20161019084923
-Min-Vid v0.3.2-release

**[Affected Platforms]:**
-Ubuntu 14.04 x64
-Windows 8.1 x64
-Mac OS X 10.11.6

**[Prerequisites]:**
-Latest release Min-Vid add-on version (0.3.2 - Test Pilot) was previously installed on a clean profile.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to a website with videos supported by Min-Vid player (eg: YouTube).
3. Send a video to Min-Vid player.

**[Expected result]:**
-Video is sent to Min-Vid player.

**[Actual result]:**
-`console.error: min-vid: Message: SyntaxError: missing = in const declaration...core.js:106` error is displayed in browser console.

**Comment by meandavejustice** [comment]
Just reproduced in FF49 on linux. Working on fixing this right now.

**Comment by meandavejustice** [comment]
Looks like this is our issue https://github.com/sindresorhus/map-obj/issues/5. Going to remove that dependency and create a fresh build, should fix us up.

**Comment by Softvision-VladBacia** [comment]
This issue was verified and is it no longer reproducible on latest Fx release v49.0.2 with Min-Vid add-on 0.3.3.
