### ISSUE TITLE
Videos occasionally get stuck in loading loop

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#468]
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/19701619/009bbda4-9ab1-11e6-89ff-445225940092.png)

I've been watching a few videos and they've worked fine, but every once and awhile I see this preloader appear and get stuck (and only animates the first bar, which is hard to see regularly since usually the videos load v. quickly for me).

![min-vid-stalling](https://cloud.githubusercontent.com/assets/557895/19701601/e98f3ece-9ab0-11e6-827d-ce2839a95003.gif)

![browser_console](https://cloud.githubusercontent.com/assets/557895/19701588/df488d80-9ab0-11e6-981c-e622ae0f45e2.png)

**Comment by pdehaan** [comment]
Oh, also worth noting is that this is totally random and non-reproducible. If I try the same video again, it works. So may be some timing issue or intermittent thing. But I've seen it about 3x in the past 20 minutes of spamming videos to the min vid player via reddit.com/r/videos

**Comment by Softvision-VladBacia** [comment]
@pdehaan , this issue seems to be related to #328. From what I can observe in the console log from the above issue, there are more errors than in #328 .
