### ISSUE TITLE
TypeError: window.YTPlayer.getCurrentTime is not a function

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#469]
Also noticed that occasionally videos play, but the current time does not update. 

![min-vid-getcurrenttime](https://cloud.githubusercontent.com/assets/557895/19702298/c899e11c-9ab3-11e6-8fdb-c2dd34e15594.gif)

![browser_console](https://cloud.githubusercontent.com/assets/557895/19702280/b32ee23c-9ab3-11e6-9fe9-131c5a2cc069.png)

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/19702311/dcff949e-9ab3-11e6-8c38-59920a6ff260.png)

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/19702303/d28e2f84-9ab3-11e6-9a72-f39dd0ff8868.png)

**Comment by pdehaan** [comment]
... curious.
I wonder if this is because I usually send videos to the mini player while I'm currently watching a video in a mini player. It usually unloads and loads the new video as expected, except when it doesn't.

Possibly some collision in `setTimeout()` or `setInterval()` where the current video is playing but then is unloaded and we're trying to call `window.YTPlayer.getCurrentTime()` or `window.YTPlayer.getDuration()` of a now unloaded video?

**Comment by meandavejustice** [comment]
I refactored a bunch of this stuff in my audio support branch. It still may be a while before that lands though, as we are going to wait until we can get soundcloud support working consistently. After next weeks release I may be able to pull out the fix from the audio branch and apply it to master
