### ISSUE TITLE
Add support for Vine

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#47]

**Comment by kaganjd** [comment]
Here's my [WIP branch for Vine support](https://github.com/kaganjd/min-vid/tree/47-vine)
Right now, the Vine context menu on Vine.co only works under these conditions:
- from a direct embed URL, like this: https://vine.co/v/i3ep956utHr, and 
- after sending YouTube link to Min-Vid first, which I think has to do with setting the control panel.

So I'll play with controls next.
<img width="804" alt="screen shot 2016-06-13 at 7 21 17 pm" src="https://cloud.githubusercontent.com/assets/9204835/16026610/b6940e7c-319d-11e6-8ff2-cb371a62abb4.png">

**Comment by meandavejustice** [comment]
Thanks @kaganjd, I'll be around in irc today, let me know if you need me to look at anything

**Comment by meandavejustice** [comment]
@kaganjd Now that the base-ui and controls are in master via #57 We should be able to finish getting this hooked up. Let's talk early next week get a plan together

**Comment by 6a68** [comment]
@kaganjd Hey, here's a function that gets the video and image URLs for a given vine.co URL. It uses a callback because we have to wait for the vine.co page to load before fishing out the data we need.


You could put this inside a separate lib or insert it inline in index.js. If you make it a separate lib, be sure that you `export` the getVineMP4 function. I left a stylistic TODO in there that can get addressed in the review. 

```js
var hiddenFrames = require('sdk/frame/hidden-frame');

// getVineMP4: Given a vine.co URL, returns URLs of the video and preview image.
//
// Takes two arguments: the vine.co URL and a callback.
// The callback will be passed two arguments: 
// the first argument is null or an error string,
// the second is an object of the form { url, image, video }, where
//   url is the vine.co URL that was passed to the function,
//   image is the vine CDN URL of the video's jpg preview image (or null), and
//   video is the vine CDN URL of the mp4 video (or null).
function getVineMP4(vineURL, cb) {
  const hiddenFrame = hiddenFrames.add(hiddenFrames.HiddenFrame({
    onReady: function() {
      this.element.contentWindow.location = vineURL;
      this.element.addEventListener('DOMContentLoaded', () => {
        const doc = this.element.contentDocument;

        const videoEl = doc.querySelector('meta[property="twitter:image:src"]');
        const videoURL = videoEl ? videoEl.content : null;

        const posterEl = doc.querySelector('meta[property="twitter:player:stream"]');
        const posterURL = posterEl ? posterEl.content : null;

        // TODO: do we want an Error instance here, or a node-style error string?
        cb(videoURL ? null : 'url not found', { url: vineURL, poster: posterURL, video: videoURL });

        hiddenFrames.remove(hiddenFrame);
      }, true, true);
    }
  }));
}
```
