### ISSUE TITLE
min-vid doesn't trigger a history event

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#470]
Possibly related to (or dupe of) #117 

So I can see my recent activity where I installed the add-on (12:29pm -- see (1) below), and then when I went to reddit.com/r/videos (12:48pm -- see (2) below), and then looked through 3 pages of /r/videos (see (3a-c) below).

but nowhere in ActivityStream does it show me what videos I watched (apart from the 1 video I had to go to YouTube directly, because of Vevo licensing)

![new_tab](https://cloud.githubusercontent.com/assets/557895/19703349/5e36e856-9ab8-11e6-9bf0-54d79b263ede.png)

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/19703437/b0e1c3f0-9ab8-11e6-9506-2c40684b38d5.png)

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/19703417/9d22e286-9ab8-11e6-8a46-c662aa2e083c.png)

**Comment by meandavejustice** [comment]
dupe
