### ISSUE TITLE
Odd flow with copyright videos

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#471]
I tried watching https://www.youtube.com/watch?v=fYN14UfO-Uc&t=0 via https://reddit.com/r/videos and it brings up this view in Min Vid:

![licecap_v1_25__stopped__and_search_results](https://cloud.githubusercontent.com/assets/557895/19705111/99eb8922-9abf-11e6-9b80-53ca6eaab744.png)

Clicking "Open in new tab" opens a new tab (as expected) in my Firefox'en browser.
Clicking the Min Vid overlay on the video on the YouTube page tries to re-launch the min-vid player, which now says:

![licecap_v1_25__stopped__and_search_results](https://cloud.githubusercontent.com/assets/557895/19705257/5e3a491c-9ac0-11e6-9231-3ef912de1428.png)

Not sure if it'd be possible to use the second "play on youtube" screen the first time, rather than the error-looking "something's gone wrong".

---

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/19705318/b46a368a-9ac0-11e6-88a4-d9c411ca5713.png)

**Comment by meandavejustice** [comment]
I actually have min vid specially coded to not allow playback of macklemore videos
