### ISSUE TITLE
Timestamp and seekbar are not updated with the latest video progress if the "Confirm close" window is displayed

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#472]
**[Affected versions]:**
-Firefox 45.0 and up
-Min-Vid 0.3.3-dev

**[Affected Platforms]:**
-All Windows
-All Mac
-All Linux

**[Prerequisites]:**
-Latest Min-Vid add-on version (0.3.3-dev) was previously installed on a clean profile.
-In about:preferences when the browser starts, set any other option than "Show my windows and tabs from last time".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open multiple tabs.
3. Navigate to a website with videos supported by Min-Vid player (eg: YouTube, Vimeo, etc).
4. Send a video to Min-Vid player and play it.
5. Click on "Close" button for the browser window.
6. Move the mouse cursor over the Min-Vid player.

**[Expected result]:**
-The movie is playing, timestamp and seekbar are updated with the latest video progress.

**[Actual result]:**
-Timestamp and seekbar are not updated with the latest video progress.

**[Additional Notes]:**
-Timestamp and seekbar are not updated if the user fast forwards/fast backwards if the video is playing and the "Confirm close" window is displayed. If the video is on pause,  the timestamp and seekbar are updated.
-[Here](https://drive.google.com/open?id=0B6QogV2AJFKieldHSndpa0NMSm8) is a screen recording of the issue.

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible on the latest Min Vid version built on 4/11/2017.
