### ISSUE TITLE
Volume level is not updated in the source video if previously a video has been sent to a tab from Min-Vid

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#474]
[Affected versions]:
-Firefox 45.0 and up
-Min-Vid 0.3.3-dev

[Affected Platforms]:
-All Windows
-All Mac
-All Linux

[Prerequisites]:
-Latest Min-Vid add-on version (0.3.3-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to a website with videos supported by Min-Vid player (eg: YouTube, Vimeo, etc).
3. Send a video to Min-Vid player and play it.
4. Change the volume level in Min-Vid player so it's different from the source.
5. Click on "Send to tab button" from Min-Vid player.
6. Observe the volume level.

[Expected result]:
-The volume level from the source video is changed so it reflects the level set in Min-Vid player.

[Actual result]:
-The volume remains unchanged after the video was set to tab.

**Comment by meandavejustice** [comment]
Unfortunately there is no url param to set volume for youtube watch pages. :(
closing as wontfix
