### ISSUE TITLE
Browser window is forced to be "Always on top"

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#476]
**[Affected versions]:**
-Firefox Nightly 52.0a1 x64, Build ID: 20161102030205
-Min-Vid commit-91e8504

**[Affected Platforms]:**
-All Windows

**[Prerequisites]:**
- Min-Vid add-on version (0.3.1-dev_commit-91e8504) was previously installed on a clean profile.
- Open multiple folders on the desktop that has the browser window with Min-Vid add-on installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to a website with videos supported by Min-Vid player (eg: YouTube)
3. Send a video to Min-Vid player.
4. Click on the one of the folder window opened.
5. Click on the browser window.
6. Repet steps 4 and 5.

**[Expected result]:**
-The selected window is on top of the others.

**[Actual result]:**
-Browser window remains on top of other folder window opened.

**[Notes]:**
-As a side note, I am using a desktop configuration with 2 monitors.
-[Here](https://drive.google.com/open?id=0B6QogV2AJFKiTzZVN2xVYi1NSzg) is a video of the issue.
-If the browser window is minimized and restored while there are other folder window opened on desktop, then the folder window remains on top of the browser window.
-To escape the "Always on top" state, the browser must be restarted.

**Comment by Softvision-VladBacia** [comment]
related with #475

**Comment by 6a68** [comment]
Thanks, @Softvision-VladBacia! I wasn't seeing this on Windows 10 in vmware. I'll try to repro on a real windows laptop.

**Comment by 6a68** [comment]
Hmm. I can repro this on windows 10.

I tried changing the [hWndInsertAfter](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633545(v=vs.85).aspx) value from `HWND_TOPMOST` to `HWND_TOP`, but that introduces other weird behavior: depending on the order of focus transfer between Firefox and other applications, sometimes the other Firefox windows can _never_ become topmost, even when activated:

1. open firefox and a file explorer window
2. open a minvid window from firefox
3. click the title bar of the file explorer window, bringing it to the top of the z order
4. click on the title bar of the firefox window (not the minvid window)

expected - firefox window is moved above file explorer window in the z order when activated
actual - firefox window is activated, but stays underneath the file explorer window

@Noitidart Hey, any idea why [setting windows topmost](https://github.com/6a68/min-vid/blob/window-player-updated/lib/topify.js#L59) isn't working quite right? HWND_TOPMOST creates the bug mentioned in the description, while moving to HWND_TOP creates another weird bug (described above in this comment).

**Comment by Noitidart** [comment]
I'll take a crack at this :)

**Comment by Noitidart** [comment]
@6a68 please see the PR it's fixed. That `alwaysRaised` flag is a doozey.

After initial `let win = window.open/Services.ww.openWindow`, fine tune control on windows is best done with ctypes alone or XPCOM alone. Mixing them causes weird behavior, for example in my [NativeShot](https://addons.mozilla.org/en-US/firefox/addon/nativeshot/) project after/before setting window on top I would make the window full screen with `win.fullScreen = true`, on Windows this caused funkiness, and on some linux distros it straight up crashed.

**Comment by Noitidart** [comment]
Also dragging is funky on Win10 - https://www.youtube.com/watch?v=w1XqJRX0hfE

**Comment by Noitidart** [comment]
@Softvision-VladBacia may you please test commit - b67706a325ec6f536dc087741f9b6859dcbb2a56

**Comment by 6a68** [comment]
@Softvision-VladBacia I think this bug is fixed in my branch. I've uploaded a fresh xpi. You can download it from the first link on my people page: https://people-mozilla.org/~jhirsch/min-vid-addon/

**Comment by Softvision-VladBacia** [comment]
@6a68 , I've tried to install the xpi on latest Nightly but this error message is displayed: `Forbidden, You don't have permission to access /~jhirsch/min-vid-addon/min-vid--branch-6a68-window-player-updated--commit-b67706a.xpi on this server.` 
Also, I've downloaded the .xpi file with Save link As... but it is corrupt and cannot be installed.

**Comment by Softvision-VladBacia** [comment]
@6a68 , I've rebuild the xpi from your branch and I could install it.

**Comment by Softvision-VladBacia** [comment]
I have verified the fix on Ubuntu 14.04, Windows 8.1 x64 and Mac OS X 10.9 with latest Nightly (Build ID: 20161108030212) and the issue is no longer reproducible.

I think that we should leave this issue opened until all PRs are merged into master.

**Comment by Noitidart** [comment]
Awesome! Thanks for discovering and getting us to the finish line with it!

**Comment by 6a68** [comment]
@Softvision-VladBacia The PR just landed in master, closing. Let's reopen if you can repro the issue :tada:
