### ISSUE TITLE
Add Noitidart to contributors on experiment page

### ISSUE THREAD

**Issue by 6a68** [meandavejustice/min-vid#479]
Let's add @Noitidart to the list of contributors on the min vid test pilot page, to reflect all his help with the js-ctypes windowing code.

@Noitidart, what name and avatar would you like us to use for your entry? See the existing page for examples: https://testpilot.firefox.com/experiments/min-vid.

**Comment by Noitidart** [comment]
Thanks!! May we please use my caricature - http://noitidart.github.io/img/avatar.jpg
And name Noitidart

**Comment by meandavejustice** [comment]
closing for https://github.com/mozilla/testpilot/issues/1842

**Comment by meandavejustice** [comment]
pr open at https://github.com/mozilla/testpilot/pull/1843
