### ISSUE TITLE
Implement metrics pings

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#48]
- [ ] `available` ping (logged when user visits a whitelisted domain, where we may prompt the user
- [ ] `activate` ping
- [ ] `deactivate` ping
- [ ] controls pings, `play`, `pause`, `volume`, `send-to-tab`, `minimize`, `maximize`, `close`
- [ ] settings pings `resize` and `move` pings
- [ ] video ended without user interaction `end` ping

**Comment by meandavejustice** [comment]
I think there are a couple more stats which may be interesting to add to the metric payload:
``` json
"video-stats": {
  "progress": "43%",
  "duration": "4:56",
  "muted": false,
  "minimized": true
}
```
if vine
```json
"video-stats": {
 "loop-count": 4
}
```

**Comment by 6a68** [comment]
@meandavejustice For the very first version, what if we simplify things a bit? Maybe we could just track the number of video plays, and use that to build a MAU / DAU number. We could add extra instrumentation if we have time, but I think we could probably ship without all the ping subtypes.

What do you think?

**Comment by 6a68** [comment]
on button click / special event (like opening player or loading a video), send over the event type and the AppData state bundle
