### ISSUE TITLE
Mac: Set collection behavior to join all spaces

### ISSUE THREAD

**Issue by Noitidart** [meandavejustice/min-vid#480]
@6a68,
We may want this behavior, I'm not sure - On mac, pop open a minvid window, then make any window full screen or change work space with Cmd + Lt/Rt Arrow. The video is no longer on "screen". I need a mac expert for code review, but this works for me - https://gist.github.com/Noitidart/80d00ae9147f1ab917099d43fbb012e9

Here is the critical part of the gist above:

```

  var collectionBehavior = sel_registerName('collectionBehavior');
  var behavior = objc_msgSend(winptr, collectionBehavior);
  behavior = ctypes.cast(behavior, ctypes.int).value;

  console.log('behavior:', behavior.toString());
  behavior |= NSWindowCollectionBehaviorCanJoinAllSpaces;
  console.log('behavior:', behavior.toString());
  
  var setCollectionBehavior = sel_registerName('setCollectionBehavior:');
  var rez = objc_msgSend(winptr, setCollectionBehavior, ctypes.unsigned_long(behavior));
  console.log('rez:', rez.toString());
```

It is upside down during the slide animation between spaces, but it fixes up. Maybe @mstange would have input on this.

Here is screencast of how a window stays on top with this method: https://www.youtube.com/watch?v=sqrQV5WZkHk

**Comment by 6a68** [comment]
@Noitidart Hey, thanks for filing this bug. Sorry I didn't notice it sooner.

I'd prefer to keep the OS-specific customizations to the minimum required for the basic functionality to work. If power users get into weird states while jumping between workspaces, they should generally know enough to get back out of those weird states--even if it requires a browser restart. Closing.

**Comment by Noitidart** [comment]
No problem. Makes sense :)
