### ISSUE TITLE
Min Vid might be making Nightly run slowly

### ISSUE THREAD

**Issue by jrmuizel** [meandavejustice/min-vid#481]
I get a bunch of these messages when running with Min Vid enabled.

**Comment by meandavejustice** [comment]
@jrmuizel it looks like you forgot to add the messages

**Comment by Softvision-VladBacia** [comment]
@meandavejustice , I think the reporter was referring to the message from title: `Min Vid might be making Nightly run slowly` .

**Comment by meandavejustice** [comment]
Ahh okay, thanks @Softvision-VladBacia

**Comment by jrmuizel** [comment]
Yep. The I'm referring to the bar that comes up at the bottom of the browser to complain about slow addons.

**Comment by meandavejustice** [comment]
This may be fixed with the new windowing changes

**Comment by 6a68** [comment]
refs #475
