### ISSUE TITLE
Why it's limited to 2 video player only?

### ISSUE THREAD

**Issue by rhazor** [meandavejustice/min-vid#484]
Why can't it open any website on the floating panel, no matter if it has video player in it? I'm stuck looking for alternative to Chrome Panels that opens any page on floating panel, but all Firefox addons are locked to YouTube. What a bummer.

**Comment by Softvision-VladBacia** [comment]
@rhazor , thank you for reporting this. 

#6 and #331 are handling this case. Feel free to provide video domains, for which you want support.

**Comment by rhazor** [comment]
I found a solution https://addons.mozilla.org/en-US/firefox/addon/all-in-one-sidebar/ it provides an icon that opens current page on sidebar.
