### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by Noitidart** [meandavejustice/min-vid#487]
From Android API 22+ we can create an overlay/panel/view (view is androids term for panel) that stays on top no matter what app is currently active. Using JNI.jsm - https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/JNI.jsm - we can bring the same affect seen here - https://github.com/meandavejustice/min-vid/pull/475

We have a huge mobile team (with Android API experts), is it possible we can request that they show us java code on how to ** **dynamically** ** create a view and load an iframe in it. I can then port it to JNI.

This is my work so far, it creates an overlay but I don't think it's the right approach:

```
	var aContext = GeckoAppShell.getContext();
	var wm = aContext.getSystemService(Context.WINDOW_SERVICE);
	wm = JNI.classes.android.view.WindowManager.__cast__(wm);
	
	// var inflater = aContext.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
	// inflater = JNI.classes.android.view.LayoutInflater.__cast__(inflater);
	// inflater.inflate(R_layout.my_view, null);
	var myView = View.new(aContext);
	
	var params = WindowManager_LayoutParams.new(
		WindowManager_LayoutParams.MATCH_PARENT,
		WindowManager_LayoutParams.MATCH_PARENT,
		WindowManager_LayoutParams.TYPE_SYSTEM_ALERT,
		WindowManager_LayoutParams.FLAG_NOT_FOCUSABLE,
		PixelFormat.TRANSLUCENT
	);
	
	params.x = 0;
	params.y = 0;
	
	wm.addView(myView, params);
	console.log('will block/make fx unresponsive until `wm.removeView(myView)` is done');

	setTimeout(function() {
		wm.removeView(myView);
		console.log('view removed');
	}, 5000);

```

**Comment by 6a68** [comment]
Hey, thanks for filing. Test Pilot isn't currently supported on mobile OSes, so I'm not sure users would even be able to download the experiment. This might be changing in 2017, but it's not yet clear just when.

I'll ask around and see if this would be worth exploring, but most likely won't go anywhere during min vid's time in test pilot.

**Comment by Noitidart** [comment]
> I'll ask around and see if this would be worth exploring, but most likely won't go anywhere during min vid's time in test pilot.

Thanks for asking even if chances are low! I make all my personal addons compatible with Firefox for Android. I can provide PRs for it very easily. :)

**Comment by 6a68** [comment]
> I can provide PRs for it very easily. :)

@Noitidart :+1: It's hard to argue with working code. Feel free to open a PR, probably good to wait till the window branch lands (hopefully this week).

**Comment by 6a68** [comment]
OK, window branch landed, feel free to crank out a PR :-) @meandavejustice is working on a huge refactor to bring in audio support, but I'm thinking most of the android code will be Gecko stuff, so it probably won't matter too much.

**Comment by Noitidart** [comment]
Wow super cool news!!

I actually am not an expert on Android API, I'm just good at porting it to JNI. I can do research and dev but that takes time (the code above is what I came up with). Do we have any Android API experts that can show me how to create a view with an iframe in it? (Then I can port that to JNI and we can set the src of the iframe to our minvid page.)

**Comment by johngruen** [comment]
@Noitidart closing this as out of scope for this project.
