### ISSUE TITLE
Window flickering while moved

### ISSUE THREAD

**Issue by smartynko** [meandavejustice/min-vid#492]
I just want to report this odd bug. When I tried to move the window from left to the right side of the screen it flickered a lot. Just tried this extension. Good luck with development.

**Comment by 6a68** [comment]
refs #475

**Comment by chutten** [comment]
@smartynko Would you happen to have a mixed dpi setup? I have the same problem on the hidpi screen (no such problem on the lodpi screen)

**Comment by meandavejustice** [comment]
@smartynko did you acquire the addon via testpilot or from this github repo?

**Comment by meandavejustice** [comment]
This issue seems to have gone stale, closing
