### ISSUE TITLE
Report available videos per-page instead of per-instance

### ISSUE THREAD

**Issue by wresuolc** [meandavejustice/min-vid#494]
Right now our stats are showing a huge number of available videos which aren't played.  We suspect this is because hitting up youtube.com has, like, 50 available videos on it and we get a ping for every one.  Instead of pinging per-available video, let's ping per page with at least one playable video on it.

Bonus points:  Can we send the number of available videos per page in  that single ping?

Edit:  Also, Sunah has asked that we have some kind of changelog for metrics changes, so, maybe a new section at the bottom of metrics.md tracking changes to the ping format.

/cc @johngruen

**Comment by meandavejustice** [comment]
@wresuolc The metrics changelog sounds like a good idea. We do currently have a changelog so make sure you point anyone to that for the time being.

I think the available videos count would be a nice addition to this. Should we send another ping on the infinite scroll events? Probably unneccessary

**Comment by wresuolc** [comment]
yeah, probably not necessary.

Sounds like she was actually talking about a central wiki page, so, let's figure that out next week.  Cheers!
