### ISSUE TITLE
Contact the activity-stream team about possible integrations with min-vid

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#5]
Would be really nice to be able to be closely integrated with `activity-stream` at some point.
Ideas for this include:
- launching min-vid from activity-stream
- adding an activity type that is "watched in min-vid"

**Comment by wresuolc** [comment]
@meandavejustice can you expand on this? :)

**Comment by meandavejustice** [comment]
Any integrations can/should be done once either experiment is actually a part of firefox
