### ISSUE TITLE
Make a test plan!

### ISSUE THREAD

**Issue by wresuolc** [meandavejustice/min-vid#50]
Let's make a test plan of the basic functionality so we know what to test with each new release.

We should have a changelog!

**Comment by pdehaan** [comment]
It looks like there is an acceptance criteria for the MVP at [/docs/acceptance-criteria.md](https://github.com/meandavejustice/min-vid/blob/master/docs/acceptance-criteria.md) which covers installing the add-on via Test Pilot and running through basic add-on functionality.

**Comment by wresuolc** [comment]
Ah yes, I remember.  I'm happy with that for the MVP if you are.  Thanks for writing it, Dave!

**Comment by meandavejustice** [comment]
@clouserw yeah I'm good with that, closing now
