### ISSUE TITLE
How can we differentiate the videos that can be played with Min-Vid player from those that cannot be played using a GET request?

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#505]
I have used below GET Request in order to obtain information related to the videos that I want to play in Min-Vid.

`https://www.googleapis.com/youtube/v3/videos?id=[video_ID]&key=[youtube_API_KEY]&part=snippet,contentDetails,status`

I took random videos that can be played and videos that cannot be played in Min-Vid player and compared the GET Request response.  From what I've seen, there are no differences between the information from the responses.

Below are 2 txt files, one with the GET Request response for a working video and one for a video that doesn't play.
[can be played.txt](https://github.com/meandavejustice/min-vid/files/604293/can.be.played.txt)
[doesn't play.txt](https://github.com/meandavejustice/min-vid/files/604295/doesn.t.play.txt)

How can we know if a video will play or doesn't play in Min-Vid player without sending the video to the player?

**Comment by meandavejustice** [comment]
@Softvision-VladBacia Thanks for doing this research, I also dug around for this a while back, it seems they've made it rather difficult to determine when using the embed player :(
