### ISSUE TITLE
Minvid placed over "tab center"

### ISSUE THREAD

**Issue by risoul** [meandavejustice/min-vid#506]
When using tab center experiment (tabs in a vertical right column), opening a minvid hide latest tabs. May be it would be good to move it at the right side of tab column.

**Comment by meandavejustice** [comment]
@risoul This is a good point, we need to test our interactions with tab center better

**Comment by 6a68** [comment]
This won't be an issue when we release the window-based player, because the window will be draggable on all platforms.

**Comment by meandavejustice** [comment]
fixed in #475
