### ISSUE TITLE
Minvid hide the page bottom when scrolling to bottom

### ISSUE THREAD

**Issue by risoul** [meandavejustice/min-vid#507]
Adding some blank space at the bottom of each page when minvid is active will allow to scroll more and make the bottom content appears above the minvid player, whitout the need of manualy moving it.

**Comment by meandavejustice** [comment]
We don't want to modify the appearance of each webpage. We've made min-vid draggable for this reason. We may experiment with make the ui more transparent down the road. Thank You :)
