### ISSUE TITLE
Make sure Min-Vid Test Pilot webpage is updated with latest changes

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#508]
Make sure the Min-Vid Test Pilot webpage is accurate for the next release. #475 changed a few things and maybe some screenshots and description are outdated.

**Comment by 6a68** [comment]
We also need to update the contributors list to include @Noitidart, who was very helpful in getting the ctypes code working

**Comment by meandavejustice** [comment]
@6a68 this landed a couple of days ago https://github.com/mozilla/testpilot/pull/1843

**Comment by meandavejustice** [comment]
fixed in https://github.com/mozilla/testpilot/commit/13f08363cd83c8e8fcbd7f39e82ffa831af7a388

**Comment by Softvision-VladBacia** [comment]
Test Pilot Min Vid page is not updated with latest changes in Min Vid functionality and screenshots are outdated.

**Comment by Softvision-VladBacia** [comment]
Min-Vid page from Test Pilot is not updated with latest changes. Screenshots used there are old and outdated.

![min-vid_changes](https://cloud.githubusercontent.com/assets/9248513/24754184/10a9b702-1ade-11e7-96e4-de945ab00a55.gif)
