### ISSUE TITLE
Make min-vid player scalable

### ISSUE THREAD

**Issue by Lurtzae** [meandavejustice/min-vid#513]
I'm using Firefox with a 1440p and 2160p monitor and the min-vid player is just too tiny with high resolution monitors to be of much help. 
It would be great if you could just scale the min-vid player by dragging its border and set the size manually.

**Comment by 6a68** [comment]
Thanks for filing! This is a dupe of #69, and we will eventually add resizing. Note that our upcoming release will make the player resizable, but only on linux (for now).
