### ISSUE TITLE
Set a fix resolution for min-vid

### ISSUE THREAD

**Issue by zer09** [meandavejustice/min-vid#514]
Just noticed that if your watching high res video on youtube and send it min-vid the quality is something like distorted. So what I am doing if I want to watch it in  min-vid, I set the youtube video res to lower before sending to min-vid. As I observe the sweet-spot is 360p. And also other benefit of this is it will consume much lower bandwidth. 

I uploaded images on google drive for comparison. Try to zoom and compare the text.
https://drive.google.com/open?id=0Bwnk4y2mEk0xNDVXTE5JR0p4Y1U

Thanks.

**Comment by 6a68** [comment]
This will be fixed by our next release, which moves the player to a hardware-accelerated window. Should be out really soon.

**Comment by meandavejustice** [comment]
fixed in #475
