### ISSUE TITLE
set env variables in a separate file

### ISSUE THREAD

**Issue by wresuolc** [meandavejustice/min-vid#515]
In the build script you're setting a couple of environment variables.  Instead of setting them directly, please write them to a `addon.env` file in the current working directory.  An example file:

> TESTPILOT_ADDON_ID="@min-vid"
> TESTPILOT_ADDON_VERSION="1.2"

**Comment by 6a68** [comment]
Would it make more sense to parse those values out of package.json or install.rdf?

**Comment by wresuolc** [comment]
Relud did end up doing that for package.json if these vars don't exist, but doing them for min vid would let us test the whole script, so I left this filed.
