### ISSUE TITLE
Right mouse click anywhre in the min-vid  portin should let changing position

### ISSUE THREAD

**Issue by mMARUF** [meandavejustice/min-vid#520]
Currently,when the video is playing through min-vid, there is a + sign , and if we right click on that sign and drag and drop, we can change the position of min-vid. It will a cool feature, if the user can change the position of video playing section by drag and drop with right anywhere in the min-vid video playing section. It was a popular demand,  when we arranged a "Firefox Test Pilot Sprint " among the audiences .

Attachment:  https://drive.google.com/open?id=0B75_JfziYeofOFZLZDJXc2gyWk0

**Comment by Softvision-VladBacia** [comment]
@mMARUF , thank you for reporting this. The drag button has been removed and other cool stuff was added when #475 landed. Now, the drag action can be done from the top part of the player window.

**Comment by meandavejustice** [comment]
We will continue to experiment with the best option for dragging/resizing and other actions. I don't see right click being one of these options for the future as it already is expected to launch a context menu.
