### ISSUE TITLE
Min-Vid icon and "Send to mini player" option are missing when the new YouTube layout is active

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#521]
**[Affected versions]:**
-Firefox 45.0 and up
-Min-Vid 0.3.3b

**[Affected Platforms]:**
-All Windows

**[Prerequisites]:**
-Latest Min-Vid add-on version (0.3.3b) was previously installed on a clean profile.
-YouTube new UI was activated for the testing profile. 

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to YouTube.
3. Hover the video thumbnail.
4. Right-click on the video thumbnail or video link.

**[Expected result]:**
3. The Min-Vid icon is displayed on the video thumbnail.
4. "Send to mini player" option is displayed din the context menu.

**[Actual result]:**
3. Min-Vid icon is missing from the video thumbnails.
4. "Send to mini player" is missing from the context menu.

**[Notes]:**
-[Here](https://drive.google.com/open?id=0B6QogV2AJFKiVlIyWmJGZG5sYXc) is a recording of the issue.
-Min-Vid button is displayed on the video thumbnail only after the user has clicked a video link  in order to view the video.

**Comment by meandavejustice** [comment]
@Softvision-VladBacia Hey vlad, how do I enable the new youtube layout for testing?

**Comment by SoftVision-PaulOiegas** [comment]
@meandavejustice this was possible a while back with cookie editing but it seams it's no longer working. What I managed to do is to get a random clean Firefox profile which was selected by YouTube to receive the new UI. Compressed it and managed to use it on others too for testing purpose.

Here is a [link ](https://drive.google.com/open?id=0B46G1GC59gyDdVpwU0dXb1dMREk)to the profile archive. Just create a new profile and after paste the archive content in the new profile folder. After that navigate to www.youtube.com and enjoy the new Material UI.

**Comment by Softvision-VladBacia** [comment]
This issue is still reproducible. Now, there is an easier way to access the new UI from YouTube (https://www.youtube.com/new)
