### ISSUE TITLE
Closed Captions/Subtitles are displayed in min-Vid player even if they are set to OFF on YouTube

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#522]
**[Affected versions]:**
-Firefox 45.0 and up
-Min-Vid 0.3.3b

**[Affected Platforms]:**
-All Windows

**[Prerequisites]:**
-Latest Min-Vid add-on version (0.3.3b) was previously installed on a clean profile.
-Need to have an YouTube video that has Closed Captions/Subtitles, not auto-translate. ( eg. https://www.youtube.com/watch?v=P3Ew8dCUonE )

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to YouTube.
3. Search for a video that has subtitles (eg. https://www.youtube.com/watch?v=P3Ew8dCUonE ).
4. Play the video on YouTube and set the Closed Captions/Subtitles to OFF.
5. Open the video in Min-Vid player.

**[Expected result]:**
- Closed Captions/Subtitles are OFF in Min-Vid player.

**[Actual result]:**
-  Closed Captions/Subtitles are displayed in Min-Vid player.

**[Notes]:**
-[Here](https://drive.google.com/open?id=0B6QogV2AJFKiaUlzWGx1Q2xEcHc) is a recording of the issue.
-Closed Captions/Subtitles should be displayed in Min-Vid player only if they are set to ON for the played video on YouTube.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest Min-Vid version (3.3.0b built on 12/27/2016).
