### ISSUE TITLE
Min Vid stopped working...

### ISSUE THREAD

**Issue by yanoom** [meandavejustice/min-vid#523]
I get the same error for some videos I try to play on Min Vid:

"Something's gone wrong with this video. Try again later.
Open in new tab"

![minvid](https://cloud.githubusercontent.com/assets/14986120/21143302/c7347c4e-c14e-11e6-8db3-8caa4944d487.png)

Thanks

**Comment by Softvision-VladBacia** [comment]
@yanoom , thank you for reporting this. This issue seems related to #331 . 

Can you provide the link for the used videos? I would like to verify them on my machine.

**Comment by yanoom** [comment]
Hi,
thanks for your quick reply.

When I went in to copy the URL, I realized it does work for some videos
(and not all as I mentioned in the bug, should I change it?)

Here's an example for a video that doesn't work:
https://www.youtube.com/watch?v=y2lpR-mlQTw

It is in Hebrew, I guess it might suggest somehow the failure.
~-~-
​Yanoom

**Comment by Softvision-VladBacia** [comment]
I've tried to play the video in Min-Vid player but couldn't. Same error is displayed. I think it is related to HTML5 support or the video was restricted by the user.

**Comment by danya02** [comment]
Confirmed on my machine. [This video](https://www.youtube.com/watch?v=6Dakd7EIgBE) doesn't work, but [this one](https://www.youtube.com/watch?v=QgaTQ5-XfMM) does.
