### ISSUE TITLE
Close button only stops visualization on Soundcloud songs

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [meandavejustice/min-vid#535]
[Notes]:
- This issue was mentioned by Jared in the PR for SoundCloud support but at the end he said that major issues were fixed and didn't saw a followup bug for this. So either it was not fixed or it's a regression.

[Affected versions]:
- Firefox 50.1.0 and above
- Min Vid 0.3.3b

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Min Vid add-on is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to https://soundcloud.com page.
3. Right click on a song name and choose the "Send to mini player" option.
4. Click the play button and after the song starts, click the close button "[x]" from top right.
5. Observe player behavior.

[Expected result]:
- The played song stops and player is closed.

[Actual result]:
- The player visualization is stopped but the song continues to play and player is not closed. 

[Additional notes]:
- This issue is not reproducible with YouTube or Vimeo videos.
- Here is a recording of the issue: https://goo.gl/7QOASj.

**Comment by meandavejustice** [comment]
I'm having trouble reproducing this issue. @SoftVision-PaulOiegas. Is there a specific track I should try with?

**Comment by SoftVision-PaulOiegas** [comment]
Well following the above steps I can still reproduce it on latest Nightly on Windows and Mac OS using a build made today from the repo. I just navigate to soundcloud.com homepage, right click a song title from the suggested content and I cannot close the player afterwards.
This only happens on SoundCloud, the YouTube videos work perfectly...

**Comment by meandavejustice** [comment]
I was finally able to reproduce this today. Gunna get to the bottom of it. Thanks for your investigation @SoftVision-PaulOiegas
