### ISSUE TITLE
Min-Vid is not closed when closing Firefox

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#539]
[Notes]:
- If you try to reopen the browser while the Min-Vid player is still open you will get the "Firefox is already opened..." message.
- If you close the Min-Vid player after closing the browser, the player loses it's custom position on the screen.

[Affected versions]:
- Nightly 53.0a1
- Min-Vid 0.3.3b (built on 12/27/2016)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.3.3b) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to https://www.youtube.com and send a video to the mini player.
3. Observe the Min-Vid while closing the browser.

[Expected result]:
- The Min-Vid player is also closed.

[Actual result]:
- The Min-Vid player remains open.

[Additional Notes]:
- The issue is also reproducible on the Test Pilot version of the add-on.
- Attached a screen recording of the issue:
![min-vid is not closed when closing firefox](https://cloud.githubusercontent.com/assets/18304511/21502708/6c4217f8-cc5a-11e6-8afd-cf75b296f06e.gif)

**Comment by 6a68** [comment]
This should be a straightforward fix.

When a window is closed, we can detect that, count the number of remaining windows, and shut down Firefox if min-vid is the only window left. I think we could either use a WindowWatcher, or listen for the window closing nsIObserver signal, then use the SDK windows lib to count the windows remaining.

**Comment by 6a68** [comment]
We may not even need to use the nsIObserver approach.

It looks like the [SDK windows module](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/windows) fires an event whenever a window is closed. Looking a little more closely in dxr, it looks like the windows module [relies on](https://dxr.mozilla.org/mozilla-central/source/addon-sdk/source/lib/sdk/windows/observer.js#21) a module called [WindowTracker](https://dxr.mozilla.org/mozilla-central/source/addon-sdk/source/lib/sdk/deprecated/window-utils.js#77) (inside a 'deprecated' folder...but heavily used by SDK code) which [does the WIndowWatcher stuff](https://dxr.mozilla.org/mozilla-central/source/addon-sdk/source/lib/sdk/deprecated/window-utils.js#18-19) already.

**Comment by meandavejustice** [comment]
@6a68 wow that greatly simplifies this, good work investigating

**Comment by 6a68** [comment]
Oh wait, it looks like [the SDK window docs](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/windows#close) specifically mention that you might not get the close event if the user is closing the browser, because the addon itself may be unloaded before the close event is fired from all windows.

I bet we can hack around this by closing the minvid window whenever the addon is unloaded.

So the tasks would just be

1. listen for the SDK window 'close' event, count up visible windows, and if minvid's the only one left, close it as well
2. close the minvid window, if open, any time the addon is unloaded

**Comment by 6a68** [comment]
Hmm. Maybe the simplest thing is to just listen for [APP_SHUTDOWN reason](https://developer.mozilla.org/en-US/Add-ons/Bootstrapped_extensions#Reason_constants) in the shutdown function, and always close the minvid window in that case.

**Comment by 6a68** [comment]
Hmmmmmmm. We already have code that [listens for the application shutdown event](https://github.com/meandavejustice/min-vid/blob/master/index.js#L51), and should always close the min-vid window as part of shutdown.

**Comment by 6a68** [comment]
OK, I think we can add a listener for the first signal fired when application shutdown is requested: https://developer.mozilla.org/en-US/docs/Observer_Notifications#Application_shutdown

Just shove it into either index.js or window-utils.js where we add the listener on startup (via `Services.obs.addObserver`), then respond to the listener by closing the min-vid window & unregistering the listener.

**Comment by 6a68** [comment]
Maybe the best signal to listen to is `quit-application-granted`, so that we know the shutdown won't be canceled by another listener.

**Comment by 6a68** [comment]
Nope. Trying `browser-lastwindow-close-requested`

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest Min-Vid version 0.3.3b built on 1/16/2016.
