### ISSUE TITLE
Replicate player state for SoundCloud embeds

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [meandavejustice/min-vid#542]
[Affected versions]:
- Nightly 53.0a1
- Min-Vid 0.3.3b (built on 12/28/2016)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.3.3b) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to https://soundcloud.com/.
2. Hover on one of the song thumbnails displayed in the homepage and click the play button.
3. After the "SoundCloud" player appears at the bottom of the page, right click on the song name and send it to the Min-Vid player.
4. Observe the Min-Vid player.

[Expected result]:
- The "SoundCloud" player is paused and the song resumes playing in the Min-Vid player.

[Actual result]:
- The "SoundCloud" player continues to play, the song is sent to the Min-Vid player and is paused.

[Notes]:
- This might be related to #271.
- The sound volume state isn't replicated either.
- Attached a screen recording of the issue:
![minvid-resume-playback](https://cloud.githubusercontent.com/assets/20083658/21542326/a14c43da-cdc5-11e6-9e7b-0b6690b7c537.gif)

**Comment by wresuolc** [comment]
We're dropping support for soundcloud and vimeo
