### ISSUE TITLE
Min-Vid wrongly updates itself to the production version

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#543]
[Notes]:
- This can happen naturally if the "Update Add-ons Automatically" option is checked in about:addons.
- The issue might be caused by the fact that the production xpi and the custom xpi have the same version number. If you change the version number to a higher one before making the xpi, the issue is no longer reproducible.

[Affected versions]:
- Firefox 50.1.0 and above
- Min-Vid 0.3.3b

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Min-Vid add-on is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Go to about:addons and click the Extensions tab.
3. Click the Gearwheel icon and choose the "Check for Updates" option.
4. Repeat Step 3.

[Expected result]:
- Step 3: No updates are found.
- Step 4: No updates are found.

[Actual result]:
- Step 3: Min-Vid is updated to 0.3.3c.
- Step 4: Min-Vid is updated to 0.3.3.

[Additional Notes]:
- Here is a screen recording of the issue: https://goo.gl/sJFjKO.

**Comment by SoftVision-PaulOiegas** [comment]
@meandavejustice This issue hasn't been touched yet and it's kind of a blocker at least for testing the dev version of the add-on. Currently the add-on even auto updates while you use the mini player and closes it after.
I don't know if this would affect the release, but maybe we should look into it to be sure that it won't.

**Comment by meandavejustice** [comment]
@SoftVision-CiprianMuresan @SoftVision-PaulOiegas Digging into this now, I misunderstood the issue before thinking it was more of an edge case than it is.

**Comment by meandavejustice** [comment]
@SoftVision-PaulOiegas @SoftVision-CiprianMuresan This seems to be an inherent annoyance when dealing with addons. The addon is using the [update url](https://github.com/meandavejustice/min-vid/blob/master/package.json#L12) to update itself. We don't really have control of this without updating the package json each time. For now I would suggest turning off auto updates when doing this sort of testing.

**Comment by wresuolc** [comment]
The add-on won't update itself to an older version.  How are these newer add-ons being generated without being higher versions?

**Comment by SoftVision-CiprianMuresan** [comment]
Fixed by  	9ec35b4.
The issue is no longer reproducible on the latest Min-Vid version (0.3.4-beta).
