### ISSUE TITLE
Large number of testpilottest pings submitted from min-vid

### ISSUE THREAD

**Issue by mreid-moz** [meandavejustice/min-vid#545]
Similar to #457 and #455, I'm still seeing a large number of `testpilottest` pings being send from the min-vid test. For part of today (2017-01-04):

```js
    "@min-vid": {
      "unique_clients": 359,
      "count": 1588700, // number of submissions
      "size": 20517994328 // total uncompressed bytes
    }
```

You can find the monitoring code and results on the [realtime dashboard](https://pipeline-cep.prod.mozaws.net/).

**Comment by 6a68** [comment]
@mreid-moz Hey, could you provide a little guidance on how to navigate the realtime dashboard site? I can't figure out how to see the min-vid data.

I'm working on integrating a new metrics library for experiment authors (#546), which might fix this issue.

**Comment by 6a68** [comment]
I can just take this issue, since I'm in here anyway.

**Comment by mreid-moz** [comment]
@6a68 yeah, head to the "Dashboards" tab, then "Raw outputs", find the `analysis.mreid.mreid_testpilottest_volume.tpt_stats.json` file (or just [click here](https://pipeline-cep.prod.mozaws.net/dashboard_output/analysis.mreid.mreid_testpilottest_volume.tpt_stats.json)) :)

**Comment by mreid-moz** [comment]
Any update on this issue?

**Comment by meandavejustice** [comment]
@mreid-moz This should have been fixed in https://github.com/meandavejustice/min-vid/commit/bcbf6b3ede6d5abb4031cb8eddf7bf78ddb71119 which will be going out in the next update. I'm planning to do a minor update mid next week

**Comment by mreid-moz** [comment]
Cool, thanks for the update.

**Comment by wresuolc** [comment]
@meandavejustice - what does this mean for analysis of min vid data?  Was there a particular ping being sent too often so it'll be overblown in the data, or...? /cc @sunahsuh

**Comment by sunahsuh** [comment]
cc @ilanasegall

**Comment by mreid-moz** [comment]
We were seeing ~8000-12000 `testpilottest` pings per unique client per day from min-vid. We're now seeing under 1000 pings per client per day.

**Comment by meandavejustice** [comment]
@wresuolc The most recent fix was an issue where "available" pings were going out too often https://github.com/meandavejustice/min-vid/commit/bb4561b967. I'm guessing that is the ping that was the problem
