### ISSUE TITLE
Vimeo videos and SoundCloud songs cannot be played on Linux

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [meandavejustice/min-vid#551]
[Affected versions]:
- Firefox Nightly 53.0a1 (20170112030301)
- Min Vid 0.3.3b

[Affected Platforms]:
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Min Vid add-on is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to https://soundcloud.com or vimeo.com page.
3. Right click on a song name and choose the "Send to mini player" option or hover the video and click the overlay button.
4. Observe the Min Vid player behavior.

[Expected result]:
- The mini player is launched and the video / song is loaded.

[Actual result]:
- The mini player is launched but the user is presented with an error.

[Additional notes]:
- Tried to play multiple videos and songs from suggested content, none of them worked so it's not specific to some videos.
- This issue is not reproducible with YouTube videos.
- Here are some console errors for both SoundCloud and Vimeo.
![screenshot from 2017-01-12 19_34_54](https://cloud.githubusercontent.com/assets/17258026/21900966/913f4098-d8fe-11e6-86af-373f1d42bb4b.png)
![screenshot from 2017-01-12 19_36_18](https://cloud.githubusercontent.com/assets/17258026/21900971/96e24f90-d8fe-11e6-896a-6f039e1aeccf.png)

**Comment by SoftVision-PaulOiegas** [comment]
Found out that the Flash Player was outdated on Linux, but after I updated it, mostly the same errors appeared.

**Comment by meandavejustice** [comment]
@SoftVision-PaulOiegas hmm, this doesn't use the flash player. What linux were you using? Seems like an issue with codecs

**Comment by SoftVision-PaulOiegas** [comment]
I was using Ubuntu 14.04 but it seams that we needed to use an extra command (sudo apt-get install ubuntu-restricted-extras) to install some restricted extras. @Softvision-VladBacia performed some further investigations and managed to make Vimeo videos to work. 

However, we could not theck the SoundCloud part since it's broken. @SoftVision-EmilPasca logged today a separate issue for it (#559)

**Comment by meandavejustice** [comment]
@SoftVision-PaulOiegas Mind taking another look at this? Should be fixed

**Comment by SoftVision-PaulOiegas** [comment]
Indeed, this is working now. I forgot to close it. Thanks for the heads up.
