### ISSUE TITLE
min-vid stuck in loading video

### ISSUE THREAD

**Issue by PinkiePie93** [meandavejustice/min-vid#556]
min-vid plays the video like i can here in my headphones but shows "loading video from youtube.com".
also if i load a new video it stays in that animation

**Comment by meandavejustice** [comment]
@PinkiePie93 would you mind providing the url you are seeing this on for testing? thank you :)

**Comment by meandavejustice** [comment]
closing as stale after no response, feel free to reopen if you are still having the issue
