### ISSUE TITLE
Inconsistent default volume level between Youtube and Vimeo & Soundcloud when sending content to mini player

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [meandavejustice/min-vid#565]
[Affected versions]:
- Firefox Nightly 53.0a1 (20170118030214)
- Min Vid 0.3.3b

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Min Vid add-on (01.18.2017) is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to YouTube main page and send a video to mini player.
3. Observe the volume of the video in Min Vid.
4. Navigate to Vimeo or SoundCloud page and send a video / song to mini player.
5. Observe the volume of the video / song in Min Vid.

[Expected result]:
- All the content sent to mini player has volume to 100% by default.

[Actual result]:
- Vimeo and SoundCloud videos / songs have only 50% volume by default.

[Additional notes]:
- I'm not sure if 100% volume is the desired behavior but at least we should have consistency across the all websites that are supported by Min Vid.
- Here is a screen recording of the issue - https://goo.gl/3nRTbD.

**Comment by SoftVision-CiprianMuresan** [comment]
Volume levels are still inconsistent across supported platforms. 
- If an item is sent from SoundCloud or YouTube, the volume will be set at 50%.
- If an item is sent from Vimeo, the volume will be set at 100%.
- If an item is sent from YouTube or SoundCloud and then a Vimeo one is sent, the volume level will remain at 50%.
- If an item is sent from Vimeo and then a YouTube or SoundCloud one is sent, the volume level will remain at 100%.

**Comment by wresuolc** [comment]
We're dropping support for soundcloud and vimeo
