### ISSUE TITLE
[Vimeo] No sound can be heard if unmute button is pressed after dragging slider to 0%

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [meandavejustice/min-vid#566]
[Affected versions]:
- Firefox Nightly 53.0a1 (20170118030214)
- Min Vid 0.3.3b

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Min Vid add-on (01.18.2017) is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to Vimeo main page and send a video to mini player.
3. Choose to "Play" the video and after sound can be heard, reduce the volume to 0%.
4. Click the "Unmute" button from left side of the volume slider.
5. Listen mini player behavior.

[Expected result]:
- Volume slider is increased to a minimal value and sound can be heard.

[Actual result]:
- Volume remains to 0% and no sound can be heard.

[Additional notes]:
- Here is a screen recording of the issue - https://goo.gl/LPlqUS.

**Comment by meandavejustice** [comment]
no longer seeing this

**Comment by SoftVision-PaulOiegas** [comment]
I agree. Verified on YouTube, Vimeo and SoundCloud and all 3 are behaving the same. Volume correctly raises to the last user set value after unmute.
