### ISSUE TITLE
Volume slider changes position only after second unmute, if it was manually set to 0% previously 

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [meandavejustice/min-vid#567]
[Affected versions]:
- Firefox Nightly 53.0a1 (20170118030214)
- Min Vid 0.3.3b (01/19/2017)

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Min Vid add-on (01/19/2017) is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to YouTube main page and send a video to mini player.
3. Choose to "Play" the video and after sound can be heard, move the volume slider to 0%.
4. Click the "Unmute" button and observe slider behavior.
5. While observing the volume slider, mute and unmute again the video.

[Expected result]:
- Volume slider automatically moves to a minimal value higher than 0% each time video is unmuted.

[Actual result]:
- Step 4: Volume slider remains to 0% position.
- Step 5: Volume slider moves to a minimal value higher than 0%.

[Notes]:
- Here is a screen recording of the issue - https://goo.gl/rkSYjP.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest Min Vid version built on 4/11/2017. After clicking the "Unmute" button the volume slider moves back to the volume level it was at Step 3.
