### ISSUE TITLE
[YouTube] For each video sent to mini player, the sound volume increases when lowering the volume slider (above 75%)

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [meandavejustice/min-vid#568]
[Affected versions]:
- Firefox Nightly 53.0a1 (20170118030214)
- Min Vid 0.3.3b (01/19/2017)

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Min Vid add-on (01/19/2017) is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to YouTube main page and send a video to mini player.
3. Observe the video volume slider position.
4. Choose to "Play" the video.
5. While listening to the sound of the video, lower a bit the volume (above 75%)

[Expected result]:
- The video sound volume decreases.

[Actual result]:
- The video sound volume wrongly increases.

[Notes]:
- It seems that the volume slider incorrectly shows 100% when in fact the volume is at 50% by default.
- Here is a screen recording of the issue - https://goo.gl/TLsYBF.
- This can be observed also by muting and unmuting the video. The slider is brought to 50% after unmute, the real value - https://goo.gl/7pngm5.

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Min Vid version built on 4/11/2017.
