### ISSUE TITLE
Status of add-on localization?

### ISSUE THREAD

**Issue by flodolo** [meandavejustice/min-vid#569]
I'm currently on 0.9.3, and the add-on is in English.

We've opened up localization for this add-on for a couple of months now, and added new strings as recently as last week, so I wonder why there's no localized UI at this point.

Out of curiosity I've checked the .xpi and I see an it.properties, but UI is in English for me.

**Comment by meandavejustice** [comment]
@flodolo Localization should be working. Would you mind pinging me in the irc channel and we try to figure this out together. nick: `JSON_voorhees`

**Comment by meandavejustice** [comment]
Fixed in 0.3.4
