### ISSUE TITLE
Popupbar at top of page

### ISSUE THREAD

**Issue by TriMoon** [meandavejustice/min-vid#570]
PLEASE for the sake of sanity REMOVE the popup to rate the extension that appears randomly on top of a webpage im viewing !!!
It's not due to the page thats being viewed it's the extension that ADDS this popup.
Im about to uninstall this extension just because of THIS issue, it's driving me nuts!

**Comment by SoftVision-CiprianMuresan** [comment]
@TriMoon, that pop-up is not caused by Min-Vid, it's a Test Pilot pop-up. 
Please open an issue on the Test Pilot repo: https://github.com/mozilla/testpilot/issues.

**Comment by meandavejustice** [comment]
@TriMoon This behavior has to do with the Test Pilot extension, you could [file an issue](https://github.com/mozilla/testpilot/issues/new) on that repo to start a discussion about improving that ui.
