### ISSUE TITLE
[Soundcloud] Video playback error message is displayed for audio files

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#576]
[Notes]:
- As a suggestion, wouldn't it be better to simplify the message in order for it to fit all cases? (both videos and songs)

[Affected versions]:
- Firefox 51 and above
- Min Vid 0.3.3b

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Min Vid add-on is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to https://soundcloud.com/heyamine/caroline page.
3. Hover the album image and send the track to the mini player.
4. Observe the error message.

[Expected result]:
- An error message specific for Soundcloud songs is displayed.

[Actual result]:
- "Something's gone wrong with this video." message is displayed.

[Additional notes]:
- Here is a recording of the issue: 
![inaccurate error message](https://cloud.githubusercontent.com/assets/18304511/22294762/21268f22-e31d-11e6-8206-6630f7994f27.gif)

**Comment by meandavejustice** [comment]
Looking at this right now

**Comment by meandavejustice** [comment]
http://stackoverflow.com/questions/36360202/soundcloud-api-urls-timing-out-and-then-returning-error-403-on-about-50-of-trac/36529330#36529330

>Update: As of 5/25/2016, the issue is still not fixed and SoundCloud has yet to reply with a satisfactory response. They're saying that right holders have the option to disable API requests, but every time I ask if they can show me a screenshot or anything at all that proves this behavior is intentional, their helpdesk no longer replies.

>SoundCloud emailed back saying they have introduced an option for right holders to disable all API access to tracks by default, returning this 403 error when requested. They also said it's understandable that this is a confusing feature, and that they hope to make it more clear.

>SoundCloud: please let applications read basic track information. Blocking access from simple information such as track ID breaks so many applications that use your API. It doesn't make any sense to block access to applications from retrieving a simple ID, title, or duration.

>Also, most users who have tracks that are blocking API access have no idea about configuring this, so I'm still fairly convinced this is a bug in the SoundCloud API.

So basically same story we see on any platform. API gives poor ux whenever a major publisher is involved. Thanks for finding this issue @SoftVision-CiprianMuresan , I'll add a more specific error for when we receive a `403` from the server.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest Min-Vid version (0.3.4-beta).

**Comment by SoftVision-PaulOiegas** [comment]
It seems that we have a regression. The issue is reproducible on both Min Vid release and custom repo build.

**Comment by SoftVision-PaulOiegas** [comment]
Double checked on Windows too and it is fixed. 👍
