### ISSUE TITLE
Sending the same video to the mini player pauses the one that is playing

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#580]
[Affected versions]:
- Firefox 51 and above
- Min Vid 0.3.4-beta

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Min Vid add-on is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.youtube.com and send a video to the mini player.
3. Play the video.
4. Send the same video to the mini player and observe the player behavior.

[Expected result]:
- Video playback is unaffected.

[Actual result]:
- Video playback is paused.

[Notes]:
- Here is a recording of the issue: 
![sending the same video to the mini player pauses the one playing](https://cloud.githubusercontent.com/assets/18304511/22336336/8b23ab26-e3ea-11e6-8175-543d3dd12bea.gif)

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Min Vid version built on 4/11/2017.
