### ISSUE TITLE
"Unmute" message appears for a fraction of a second after sending YouTube videos to the mini player

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#581]
[Affected versions]:
- Firefox 51 and above
- Min Vid 0.3.4-beta

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Min-Vid add-on is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.youtube.com and send a video to the mini player.
3. Play the video.
4. Observe the top left part of the mini player as you send a different video to it.

[Expected result]:
- The video is loaded in the mini player with no rendering issue.

[Actual result]:
- An "Unmute" message flashes in the video player.

[Notes]:
- Here is a recording of the issue: 
![unmute message appears for a fraction of a second after sending youtube videos to the mini player](https://cloud.githubusercontent.com/assets/18304511/22337919/c6a1ab36-e3ee-11e6-8795-aa690ae23b44.gif)

**Comment by meandavejustice** [comment]
This bug has me somewhat baffled

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest Min Vid version built on 4/11/2017.
