### ISSUE TITLE
Ensure Min Vid's `available` ping only happens once per page

### ISSUE THREAD

**Issue by wresuolc** [meandavejustice/min-vid#583]
I think we talked about this a long time ago, and maybe we already fixed it?

Our stats were getting overwhelmed with "available" pings from the same page.  Like, go to youtube.com and you get 50 pings from all the videos on the page.  We want just one ping no matter how many videos are on the page.

**Comment by meandavejustice** [comment]
This should have been fixed in the last release https://github.com/meandavejustice/min-vid/commit/bb4561b967
