### ISSUE TITLE
Repeat and close button persist after pressing repeat button

### ISSUE THREAD

**Issue by BrainStone** [meandavejustice/min-vid#590]
After I press the repeat button or use the YouTube autorepeat feature the video continues to play but this screen doesn't go away, blocking the video itself.

http://puu.sh/tGJ6I/e944666841.png

* OS: Windows 10
* Firefox Version: 51.0.1

**Comment by SoftVision-PaulOiegas** [comment]
@BrainStone Hi and thanks for reporting this ! It seams that you have sighted an issue that is probably related to the same root cause of another one that we already logged. I will mark this as closed in favor of that one, so please continue any discussions there.

Thanks !
