### ISSUE TITLE
[Soundcloud] Song visualization starts to twitch and continues to degrade with every new song sent

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [meandavejustice/min-vid#591]
[Affected versions]:
- Firefox 51 and above
- Min Vid 0.3.4 

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Min-Vid add-on is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.soundcloud.com and send a song to the mini player.
3. Play the song and switch to frequency view (2nd visualization) for better view.
4. Send another song to mini player.
5. Repeat steps 3 and 4 multiple times observing the visualization quality.

[Expected result]:
- Visualization quality is the same no matter how many songs are sent to mini player.

[Actual result]:
- Visualization starts to twitch and continues to degrade with every new song sent

[Notes]:
- Here is a recording of the issue - https://goo.gl/EQY6E9.
- Bot the visualizations have the same issue but it's more visible on the frequency view.

**Comment by meandavejustice** [comment]
well, this is embarrassing. Thanks for finding this @SoftVision-PaulOiegas

**Comment by SoftVision-PaulOiegas** [comment]
Hammered it and it didn't broke. Good fix ! 👍
