### ISSUE TITLE
[Soundcloud] The elapsed time is larger than the total time if you wait a while before starting playback

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#604]
[Affected versions]:
- Nightly 54.0a1
- Min Vid 0.3.4 

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Min-Vid add-on is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to https://soundcloud.com/ and send a song to the mini player.
3. Wait for an exact period of time. (eg. 2 minutes)
4. Choose to play the song and leave it until the end.
5. Observe the song timestamp once the Replay/Close screen appears.

[Expected result]:
- Timestamp shows the elapsed time out of the total time. (eg. 4:44/4:44)

[Actual result]:
- The elapsed time is with 2 minutes over the total time.

[Notes]:
- The same thing occurs if you pause the song and then wait for a while.
- Here is a recording of the issue - https://goo.gl/5gb03G.

**Comment by meandavejustice** [comment]
I have plans to completely rewrite [meandavejustice/audiosource](https://github.com/meandavejustice/audiosource), as it's become quite a mess over the years. Since this is a minor visual bug which I assume won't be noticed often, I vote we push it off until that rewrite happens.(hoping to start on this next weekish)

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible on the latest Min Vid version built on 4/11/2017.
