### ISSUE TITLE
[Soundcloud] The mini player is unresponsive for a few seconds after sending a second song to it

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#610]
[Notes]:
- I have a hunch that this might be caused by the "Loading media from Soundcloud" message that could be running in background even if it's not displayed.

[Affected versions]:
- Firefox 51.0 and up
- Min-Vid 0.3.4-dev (built on 2/13/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.3.4-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.soundcloud.com page and send a song to the mini player.
3. Send a different song to the mini player and quickly hover the player.
4. Click the "Play" button and observe the mini player behavior.

[Expected result]:
- Playback starts.

[Actual result]:
- The mini player is unresponsive.

[Additional Notes]:
- Attached a screen recording of the issue: https://goo.gl/gcB3Zt

**Comment by meandavejustice** [comment]
I've been working on some improvements to audio playback which should fix this and a couple other playback and visualization bugs, as well as add better looking visualizations. Hoping to get that in within the next couple of days.
