### ISSUE TITLE
Playback stutters when a video is replayed, if YouTube's loop option is also enabled

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#622]
Split from #621.

[Affected versions]:
- Firefox 51.0 and up
- Min-Vid 0.3.4-dev (built on 2/24/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.3.4-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.youtube.com page and send a video to the mini player.
3. Right click the video from the mini player and choose the "Loop" option.
4. Fast Forward the video to the end and wait.
5. Click the Replay button and observe the behavior.

[Expected result]:
- The video is replayed.

[Actual result]:
- The video stutters as it is playing and the Play/Pause button switches from one state to the other intermittently.

[Notes]:
- Attached a screen recording of the issue:
![yt loop conflict with replay option](https://cloud.githubusercontent.com/assets/18304511/23299456/52de64ac-fa8a-11e6-8540-cdba0adf9122.gif)

**Comment by meandavejustice** [comment]
As a part of the work on #453, I've added in the react-player library which should take care of this. We will also be handling "replay" or "looping" functionality with these changes.

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Min Vid version built on 4/11/2017.
