### ISSUE TITLE
Playlist doesn't function.

### ISSUE THREAD

**Issue by JeanMichel13131313** [meandavejustice/min-vid#625]
I like to have my own playlist playing while using MinVid....but all it does is to play a single video from my playlist, and stops.
...is there something I'm not understanding...?
How do I get MinVid to play ALL the videos in my playlist, automatically...?

**Comment by SoftVision-CiprianMuresan** [comment]
Hi @JeanMichel13131313, thanks for the feedback. The Playlist function is being tracked in #453.
