### ISSUE TITLE
Playback stutters and lots of pings are sent when the "Play / Pause" button is quickly double or triple clicked

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [meandavejustice/min-vid#626]
[Notes]:
- When this occurs the browser performances are also affected.
- Lots of play / pause pings are sent.
- First I managed to reproduce this while having other application in full screen. You need to double click the mini player to have it in focus and to make the desired action.

[Affected versions]:
- Firefox 51.0 and up
- Min-Vid 0.3.4-dev (built on 2/27/2017)

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on version (0.3.4-dev) was previously installed on a clean profile.
- Firefox is already opened with the above profile and with Browser console opened with "Net" filter on. 

[Steps to reproduce]:
1. Navigate to www.youtube.com page and send a video to the mini player.
2. Choose to "Play" the video.
3. Quickly double (harder to reproduce) or triple click on the "Play / Pause" button.
4. Observe the playback behavior and the console logs.  

[Expected result]:
- The "Play / Pause" actions are correctly made and do not affect the video playback.

[Actual result]:
- Playback shutters and lots of pings are sent when the "Play / Pause" button is quickly double or triple clicked.

[Additional Notes]:
- Haven't managed to reproduce this on Mac OS.
- Attached a screen recording of the issue: https://goo.gl/OuYyCP.

**Comment by meandavejustice** [comment]
Is this still and issue in the queue branch? @SoftVision-PaulOiegas

**Comment by SoftVision-PaulOiegas** [comment]
Seems so https://goo.gl/drOM0Q.

**Comment by SoftVision-CiprianMuresan** [comment]
I've found that the issue is more easily reproducible if you have a lot of loaded tabs (20-30). This way the issue is also reproducible on Mac OS.

**Comment by SoftVision-PaulOiegas** [comment]
The fix seems pretty ok. I have managed to reproduce this, but now I consider it a super edge case (spam holding "Space" key). I would say that we can consider it fixed. 
However, I have logged the remaining related behavior with "Replay" button separately (#836).
