### ISSUE TITLE
Track added to queue UI

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#635]
We need to show the user a message when a new track is added to the queue and the queue panel is not showing. I'm thinking something like the toaster notification which could slide in under the top or bottom control bar.
cc/ @youwenliang

**Comment by youwenliang** [comment]
@meandavejustice Do you mean something like this?
![added message](https://cloud.githubusercontent.com/assets/8919308/23891876/4d91ee36-08d3-11e7-88b4-801ab974d0aa.png)

**Comment by meandavejustice** [comment]
@youwenliang Looks good to me, thanks!
