### ISSUE TITLE
min-vid initialization from embedded video logo

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#64]

**Comment by johngruen** [comment]
Here are the assets for this one: 
![video overlay](https://cloud.githubusercontent.com/assets/3323249/16807480/9bacda3e-48e6-11e6-9273-8f0f63dc08b3.png)

https://www.dropbox.com/s/00tvss2jsoduiub/Min-Vid%20Player%20Icon.svg?dl=0

**Comment by johngruen** [comment]
here's that text for easier copy pasting:

on hover over video,  fade container 
transition: opacity .25s cubic-bezier(0.0,0.0,0.2,1);

icon should be opacity: .9 by default
on hover/focus/active over the container opacity: 1
hover transition: opacity .1s cubic-bezier(0.4,0.0,1,1);

Container is the hit target, something like this:
position: abosolute;
top: 0;
left: 12px;
width: 46px;
height: 36px;
border-radius: 0 0 3px 3px;
background: rgba(0,0,0,.2);
display: flex;
align-items: center;
justify-content: center;
