### ISSUE TITLE
need a default image for tracks without a preview/album cover

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#645]
cc/ @youwenliang

**Comment by youwenliang** [comment]
@meandavejustice Does this only happen with audio tracks and not videos?
We can come up with a preview image for the tracks soon.

**Comment by meandavejustice** [comment]
@youwenliang For videos I was planning to try and grab a frame from the video to use as the preview image. But it would be good to have a fallback for when that fails as well

**Comment by TLHuang** [comment]
Upload audio and video default images. 
[thumbnails.zip](https://github.com/meandavejustice/min-vid/files/872085/thumbnails.zip)
