### ISSUE TITLE
The bottom quarter of the progress bar does not react to clicks

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#646]
[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 3/10/2017)

[Affected Platforms]:
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.3.4-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.youtube.com page and send a video to the mini player.
3. Fast forward the video by clicking the bottom quarter of the progress bar at a different time.
4. Observe the behavior.

[Expected result]:
- The progress bar is moved to that location.

[Actual result]:
- The progress bar does not respond to clicks.

[Additional Notes]:
- The issue is not reproducible on Windows.
- Attached a screen recording of the issue: [Link](https://drive.google.com/open?id=0B8ICzPJynbchbmQyV3FWMzlDR0U)

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible on the latest Min Vid version built on 4/11/2017.
