### ISSUE TITLE
Firefox is not focused after sending a video from the mini player to the browser

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#647]
[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 3/10/2017)

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.3.4-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.youtube.com page and send a video to the mini player.
3. Open a different app (notepad, file explorer) and move it over the browser window.
4. Hover the mini player and click the "Send to tab" button.
5. Observe the browser window.

[Expected result]:
- The browser window is brought into foreground.

[Actual result]:
- The browser window remains in background.

[Additional Notes]:
- The issue is not reproducible on Mac OS.
- Attached a screen recording of the issue: 
![firefox is not focused after sending a video from the mini player to the browser](https://cloud.githubusercontent.com/assets/18304511/23800528/61a58da4-05b5-11e7-912f-3dffc0622105.gif)

**Comment by meandavejustice** [comment]
This is probably a one liner for someone with deep Gecko wisdom, cc @6a68 

It also could be as simple as finding the window and calling [`activate()`](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/windows#activate())

**Comment by meandavejustice** [comment]
closing for #608
