### ISSUE TITLE
The player controls are no longer actionable after minimizing Min Vid

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#652]
[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 3/15/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.youtube.com and send a video to the mini player.
3. Minimize the mini player and hover it with the mouse.
4. Observe the behavior.

[Expected result]:
- All the player controls are visible and actionable.

[Actual result]:
- The player controls are no longer actionable. The "back" and "next" buttons are overlaid on other player controls.

[Notes]:
- The player also can't be moved to a different position after it was minimized.
- The minimized player does not keep the custom width, if it was set.
- Attached a screen recording of the issue:
![no player controls work after minimizing the min vid player](https://cloud.githubusercontent.com/assets/18304511/23945270/93a8b4a8-097e-11e7-8df4-845904db3af4.gif)

**Comment by meandavejustice** [comment]
Putting this one off for a bit, although it is crucial for launch. I will need to install a different window manager in order to fix this.

Pinging @6a68 to see if he has any interest in working on this, although I think his plate is really full at the moment.

**Comment by Softvision-VladBacia** [comment]
The issue is no longer reproducible on the latest Min Vid with Queue functionality built on 3/31/2017.
