### ISSUE TITLE
"Play now" and "Add to queue" icons from the context menu are white and barely visible

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#653]
[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 3/15/2017)

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.
- Default Firefox theme is enabled.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.youtube.com.
2. Right click on a video thumbnail and hover the "Min Vid" option.
3. Observe the icons for the "Play Now" and "Add to queue" options.

[Expected result]:
- Icons are visible.

[Actual result]:
- (Mac OS) The icons are not displayed until the options are hovered.
- (Windows) The icons are white and barely visible. 

[Notes]:
- Attached screenshots of the issue:
**Mac OS** 
![mac icons](https://cloud.githubusercontent.com/assets/18304511/23946165/f8658f4e-0981-11e7-9bc6-fadb486cbaed.png)
**Windows**
![windows icons](https://cloud.githubusercontent.com/assets/18304511/23946233/47110150-0982-11e7-9aca-8c60111bf11e.png)

**Comment by meandavejustice** [comment]
I was originally going to detect the themes and swap the icons to dark if there is a light theme. But then I remembered that context menus are themed at the OS level. Looks Like we need icons that have either border stroke or neutral colors to both light and dark themes.

cc/ @youwenliang

**Comment by TLHuang** [comment]
Updated the icons. They should be able okay to work on white, black and blue background. Let me know if any questions.

[icons.zip](https://github.com/meandavejustice/min-vid/files/871813/icons.zip)

**Comment by meandavejustice** [comment]
Thanks @TLHuang, they look great
