### ISSUE TITLE
Back button is wrongly displayed when a single item is in the playlist 

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#657]
[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 3/15/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.youtube.com and send a video to the mini player.
3. Hover the player with the mouse and observe the middle left side of the window.

[Expected result]:
- No player button is displayed.

[Actual result]:
- The "Back" button is displayed and is clickable.

[Notes]:
- If there is only one item in the playlist, the "back" button shouldn't be available because there is no other item in queue. 
Items that have finished playing should be transferred to the History section. And clicking the "Back" button should only go back until the first item in the playlist is reached.
- The "back" button can be clicked indefinitely and the items in the list will be duplicated.
- Attached a screen recording of the issue:
![back button is wrongly displayed when a single item is in the playlist](https://cloud.githubusercontent.com/assets/18304511/23945779/8557092a-0980-11e7-9392-99b50c122d8c.gif)

**Comment by meandavejustice** [comment]
Okay so this is a bit of a tricky situation UI wise, I think it needs a couple of extra eyes to make sure we make the right decision here.

First:
The history not displaying bug has been fixed. #664

The Problem: 
Back button should always pull from most recent history.
When pulling from history (by pressing the back button) you get the top item in the history queue(in the case of the gif above, a Big Black album). Since history is not modified we need to increment the index where we are pulling from history so that we don't just keep duplicating the big black album into the queue. (in order to let users go further back than one item into the history).

The current behavior:
If you click the back button more than once in 5 seconds it will increment and grab the next item in history.
Here is the code that handles it.

``` js
prevTrack () {
    let index;
    // if clicked more than once within
    // 5 seconds increment the index so
    // the user can get to further back
    // in history. Resets when timeout wears out.
    if (this.searchingHistory) {
      if (this.props.history.length > this.state.historyIndex + 1) {
        this.setState({historyIndex: this.state.historyIndex + 1});
      }
      index = this.state.historyIndex;
    } else {
      index = 0;
      this.searchingHistory = true;
      setTimeout(() => {
        this.searchingHistory = false;
        this.setState({historyIndex: 0});
      }, 5000);
    }

    sendToAddon({
      action: 'track-added-from-history',
      index: index
    });
  }
```

I realize this is not a perfect solution, I feel like it could be alright for the time being, though i'd really like a better solution.

cc/ @johngruen for discussion

**Comment by meandavejustice** [comment]
also, @johngruen if you have anyone else in mind that you think could give some insight into this, please feel free to include them on the thread

**Comment by SoftVision-PaulOiegas** [comment]
@meandavejustice  When we discussed and logged this issue we thought that Min Vid queue will somehow replicate in the YouTube Playlist functionality. 

Probably it's just me, but I would rather have a playlist functionality in Min Vid and listen the songs I added over and over. Than having to re add the songs over and over, if I want to listen to them more than once. 
But maybe I'm way to familiar with playlists functionality and I've always considered that Min Vid would become a good alternative to YouTube website player, while you guys imagined it to be different.

**Comment by youwenliang** [comment]
My thought is that queue is a temporary list, you can keep adding videos to the queue, and whenever a video in the queue has ended it will be pushed into the most recent history list. 

So clicking the back button means jumping back to the previous song, which is the first video in the history. If the history is empty, then there won't be a back button there (or showing a disabled back button)

p.s. You can use the repeat button to play the same video over and over without having to add the video back to the queue again.

**Comment by SoftVision-PaulOiegas** [comment]
I know, it's just that I usually let a few songs that I like to play from the playlist. Then I return to one of them and I re-listen them in the same order. You cannot do that with this kind of queue, but I'm not insisting on this behavior. As I've said, it's a personal "glitch" 😄.

Regarding the back button if there is no history, I agree with that.

**Comment by youwenliang** [comment]
I guess you can do that if we implement "Playlist" instead of "Play Queue". In that case, users can create their own playlist (which will stay the same order unless users rearrange it) or add a Youtube playlist to MinVid.

**Comment by meandavejustice** [comment]
@youwenliang What do you think about the current implementation I have mentioned above? Where we increment the index pulled from history if the back button is pressed more than once within 5 seconds? Do you think that makes sense? I wanna make sure it doesn't just cause confusion

**Comment by youwenliang** [comment]
@meandavejustice I'm not sure if I get it right, do you mean within 5 seconds all the clicks on the back button will be counted and after 5 seconds it will jump directly to the right one instead of going through the history one by one? 

For me the list goes like this: 
history 3 < history 2 < history 1 < currently playing > next in queue > queue 3 > queue 4

if you keep pressing back it will go through history 1, 2, 3... to the oldest in the history.

**Comment by meandavejustice** [comment]
@youwenliang it doesn't jump at the end of 5 seconds, it simply grabs the earlier item in history when clicking previous. If you'd like to try out an xpi I can email you one

**Comment by youwenliang** [comment]
@meandavejustice  I'd love to try it out. You can send it to mliang@mozilla.com
Thanks!

**Comment by youwenliang** [comment]
@meandavejustice 
I think the implementation makes sense, I'm still not sure what the 5 seconds is for though.

**Comment by SoftVision-CiprianMuresan** [comment]
While the actual results have not changed (the button is still there and is clickable), what happens when the button is clicked HAS changed: 
- If it is clicked once, a blank item appears in the Play Queue section.
- If it is clicked multiple times, multiple blank entries appear in the Play Queue section.
![blank entries](https://cloud.githubusercontent.com/assets/18304511/24752232/a4f46dfc-1ad5-11e7-8285-fc53a7eb2609.gif)

- After clicking the "Next" button a few times, closing and reopening Min Vid, the blank entries are now in the History section. They appear there only after closing and reopening.

**Comment by meandavejustice** [comment]
@SoftVision-CiprianMuresan just pushed a fix for the behavior you're describing

**Comment by SoftVision-CiprianMuresan** [comment]
We can close this one because the "Previous" button is no longer displayed as long as there is nothing in History.
