### ISSUE TITLE
The "Play Queue" section is wrongly displayed when Min-Vid player is opened

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [meandavejustice/min-vid#660]
[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 3/16/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to any supported platform and send a video/song to the mini player.
3. Observe the Min-Vid player.

[Expected result]:
- The video/song starts playing and the "Play Queue" section is hidden.

[Actual result]:
- The video/song starts playing and the "Play Queue" section is opened.

[Notes]:
- Attached a screen recording of the issue:
![min vid player opened with playlist](https://cloud.githubusercontent.com/assets/19226534/23997801/933d3308-0a5b-11e7-9405-ea4dc8b51973.gif)

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest Min-Vid add-on with Queue functionality. (built on 3/21/2017).
