### ISSUE TITLE
Sending a video from YouTube main player does not automatically start playback

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [meandavejustice/min-vid#661]
[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 3/16/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to "https://www.youtube.com/" and click on a video.
2. Click the Min-Vid overlay from the opened video.
3. Observe the Min-Vid player state.

[Expected result]:
- The video starts playing.

[Actual result]:
- The video does not automatically start playing.

[Notes]:
- Attached a screen recording of the issue:
![automatically start playback](https://cloud.githubusercontent.com/assets/19226534/23997900/e8036402-0a5b-11e7-9f71-a3f0f22833cd.gif)

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest Min-Vid add-on with Queue functionality. (built on 3/21/2017) However it seems like playback starts automatically regardless of where I send the video from (main players, thumbnail overlay or context menu option). 
@meandavejustice, is this intended?

**Comment by meandavejustice** [comment]
@SoftVision-CosminMuntean It should only start playback if either the `play now` option was selected from context menu or the min-vid logo clicked in overlay icon. Now that we have the ➕ icon, to add to queue, the other icon can serve as the Play Now trigger.
