### ISSUE TITLE
Strange behavior when using the left and right arrows keys to fast forward or backwards the video

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [meandavejustice/min-vid#662]
[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 3/16/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to any supported platform and send a video/song to the mini player.
3. Click the "Play" icon from the bottom left corner of the player.
4. Watch the video ~20s than press the left or right arrow key.
5. Observe the video progress bar.

[Expected result]:
- The video is fast forward/backwards 5 seconds.

[Actual result]:
- The video progress bar is reset and the video is fast forward/backwards 5 seconds from the beginning.

[Notes]:
- Attached a screen recording of the issue: https://goo.gl/U63jvO.

**Comment by meandavejustice** [comment]
There was an issue tracking the `currentTime` attribute, just updated to generate on seeking.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest Min Vid with Queue functionality built on 4/4/2017.
