### ISSUE TITLE
The scroll bar from Play Queue and History is truncated

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#663]
[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 3/16/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.
- Default resolution is set. (180 height 320 width)

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to any supported platform and send multiple videos/songs to the mini player.
3. Click the "Open Queue" button and observe the scroll bar.

[Expected result]:
- The scroll bar is fully visible.

[Actual result]:
- The scroll bar is half visible on Windows & Linux and barely visible on Mac.

[Notes]:
- Attached a screen recording of the issue:
![the scroll bar from play queue and history is truncated](https://cloud.githubusercontent.com/assets/18304511/24000507/16ca47da-0a64-11e7-84da-89df54f9c958.gif)

**Comment by meandavejustice** [comment]
changed default window size, looks much better now

**Comment by SoftVision-CiprianMuresan** [comment]
I have retested the issue on the latest Min Vid version with Queue functionality (built on 28/3/2017) and the scroll bars are still truncated on all OS's.

**Windows:**
![x button and scrollbar](https://cloud.githubusercontent.com/assets/18304511/24404359/c8de540c-13c9-11e7-899a-06a11ca2340b.png)

**Mac:**
![x button and scroll bar mac os x](https://cloud.githubusercontent.com/assets/18304511/24404374/d6ab472a-13c9-11e7-892d-e89150e63882.png)

**Linux:**
![screenshot from 2017-03-28 14_46_00](https://cloud.githubusercontent.com/assets/18304511/24404380/e00c5e4e-13c9-11e7-836d-1a2783ea4d79.png)

**Comment by Softvision-VladBacia** [comment]
I have retested the issue on the latest Min Vid version with Queue functionality (built on 31/3/2017) and the scroll bars on Widnows and Linux are the same as in comment above. 

On Mac OS X 10.12.4 the scroll bar is missing.
![missing scroll bar](https://cloud.githubusercontent.com/assets/9248513/24551542/8208a6f4-162b-11e7-83d9-afb7c21ed576.jpg)

**Comment by meandavejustice** [comment]
![2017-04-03--07-14-24-1920x1080_scrot](https://cloud.githubusercontent.com/assets/1844554/24623593/eb5423fc-1876-11e7-88ad-2c7b518eb35e.png)

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest Min Vid with Queue functionality built on 4/4/2017. The scroll bar now appears on Mac OS too.
