### ISSUE TITLE
There is no Min/Max resolution for the Min Vid player window

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#667]
[Notes]:
- If a custom resolution of 0x0 is set on Linux, the player seems to have minimum values and it will be displayed according to them. On Windows and Mac however, the player is created with a resolution of 0x0.
- If we want to keep the idea of a background player, then the same should be done for a maximum value (when doing this we should keep in mind HiDPI monitors). As it stands now, if custom values are set that exceed the screen resolution, the player is not displayed at all.

[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 3/17/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Go to about:addons->Extensions tab and double click the Min Vid addon.
3. Set a custom resolution of 0 height and 0 width.

[Expected result]:
- A minimum value for height and width is forced.

[Actual result]:
- The custom resolution is set.

[Additional Notes]:
- Attached a screen recording of the issue:
![min and max height and width for player window](https://cloud.githubusercontent.com/assets/18304511/24042822/60de8e4a-0b1c-11e7-9579-f7082daaa289.gif)

**Comment by meandavejustice** [comment]
After thinking about this for a while, I think I'm going to close as `wontfix`, only a certain amount of users are going to go digging into settings and if they want to set the window size to something weird, I think we should let them, even if it breaks their experience, especially since they can easily set it back to a reasonable size

**Comment by SoftVision-CiprianMuresan** [comment]
I agree that it's pretty easy to set the resolution back, on Windows and Linux at least. However, on Mac the browser needs to be restarted if you set a custom resolution of 0x0 (or one that exceeds the screen resolution). 
Anyway, it's your call on this.

**Comment by meandavejustice** [comment]
@SoftVision-CiprianMuresan I'll reopen and just move out of the milestone so it can be fixed after the sprint

**Comment by meandavejustice** [comment]
We need to come up with good Min and max values, @youwenliang, do you have an opinion on this?

**Comment by youwenliang** [comment]
@meandavejustice Do we have a fixed ratio? I would say min-width 320px and max width 640px

**Comment by SoftVision-CiprianMuresan** [comment]
The minimum values are ok across platforms. However the maximum values on Windows are greater than the maximum values on Mac and Linux.

On Mac and Linux: the min values are 400x260 and the max values are 1024x768.
On Windows: the min values are 400x260 and the max values are 1268x813.
![max res](https://cloud.githubusercontent.com/assets/18304511/25621131/134195ae-2f59-11e7-9569-2050e5bb2da8.PNG)

@meandavejustice and @6a68: Should we reopen this issue or should I log a separate one for this?

**Comment by meandavejustice** [comment]
@SoftVision-CiprianMuresan I'm not sure what you describe qualifies as a bug for us. We detect the resolution when loading up the addon in `index.js`. So if those resolutions are inconsistent, it's probably a firefox platform issue.

**Comment by meandavejustice** [comment]
@SoftVision-CiprianMuresan If we determine that it is an issue, lets log a new one and link back to this one. Multiple issues kept in the same github issue gets confusing.
