### ISSUE TITLE
The "x" button is not displayed in the "Play Queue" and "History" sections if the default resolution is set

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#668]
[Notes]:
- The "x" button is displayed if a custom resolution is set and the width is greater than 500.
- If a custom resolution is set, the "x" button will be displayed in different locations depending on how long the video/song title is.

[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 3/17/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.
- Default resolution is set. (height 180 width 320)

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any supported platform.
2. Send a video/song to the mini player and click the "Open Queue" button.
3. Hover the only item in "Play Queue" and observe the "x" button position.

[Expected result]:
- The "x" button is displayed in the right most position.

[Actual result]:
- The "x" button is not displayed.

[Additional Notes]:
- Attached a screen recording of the issue:
![the x button is not displayedv](https://cloud.githubusercontent.com/assets/18304511/24043134/c8dd5a0c-0b1d-11e7-95da-22fe988e67a7.gif)

**Comment by meandavejustice** [comment]
changed default window size and adjusted title styling here

**Comment by SoftVision-CiprianMuresan** [comment]
I have retested the issue on the latest Min Vid version with Queue functionality (built on 28/3/2017) and the "x" button appears. However if there are enough items in the list in order to have a scrollbar, the "x" button is too close to the scroll bar (on Linux). And on Mac OS and Windows, the scroll bar overlaps the button.

**Windows:**
![x button and scrollbar](https://cloud.githubusercontent.com/assets/18304511/24404359/c8de540c-13c9-11e7-899a-06a11ca2340b.png)

**Mac:**
![x button and scroll bar mac os x](https://cloud.githubusercontent.com/assets/18304511/24404374/d6ab472a-13c9-11e7-892d-e89150e63882.png)

**Linux:**
![screenshot from 2017-03-28 14_46_00](https://cloud.githubusercontent.com/assets/18304511/24404380/e00c5e4e-13c9-11e7-836d-1a2783ea4d79.png)

**Comment by Softvision-VladBacia** [comment]
The "X" button is fixed on Ubuntu and Windows.

On Mac OS X 10.12.4 the issue is still reproducible:
![missing scroll bar](https://cloud.githubusercontent.com/assets/9248513/24551963/52b6d4b4-162d-11e7-88a5-8ac35fb14a92.jpg)

**Comment by meandavejustice** [comment]
Would you mind taking another look at this one since #663 probably affected this?

**Comment by SoftVision-CiprianMuresan** [comment]
Seems like it was fixed. The "x" button is correctly placed on Mac OS too.
