### ISSUE TITLE
Cannot install min-vid from testpilot on nightly

### ISSUE THREAD

**Issue by LoveIsGrief** [meandavejustice/min-vid#672]
Maybe the root is that one cannot install testpilot on nightly, but I'm not sure. At least from [here](https://testpilot.firefox.com/experiments/min-vid) it's not possible to install min-vid on nightly.

**Comment by SoftVision-CosminMuntean** [comment]
Hi @LoveIsGrief , thanks for reporting this.

Is there any chance that you have Test Pilot add-on already installed but disabled in "about:addons"? If yes can you please go to "about:addons" page and from "Extensions" section re-enable it and try again to install Min Vid?

Also, when you are on Min Vid details page do you have the green "Install Test Pilot & Enable Min Vid" button or the blue "Enable Min Vid" button? See this screenshot: https://goo.gl/zawfNh.

**Comment by LoveIsGrief** [comment]
Hi @SoftVision-CosminMuntean ,

Indeed, test-pilot was already installed and disabled. Reactivating it allowed me to install min-vid.

Cheers
