### ISSUE TITLE
The "x" button doesn't remove items from the History section

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#674]
[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 3/17/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.
- Custom resolution is set. (width at least 500)

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any supported platform.
2. Send a few videos/songs to the mini player and click the "Next" button until the last video/song is playing. 
3. Click the "Open Queue" button and go to the History section.
4. Hover one of the items from the list. 
5. Click the "x" button for one of the items and observe the behavior.

[Expected result]:
- The item is removed from the list.

[Actual result]:
- The item remains in the list.

[Notes]:
- Attached a screen recording of the issue: 
![x button doesn t remove items from the history section](https://cloud.githubusercontent.com/assets/18304511/24103651/9b60da96-0d88-11e7-9dec-2b3ab6cf7eed.gif)

**Comment by meandavejustice** [comment]
The remove button in history was actually removing tracks from the queue instead, YIKES!

 just pushed a fix though, nice catch @SoftVision-CiprianMuresan

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest Min Vid with Queue functionality built on 3/28/2017.
