### ISSUE TITLE
Clicking the "x" button for the first item in the History section wrongly closes the player

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#676]
[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 3/17/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.
- Custom resolution is set. (width at least 500)

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any supported platform.
2. Send two videos/songs to the mini player and choose to play them. 
3. Click the "Open Queue" button and navigate to the "History" section.
4. Click the "x" button for the first item in the History section and observe the behavior.

[Expected result]:
- The item is removed and the player keeps playing.

[Actual result]:
- The item is not removed and the player is closed.

[Notes]:
- Attached a screen recording of the issue: 
![Uploading clicking the x button for the first item in the History section wrongly closes the player.gif…]()

**Comment by meandavejustice** [comment]
fixed with #674

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest Min Vid with Queue functionality built on 3/28/2017.
