### ISSUE TITLE
Sound can no longer be heard after clicking the "Next" button

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#678]
[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 3/17/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any supported platform.
2. Send a video/song to the mini player and choose to play it. 
3. Add a second video/song to Queue.
4. Click the "Next" button and observe the behavior.

[Expected result]:
- The next video/song in queue is played and audio can be heard.

[Actual result]:
- The next video/song in queue is played, but the audio can no longer be heard.

[Notes]:
- The issue is also reproducible if you click the 2nd item in the "Play Queue"
- If you let the player automatically go to the next item, either by fast forwarding the video/song or just waiting, the audio can be heard for the next item.
- Attached a screen recording of the issue:

**Comment by Softvision-VladBacia** [comment]
I've investigated a little further this issue and found out that it may be a Nightly issue. After doing a regression range I got this:
```
INFO: Narrowed inbound regression window from [aecbad80, 23cfb067] (3 revisions) to [06e12bb9, 23cfb067] (2 revisions) (~1 steps left)
INFO: Oh noes, no (more) inbound revisions :(
INFO: Last good revision: 06e12bb9737bfdb5df0a8282c82e871f7f525951
INFO: First bad revision: 23cfb067130f6225f9b63c752c349fd607e69c46
INFO: Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=06e12bb9737bfdb5df0a8282c82e871f7f525951&tochange=23cfb067130f6225f9b63c752c349fd607e69c46

INFO: Looks like the following bug has the  changes which introduced the regression:
https://bugzilla.mozilla.org/show_bug.cgi?id=1347402
```
and in bugzilla there is this issue regarding youtube sound issues: 
`https://bugzilla.mozilla.org/show_bug.cgi?id=1348432`

Leaving this as open until bugzilla issue 1348432 is fixed and we will test this scenario again to see if this is truly a Nightly issue or not. 

Thank you.

**Comment by meandavejustice** [comment]
@Softvision-VladBacia Good work digging into bugzilla!

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest Min Vid with Queue functionality built on 4/4/2017. 
Seems like it was a Nightly issue and not a Min Vid one.
