### ISSUE TITLE
Video won't load "Not embeddable"

### ISSUE THREAD

**Issue by rabimba** [meandavejustice/min-vid#683]
## Steps to Reproduce

- Open Firefox
- Goto youtube.com
- Open "https://www.youtube.com/watch?v=qFLhGq0060w"

## Screenshot

![image](https://cloud.githubusercontent.com/assets/776740/24125269/e3aa5f36-0d95-11e7-9027-daa827e82898.png)

## Firefox Version and OS

Version: 52.0
OS: Ubuntu 16.04 LTS

![image](https://cloud.githubusercontent.com/assets/776740/24125720/2c7c9cf4-0d98-11e7-967a-6031acf282b3.png)
![image](https://cloud.githubusercontent.com/assets/776740/24125737/3ea54c14-0d98-11e7-83f0-34bd55732e53.png)

**Comment by meandavejustice** [comment]
@rabimba Unfortunately there isn't anything we can do about this. Vevo hasn't allowed many of their videos to be embeddable. Gunna close this but feel free to reopen if you feel that I've misunderstood something

**Comment by rabimba** [comment]
Ok that is fine. So this will be by design for the plugin. Right? Else I was planning for a patch. But not sure how much legal that is(bypassing it)

**Comment by meandavejustice** [comment]
@rabimba Unfortunately we cannot bypass it in this addon, for legal reasons.

**Comment by rabimba** [comment]
I understand it.
Thanks!
