### ISSUE TITLE
Min Vid does not automatically skip videos/songs that cannot be played

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#684]
[Notes]: 
- I don't think these videos/songs should be skipped outright. If we detect an error we should set a timeout for that video/song and skip to the next. This way we also give the user a chance to see why the playback has stopped and hopefully help him understand that some videos/songs can't be played.
- The issue is also reproducible with un-embedable Vimeo and SoundCloud videos/songs.

[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 3/21/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.youtube.com.
2. Send a video to the mini player.
3. Add a VEVO video to Queue and then add another (working) video to the list.
4. Let the videos play out and observe the behavior.

[Expected result]:
- The VEVO video is skipped after a few seconds and the next item in queue starts playing.

[Actual result]:
- Playback stops when the VEVO video is played and an error message appears.

[Notes]:
- Attached a screen recording of the issue: [Link](https://drive.google.com/open?id=0B8ICzPJynbchWnZONFYtZG5BUjQ)

**Comment by meandavejustice** [comment]
Added a 3 second timeout for error views before forwarding to the next video

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest Min Vid with Queue functionality built on 3/28/2017.
