### ISSUE TITLE
History is wrongly deleted after a browser restart

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#689]
[Notes]:
- The name "History" leads the user to believe that the list will be kept even if the browser is restarted.
- We could consider a change in name, if we want to keep this behavior. Maybe "This session" would be more fitting.

[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 3/21/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to any supported platform and send a few videos to the mini player.
3. Click the "Next" playback button until the last item in the "Play Queue" is playing.
4. Restart the browser.
5. Navigate to any supported platform and send a video to the mini player.
6. Click the "Open Queue" button and go to the "History" section.
7. Observe the list.

[Expected result]:
- The History section is populated with items that I previously listened to.

[Actual result]:
- The list is empty. (ignoring the hardcoded album)

[Additional Notes]:
- Attached a screen recording of the issue: 
![history is deleted after a browser restart](https://cloud.githubusercontent.com/assets/18304511/24156905/9ad8d032-0e60-11e7-8f13-d900e307e36c.gif)

**Comment by Softvision-VladBacia** [comment]
This issue is reproducible with Min-Vid 1.0.10. Reopening and assigning a milestone.

**Comment by meandavejustice** [comment]
fixed in https://github.com/meandavejustice/min-vid/commit/1a65208fe68b84431dfec23285191d7bb11f9038

**Comment by Softvision-VladBacia** [comment]
This issue has been verified in 08/7/2017 with the build made from `sdk-to-webextension` branch and it is no longer reproducible.
