### ISSUE TITLE
Next button is covered up when viewing queue/history

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#693]
I'm finding myself wanting to skip ahead while looking at the track in the queue, this isn't possible with the current UI.

![2017-03-22--42-17-39-1920x1080_scrot](https://cloud.githubusercontent.com/assets/1844554/24222022/0bad01e0-0f27-11e7-86d1-c347da089442.png)

cc/ @youwenliang @johngruen

**Comment by youwenliang** [comment]
@meandavejustice 
If you click the next videos (video 2,3,4...) in the play queue it will play immediately and the first video will be pushed to History. I don't think you need the "next" button to skip ahead.

Or, we can have keyboard shortcuts to do that.

**Comment by meandavejustice** [comment]
@youwenliang that's a good point, and I've already hooked up keyboard shortcuts for that. closing
