### ISSUE TITLE
The last item from queue is truncated

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#695]
**[Affected versions]:**
-Firefox 52.0 and up
-Min-Vid with queue (built on 3/23/2017)

**[Affected Platforms]:**
-All Windows
-All Mac
-All Linux

**[Prerequisites]:**
-Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to any supported platform and send 4 or 5 videos/songs to the mini player playlist.
3. Go to "Play Queue" in Min-Vid.
4. Scroll down to the last item.

**[Expected result]:**
- The last item from Play Queue is fully visible.

**[Actual result]:**
- The bottom part from the last item from queue is truncated.

**[Notes]:**
- Attached a screen recording of the issue:
![last element from playlist is truncated](https://cloud.githubusercontent.com/assets/9248513/24250485/be8ff070-0fdf-11e7-92cb-2e03edaf1a9c.gif)

**Comment by meandavejustice** [comment]
changed default window size, no longer truncating

**Comment by Softvision-VladBacia** [comment]
The issue is no longer reproducible on the latest Min-Vid add-on with Queue functionality. (built on 3/28/2017).
