### ISSUE TITLE
"Do nothing" button is truncated on native resolution after sending a playlist to Min-Vid

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#697]
**[Affected versions]:**
-Firefox 52.0 and up
-Min-Vid with queue (built on 3/23/2017)

**[Affected Platforms]:**
-All Windows
-All Mac
-All Linux

**[Prerequisites]:**
-Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to any supported platform with videos/songs.
3. Send to the mini player a playlist.
4. Observe the Min-Vid UI.

**[Expected result]:**
- "Do nothing" button is fully visible. Buttons size and position should be scaled accordingly with the video player resolution.

**[Actual result]:**
- "Do nothing" button is truncated and barely visible.

**[Notes]:**
- Attached a screenshot of the issue:
![truncated](https://cloud.githubusercontent.com/assets/9248513/24254681/2cb9a012-0fec-11e7-8fc3-80a134dede7b.jpg)

**Comment by meandavejustice** [comment]
no longer truncating since changed defaul thet window size

**Comment by Softvision-VladBacia** [comment]
The issue is no longer reproducible on the latest Min-Vid add-on with Queue functionality. (built on 3/28/2017).
