### ISSUE TITLE
How and when should we invite users to use our viewer?

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#7]
Needs UX for sure. Two possible cases to consider:

1) User loads a page containing one or more video embed links for a supported video service.
Possible UX: display notification box with copy inviting user to right-click on an embedded video or video link to view it on screen.
Here's a [screenshot example](https://www.dropbox.com/s/hvtbp3n8inwl6so/Screen%20Shot%202016-05-11%20at%205.29.22%20PM.png?dl=0) and [MDN docs](https://mdn.io/Alerts_and_Notifications#Using_notification_box) for the notification box.

2) User loads a page on a supported video service's website.
Possible UX: notification box with copy informing user they can take the video with them as they surf other websites.
Note, however, that youtube already has a picture-in-picture mode. We might need to work around that.

**Comment by 6a68** [comment]
Updated title and description to emphasize the general UX problem. @johngruen any thoughts?

**Comment by 6a68** [comment]
What about a toolbar button that lights up when a previewable video is detected in the current page?

I'm not totally sure what would happen when the button is clicked--maybe show a list of videos on the current page? (Could be awkwardly long on r/videos)

**Comment by meandavejustice** [comment]
It seems that we have settled on Overlay Icons and context-menu for the time being. I'm going to pull this out of the MVP milestone

**Comment by meandavejustice** [comment]
Think we got this covered. Overlay icons and context menu. We can open a fresh issue once we see how users interact with the player after launch.
