### ISSUE TITLE
The "+" button from History section does not add the video/song to Queue in the last position

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#703]
[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 3/29/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.
- At least one item is in the History section.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any supported platform.
2. Send a video/song to the mini player and click the "Open Queue" button.
3. Click the "History" button and click the "+" button for one of the videos/songs.
4. Observe the behavior.

[Expected result]:
- The video/song is added to Queue in the last position.

[Actual result]:
- The video/song is added to Queue in the first position and playback starts.

[Notes]:
- Attached a screen recording of the issue:
![button from history section](https://cloud.githubusercontent.com/assets/18304511/24456538/fdf72e70-149b-11e7-83ee-3bba7a7f1102.gif)

**Comment by Softvision-VladBacia** [comment]
The issue is no longer reproducible on the latest Min Vid with Queue functionality built on 3/31/2017.
