### ISSUE TITLE
The volume icon appears in the player even if it isn't hovered

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#704]
[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 3/29/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any supported platform.
2. Send a video/song to the mini player and do not hover it.
3. Observe the bottom right corner of the player.

[Expected result]:
- The player controls are hidden if the player is not hovered.

[Actual result]:
- The volume icon is displayed.

[Notes]:
- The progress bar is also truncated.
- Attached a screen shot of the issue:
![volume icon](https://cloud.githubusercontent.com/assets/18304511/24457958/4d510640-14a0-11e7-938f-53de0b5b8b36.PNG)

**Comment by Softvision-VladBacia** [comment]
The issue is no longer reproducible on the latest Min Vid with Queue functionality built on 3/31/2017.
