### ISSUE TITLE
Incorrect timestamps appear for Live videos if they are played after a non-live video

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#708]
[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 3/30/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.youtube.com.
2. Send a non-live video to the player.
3. Send a Live video to the player with the "Play Now" option.
4. Hover the player and observe the timestamp.

[Expected result]:
- Instead of a timestamp the "LIVE" string is displayed.

[Actual result]:
- The timestamp from the previous video is displayed.

[Notes]:
- The issue is also reproducible if the live video is in queue and you use the "Next" button to play it.
- The issue is also reproducible if the live video is in History and you use the "Previous" button to play it.
- Attached a screen recording of the issue:
![timestamps appear for live videos if they are sent to the player after a non-live video](https://cloud.githubusercontent.com/assets/18304511/24501675/37d6a94c-1553-11e7-8343-ad4dcf583134.gif)

**Comment by Softvision-VladBacia** [comment]
The issue is no longer reproducible on the latest Min Vid with Queue functionality built on 3/31/2017.
