### ISSUE TITLE
Tooltips wrongly appear for the overlay buttons even if they are hidden

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#709]
[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 3/30/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any supported platform.
2. Mouse over a video thumbnail.
3. Hover the "Play Now" overlay option and keep the mouse there for 15 seconds.
4. Move the pointer down a bit, where the "Add to Queue" option was.
5. Hold the mouse there for a few seconds.

[Expected result]:
- The tooltips do not appear as long as the overlay is hidden.
or
- The overlay reappears when the mouse is moved.

[Actual result]:
- The tooltip appears even if the overlay is hidden.

[Notes]:
- Attached a screen recording of the issue:
![tooltips wrongly appear for the overlay buttons even if it is hidden](https://cloud.githubusercontent.com/assets/18304511/24503505/12725d42-155b-11e7-9579-8434fca30951.gif)

**Comment by meandavejustice** [comment]
The real issue here seems to be that the icons are hidden in the case that the animation has finished and the mouse is still over the icon.
