### ISSUE TITLE
All the Min Vid text elements are wrongly select-able with ctrl+A 

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#710]
[Notes]:
- Tooltips are also selected when doing this.
- The issue is also reproducible when a drag event is started in the player and moved horizontally to the right.
- A simple way to encounter this issue is to rapidly remove items from History and Play Queue.

[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 3/30/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any supported platform.
2. Send a video/song to the mini player and choose to play it.
3. Press CTRL+A and observe the behavior.

[Expected result]:
- No text elements are selected.

[Actual result]:
- All text elements are selected, including the ones from the tooltips.

[Additional notes]:
- Attached a screen recording of the issue:
![all text elements are select-able with ctrl a](https://cloud.githubusercontent.com/assets/18304511/24508525/58a80364-156c-11e7-8bce-6c668f7e6d03.gif)

**Comment by Softvision-VladBacia** [comment]
The issue is no longer reproducible on the latest Min Vid with Queue functionality built on 3/31/2017.

**Comment by Softvision-VladBacia** [comment]
The issue is no longer reproducible on the latest Min Vid with Queue functionality built on 3/31/2017.
