### ISSUE TITLE
Min-Vid player is blank (white), when clicking on "Play from History?" if only one video is sent to the player

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#711]
**[Affected versions]:**
-Firefox 52.0 and up
-Min-Vid 0.3.4-dev (built on 3/31/2017)

**[Affected Platforms]:**
-All Windows
-All Mac
-All Linux

**[Prerequisites]:**
-Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.
-Min-VId History and Queue are empty.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to any supported platform.
2. Send a video/song to the mini player and choose to play it.
3. Wait until the video/song finished playing.
5. Click on "Play from History?" button.

**[Expected result]:**
- The video that was previously played is replayed.

**[Actual result]:**
- Min-Vid player is white. There are no player buttons or anything.

**[Additional notes]:**
- In this case when the user has only one video sent to the player, the best scenario would be that the video will be replayed when "Play from History?" button is clicked.
- [Here](https://drive.google.com/open?id=0B6QogV2AJFKiT3RZcU15a29xYWs) is the screen recording of the issue.

**Comment by meandavejustice** [comment]
Went ahead and changed it so we no longer show the "play from history" link if there are no items in history.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest Min Vid with Queue functionality built on 4/4/2017.
