### ISSUE TITLE
The scroll bar is moved with mouse movements if it was clicked and the mouse was released outside the player

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#717]
[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 4/4/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.
- Multiple videos/songs are in Play Queue.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any supported platform.
2. Send a video/song to Min Vid and click the "Open Queue" button.
3. Click the scroll bar and release the mouse outside the player.
4. Move the mouse up and down the "Play Queue" and observe the behavior.

[Expected result]:
- Moving the mouse up and down the list has no effect on it.

[Actual result]:
- The list is scrolled up and down depending on the mouse movements.

[Notes]:
- Attached a screen recording of the issue:
![the scroll bar is moved with mouse movements](https://cloud.githubusercontent.com/assets/18304511/24660153/75f5cbc4-1957-11e7-8639-6501c71f71be.gif)

**Comment by meandavejustice** [comment]
This sounds like an upstream bug. Will update if I find anything in bugzilla

**Comment by SoftVision-CiprianMuresan** [comment]
@meandavejustice, you were right, it is an upstream bug.
Here's what I've found:

Last good revision: 4cbc57e29e25e8abe783b16915bd74325a040b02
First bad revision: d7518eef6b8924b4ddad6cdeeae4eed1c6129b26
Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=4cbc57e29e25e8abe783b16915bd74325a040b02&tochange=d7518eef6b8924b4ddad6cdeeae4eed1c6129b26

Looks like the following bug has the  changes which introduced the regression:
https://bugzilla.mozilla.org/show_bug.cgi?id=1324117

**Comment by meandavejustice** [comment]
Good detective work @SoftVision-CiprianMuresan !! Gunna close since it's upstream. We can still link to this issue/your comment if anyone else reports it.
