### ISSUE TITLE
"Track added to Queue" message does not appear when adding items from History

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#719]
[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 4/4/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.
- Multiple videos/songs are in History.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any supported platform.
2. Send a video/song to Min Vid and click the "Open Queue" button.
3. Go to the History section and click the "Plus" icon next to a video/song.
4. Click the "Close Queue" button and observe the player.

[Expected result]:
- "Track added to Queue" message appears in the player.

[Actual result]:
- No message appears.

[Notes]:
- The track is added, but there is no confirmation message.
- Attached a screen recording of the issue:
![track added to queue from history](https://cloud.githubusercontent.com/assets/18304511/24658460/6f90c220-1952-11e7-99b1-0f212b4d6693.gif)

**Comment by meandavejustice** [comment]
The intention for the "track added to queue" message was to only show it when the queue window is closed. We wanted a way for the user to know that their action worked when adding from the overlay icon or context menu, partially showing the message cutoff behind the queue message seems excessive and undesirable to me.

**Comment by Softvision-VladBacia** [comment]
Seems legit 👍
