### ISSUE TITLE
"Mute"/"Unmute" tooltips do not appear if the player is minimized

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#720]
[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 4/4/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any supported platform.
2. Send a video/song to Min Vid and minimize the player.
3. Hover the volume icon and observe the behavior.

[Expected result]:
- The "Mute" tooltip appears as the button is hovered.

[Actual result]:
- The "Mute"  tooltip does not appear.

[Notes]:
- If the volume is muted the "Unmute" tooltip does not appear while hovering the volume icon.
- Attached a screen recording of the issue:
![mute or unmute tooltips do not appear](https://cloud.githubusercontent.com/assets/18304511/24657916/c650885e-1950-11e7-8aad-c4c1294e63ee.gif)

**Comment by meandavejustice** [comment]
This was intentional, if the tooltip goes to the left it is cut off, if it goes to the right, it covers the volume bar.

**Comment by Softvision-VladBacia** [comment]
Ok, thank you for the answer @meandavejustice . This makes sense :sunny:
