### ISSUE TITLE
Clicking the progress bar under the player controls clicks that button instead of moving the progress

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#721]
[Notes]:
- If you hover the progress bar where there are no player controls, the cursor doesn't change from "hand" to "pointer".

[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 4/4/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any supported platform.
2. Send a video/song to Min Vid and minimize the player.
3. Hover the progress bar under one of the player controls.
4. Click that place and observe the behavior.

[Expected result]:
- The progress bar is moved to that place.

[Actual result]:
- The player control is clicked.

[Additional notes]:
- Attached a screen recording of the issue:
![progress bar while minimized](https://cloud.githubusercontent.com/assets/18304511/24657911/c26737ec-1950-11e7-8022-6e710df476ca.gif)

**Comment by meandavejustice** [comment]
I agree that the progress bar should be seekable when minimized, however I decided to disable it for the time being, since it is so much smaller when minimized, I thought it would be difficult to select it properly. I'm going to tag this as an enhancement and add it to the `post-queue-release` milestone.

**Comment by meandavejustice** [comment]
We're changing some of the layout for the minimized view, blocked by #723

**Comment by SoftVision-PaulOiegas** [comment]
Progress bar is now actionable and correctly seeks the video / song in minimized mode.
