### ISSUE TITLE
Volume slider is truncated while Min Vid is minimized

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#722]
[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 4/4/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any supported platform.
2. Send a video/song to Min Vid and minimize the player.
3. Hover the volume slider and observe the container.

[Expected result]:
- The volume container is correctly rendered.

[Actual result]:
- The volume container is truncated.

[Notes]:
- Attached a screen recording of the issue:
![volume slider is truncated while min vid is minimized](https://cloud.githubusercontent.com/assets/18304511/24656546/ace53bda-194b-11e7-933c-553d3c863190.gif)

**Comment by SoftVision-CiprianMuresan** [comment]
This looks good on Mac :
![minimized player on mac](https://cloud.githubusercontent.com/assets/18304511/25125061/391cc934-2436-11e7-8cdd-8df87b25c2cb.png)

And terrible on Windows: 
![minimized player on windows](https://cloud.githubusercontent.com/assets/18304511/25125070/4144e8e4-2436-11e7-9fe5-b458291375ba.png)

The volume slider is not centered in its container (on Windows).

**Comment by SoftVision-PaulOiegas** [comment]
The changes from #824 seem to have fixed this also.
