### ISSUE TITLE
There are no "Previous" and "Next" buttons while Min Vid is minimized 

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#723]
[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 4/4/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any supported platform.
2. Send a video/song to Min Vid and minimize the player.
3. Hover the minimized player and observe the control buttons. 

[Expected result]:
- All control buttons, except the "Open Queue" button, are displayed.

[Actual result]:
- The "Previous" and "Next" buttons are not displayed.

[Notes]:
- Attached a screen recording of the issue:
![no previous and next buttons while min vid is minimized](https://cloud.githubusercontent.com/assets/18304511/24656541/aa2953e0-194b-11e7-83a5-4dc5e6845d32.gif)

**Comment by meandavejustice** [comment]
cc/ @youwenliang

**Comment by youwenliang** [comment]
@meandavejustice I think it would be better if we redesign the minimized version and take #718 into consideration.
I'll make some mockups these days!

**Comment by meandavejustice** [comment]
@youwenliang sounds good :)

**Comment by youwenliang** [comment]
Just a quick mockup, would this be feasible?  I know you mentioned keeping the height 40px before but with all the control buttons it seems reasonable to double the height.

![minimized](https://cloud.githubusercontent.com/assets/8919308/25122923/45a34e3a-2459-11e7-9d61-c9546fda68fc.png)

**Comment by SoftVision-CiprianMuresan** [comment]
@meandavejustice @youwenliang
I'd like to ask two things about the new design for the minimized player:
1. Will the "Open Queue" button maximize the player and open the queue? Otherwise I cannot imagine what would be the use of it.

2. Would it be possible to have all the controls in a single row if a user sets a custom width (large enough so that all the buttons fit)?
If the default resolution is set or the custom width is not large enough we could show controls in two rows. And only if the custom width is large enough show them in two rows.

**Comment by youwenliang** [comment]
1. yes! 
2. I actually would rather keep it either one row all the time, or two rows all the time.

**Comment by SoftVision-PaulOiegas** [comment]
Buttons were added in the new minimized view with two rows design, but are inactive and wrongly positioned. See #801.
