### ISSUE TITLE
When clicking the "Play" button in "Play Queue" for YouTube/Vimeo videos while a SoundCloud song is playing, both audios are played simultaneously

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [meandavejustice/min-vid#732]
[Notes]:
- When this issue occurs the timestamp in the progressbar is fastforwarding.
- Clicking the "Pause" button from the player controls, pauses the both sound streams and video playback.
- Clicking inside the container, only the Youtube video and sound are paused, the sound from SoundCloud continues to play.

[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 4/10/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to YouTube.
2. Send a video to Min Vid.
3. Navigate to SoundCloud and send a song to Min-Vid("Play Now" option).
4. After the song starts playing click the "Open Queue" button.
5. Click the "Play" button for the YouTube video and observe the sound played.

[Expected result]:
- The corresponding sound for the YouTube video is played.

[Actual result]:
- The sound for the YouTube video is played along with the sound from the SoundCloud song.

[Additional Notes]:
- Attached a screen recording of the issue:
![minvid_soundcloud_issue_4](https://cloud.githubusercontent.com/assets/20083658/24868444/b84cb058-1e18-11e7-93c3-47f5b30fa789.gif)

**Comment by SoftVision-EmilPasca** [comment]
While investigating this issue further, I've found an extra scenario, which I think it has the same root cause:

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to YouTube.
2. Send a video to Min Vid("Play now" option).
3. Navigate to SoundCloud and add a song to Queue.
4. Click on the "Mute" button and then the "Next" button.
5. Observe the audio state.

[Expected result]:
- No sound is played as the audio "Mute" state is persisted.

[Actual result]:
- The sound of the "SoundCloud" song is played.

[Notes]:
- The "Unmute" button is still being present.
- The issue doesn't occure when playing a Vimeo video after a muted Youtube video or viceversa.
- Attached a screen recording of the issue:
![minvid_audio_mute_state](https://cloud.githubusercontent.com/assets/20083658/24917037/8f91615a-1ee4-11e7-89dd-22bc416894c7.gif)

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Min Vid version built on 4/18/2017.

**Comment by meandavejustice** [comment]
@SoftVision-EmilPasca muting should persist between tracks. If a user mutes the player we don't want to automatically unmute it for them

**Comment by SoftVision-PaulOiegas** [comment]
@meandavejustice I'm not sure that we fully understood the issue here Dave. Emil says that mute icon persists but the sound can be heard. I have just checked the behavior and he's right. 
You mute the YouTube video, but when you click next, the icon looks like the song is muted but I can hear the sound loud and clear...

**Comment by meandavejustice** [comment]
@SoftVision-PaulOiegas I apologize, I misread the issue. Thanks for reopening

**Comment by SoftVision-PaulOiegas** [comment]
Seems to be fixed now. 👍 Mute option correctly is kept for next videos / songs from queue.
