### ISSUE TITLE
"Add to queue" toast message too small

### ISSUE THREAD

**Issue by youwenliang** [meandavejustice/min-vid#735]
When a user clicks "+", the toast message display on the MinVid player is too small. The text size should be at least the same size as the tooltips.

Ideally, I propose that once a user clicks on the "+" icon, the icon should temporary change to a "✓" icon and turn back to "+" after a few seconds, so that there's also a visual feedback on the clicking area.

![001](https://cloud.githubusercontent.com/assets/8919308/24902080/a5f9627a-1edb-11e7-9483-4f3ec7092178.gif)

**Comment by SoftVision-PaulOiegas** [comment]
The "Track added to queue" message is now large enough in my opinion to be easily noticed. I also verified if the message is affected in some way when setting higher resolution for the player, but it remains the same.
