### ISSUE TITLE
No hover state on several icons

### ISSUE THREAD

**Issue by youwenliang** [meandavejustice/min-vid#736]
The "Play/Pause", "Previous/Next", and "Volume" icons should have a hover state that changes the transparency to 100% (White), just like the "close", "send to tab", "minimize" icons.

![002](https://cloud.githubusercontent.com/assets/8919308/24902244/23eaa9d2-1edc-11e7-9793-47a8b1af872d.gif)

**Comment by SoftVision-PaulOiegas** [comment]
Verified this using a custom build made from the repo today (04/26/2017) and now all the buttons have 100% white hover state.
