### ISSUE TITLE
exit video cleanly when playback finished

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#75]
maybe 2 buttons:
* replay
* close

**Comment by 6a68** [comment]
Reminder to add a metrics ping for when the video ends on its own, that was something mentioned in the original metrics doc

**Comment by johngruen** [comment]
![endcap 2x](https://cloud.githubusercontent.com/assets/3323249/17643194/288f8440-6130-11e6-82a8-a737ea269338.png)

close SVG: https://www.dropbox.com/s/s9bt16tu3w7hc65/close.svg?dl=0
replay SVG: https://www.dropbox.com/s/dyssruy8k2uj1kn/Rewatch.svg?dl=0
