### ISSUE TITLE
"send to queue" context menu option?

### ISSUE THREAD

**Issue by TonnesM** [meandavejustice/min-vid#754]
Today 1 new string landed for the Test Pilot website, containing the text "Create your own by clicking the '+' icon or choosing the 'send to queue' option from the context menu." I could not find a matching 'send to queue' option however, but instead, there was a string called "Send to mini player" (currently still in production) that seems to have been changed to "Add to queue" a few days ago.

Unless the 'send to queue' option referred to above was intended as a "general option to send/add the track to the queue" (hence using lowercase s perhaps), wouldn’t it be better to match it to use "Add to queue" instead, if intended?

**Comment by flodolo** [comment]
Thanks, this is indeed an issue in the Test Pilot website. I reported it to the developer, it should be fixed in the next hours.

**Comment by meandavejustice** [comment]
fixed in https://github.com/mozilla/testpilot/commit/03d531dc7cbe8416bf28215202f8b8682ab2b988 thanks @TonnesM and @flodolo
