### ISSUE TITLE
[Soundcloud] Visualization is zoomed in/out when scrolling in the player

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [meandavejustice/min-vid#763]
[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.6-dev (built on 4/18/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to SoundCloud and send a song to Min-Vid ("Play Now" option).
3. Hover the Min Vid player and scroll up and down (using the Mouse or trackpad).

[Expected result]:
- The "SoundCloud" visualization is not affected when scrolling in the player.

[Actual result]:
- The "SoundCloud" visualization is zoomed in/out when scrolling in the player.

[Notes]:
- Attached a screen recording of the issue:
![minvid_visualization_issue](https://cloud.githubusercontent.com/assets/20083658/25129865/8fc0a294-2448-11e7-9b9e-dccc083c63ba.gif)

**Comment by meandavejustice** [comment]
Sounds like a feature to me, do you foresee any issues with leaving this in?

**Comment by SoftVision-EmilPasca** [comment]
@meandavejustice, In my opinion this doesn't affect the user experience and most likely can be seen as a feature. 
However, I would suggest adding some limits, as you can observe in the screen recording added below, if the user scrolls to much up or down the visualization will not display anything or it might render the waves in a strange way.
![minvid_vizualisation_issue](https://cloud.githubusercontent.com/assets/20083658/25231524/d6d8dbd0-25e0-11e7-81fc-d6620a8743d5.gif)

**Comment by wresuolc** [comment]
We're dropping support for soundcloud and vimeo
