### ISSUE TITLE
Current video playback volume is wrongly increased if you add another video to queue from YouTube player

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [meandavejustice/min-vid#764]
[Affected versions]:
- Firefox v52.0.2 and up
- Min-Vid v0.3.6 (production)
- Min-Vid v0.3.6 (custom repo build)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on was previously installed on a clean profile from Test Pilot or custom repo build.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to https://www.youtube.com/ page and open several compatible videos in new tabs.
3. Focus each tab, make sure the volume is at 100% and pause each video.
4. Send first video from "Play now" overlay button and after reduce the volume to a low value.
5. While paying attention to current song volume, focus a different video tab and choose to "Add to queue".
6. Hover the mini player and observe the current video volume slider.

[Expected result]:
- The set volume for the first video sent is kept no matter how many songs are sent to queue.

[Actual result]:
- The volume of the current playing video is wrongly increased when sending a new video to queue from the YouTube player.

[Notes]:
- **On YouTube videos, the volume is first increased to 50%-60% and then randomly increases or decreases for next videos.**
- **This issue does not occurs if you send videos from other place than YouTube player.**
- This issue also occurs if you send videos from Vimeo, the only difference is that the volume increases to the next video volume value.
- This issue does not occur if you send SoundCloud songs.
- Attached a screen recording of the issue: https://goo.gl/NLrses.

**Comment by meandavejustice** [comment]
Thanks for reporting, moving into `post-queue-release` milestone

**Comment by SoftVision-PaulOiegas** [comment]
Both the volume issues seem to be fixed but now the currently playing song is wrongly paused when you send another video to queue. This wasn't happening before this fix.

**Comment by SoftVision-PaulOiegas** [comment]
SoundCloud has a different behavior for this, so I have logged a separate issue for it (#783).

**Comment by SoftVision-PaulOiegas** [comment]
@6a68 This seems to be correctly fixed now. But one thing bugs me and I want to know your opinion on this. 
Right now, the mini player volume is still overwritten if you send a video / song from web player with "Play Now" overlay button. Now this behavior seems ok since theoretically, you know what the player volume is before sending it to the mini player.  Was this a user request? Do we want to keep this logic ?  

Also, this behavior does not occur on SoundCloud songs.

**Comment by meandavejustice** [comment]
@SoftVision-PaulOiegas This comes from replicating the state of the youtube player. We can check with UX/product people and get their input here.

cc/ @johngruen @youwenliang
