### ISSUE TITLE
Playback stops if the next video in queue is a duplicate of the current playing one

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [meandavejustice/min-vid#766]
[Affected versions]:
- Firefox v52.0.2 and up
- Min-Vid v0.3.6 (production)
- Min-Vid v0.3.6 (custom repo build)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on was previously installed on a clean profile from Test Pilot or custom repo build.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to https://youtube.com page.
2. Hover one video from the page and choose the "Play now" option.
3. Hover again the same video and choose to add it again to queue from "+" button ("Add to queue" option).
4. Fast forward the first video almost at the end.
5. Wait for the first video to end and observe the player behavior.

[Expected result]:
- The next video in queue is played even if it's a duplicate.

[Actual result]:
- The next video in queue is not played if it's a duplicate.

[Notes]:
- This issue only occurs if the duplicate video is next in queue after the first one.
- Here is a screen recording of the issue: https://goo.gl/dT6swS.

**Comment by meandavejustice** [comment]
Thanks for reporting, moving into `post-queue-release` milestone

**Comment by meandavejustice** [comment]
filed upstream, https://github.com/CookPete/react-player/issues/182, trying to find a workaround in the meantime

**Comment by SoftVision-PaulOiegas** [comment]
The fix seems to be ok. Checked on YouTube, Vimeo and SoundCloud. 👍
