### ISSUE TITLE
[SoundCloud] Song playback restarted from 0, if you pause and unpause the song

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [meandavejustice/min-vid#771]
[Affected versions]:
- Firefox v53.0 and up
- Min-Vid v0.3.6 (production)
- Min-Vid v0.3.6 (custom repo build)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on was previously installed on a clean profile from Test Pilot or custom repo build.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to https://soundcloud.com page.
2. Open one of the suggested songs and click the "Play Now" overlay button from album art.
3. Click "Pause" and after "Play" in order to start the playback (issue #744).
4. After the playback is started, fast forward the video (eg: 1 minute).
5. Click again on the "Pause" button and after on "Play" button.
6. Observe the playback behavior.  

[Expected result]:
- Song playback is resumed from last position.

[Actual result]:
- Song playback is restarted from the beginning. 

[Notes]:
- I'm not entirely sure, but I managed to reproduce this a few times. If the song is stopped at a specific time (eg: after 10s) and you wait for a bit less than that value, the playback is continued from that value. But if the wait time is bigger than the elapsed time, it starts from 0 when hitting the "Play" button.
- Also, as a bonus, if you spam a bit the play pause button, the visualization gets stuck while playback continues (see at the end of the video).
- Here is a screen recording of the issue: https://goo.gl/XpJ7pj.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest version of Min Vid (built on 2017/14/08).
