### ISSUE TITLE
Overlay not removed and "Play / Pause" button must be clicked 3 times for video to restart after playback end

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [meandavejustice/min-vid#782]
**[Affected versions]:**
- Firefox v53.0 and up
- Min-Vid v0.3.6 (production)
- Min-Vid v0.3.6 (custom repo build)

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Latest Min-Vid add-on was previously installed on a clean profile from Test Pilot or custom repo build.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to https://youtube.com page.
2. Hover a video thumbnail and click on "Play Now" overlay button.
3. Fast forward the video or let it end, in order to have the "Replay / Close" overlay displayed.
4. Hover the player and observe the "Play / Pause" button state.
5. Click the "Play / Pause" button and observe the player behavior.
6. Click the "Play / Pause" button several times more.

**[Expected result]:**
- Step 4: The button passes from "Pause" to "Play" state after the video playback ends and the "Replay / Close" overlay is displayed. 
- Step 5: The button passes into "Pause" state, the overlay is removed and video playback starts again.
- Step 6: The button correctly passes into the opposite state each time is clicked and the video playback is correctly paused or played.

**[Actual result]:**
- Step 4: The button wrongly remains into  "Pause" state after the video playback ends and the "Replay / Close" overlay is displayed. 
- Step 5: The button wrongly passes into "Play" state, the playback is not restarted and the overlay is not removed.
- Step 6: A second click leaves the button in the same "Play" state, only the seek bar is restarted. A second click makes the video playback to restart, but the "Replay / Close" overlay is not removed. 

**[Notes]:**
- This issue also occurs in minimized mode where there is no "Replay" button, making this issue even easier to encounter.
- This issue also occurs for SoundCloud songs but you only need to click twice the "Play / Pause" button. But the overlay still remains displayed.
- This issue **does not** occurs for Vimeo videos. The overlay is also correctly removed when "Play" button is pressed.
- Here is a screen recording of the issue: https://goo.gl/rj30tQ.

**Comment by SoftVision-PaulOiegas** [comment]
@6a68 @meandavejustice The functionality and buttons issue was correctly fixed for both YouTube and SoundCloud. But now, fixing #626 became mandatory since every replay from overlay button or from "Play" button reproduces the issue behavior on YouTube. 

Also, if a song ends and the user clicks the "Replay" button  (or "Play"), shouldn't this generate a song occurrence in History list for each replay?

**Comment by meandavejustice** [comment]
>Also, if a song ends and the user clicks the "Replay" button (or "Play"), shouldn't this generate a song occurrence in History list for each replay?

@SoftVision-PaulOiegas I think you are right here. Would you mind logging an issue for that?

**Comment by SoftVision-PaulOiegas** [comment]
@meandavejustice Sure thing #798.

**Comment by meandavejustice** [comment]
>I've put a lot of hours into this issue so far and still haven't come up with a solid solution for this. After running git bisect I narrowed it down to this commit https://github.com/meandavejustice/min-vid/commit/bed7db6ea9fe7226105dfa3406470aa4533cada8

>If change functionality in `onEnded` to _not_ set `playing` to false, the stuttering goes away. I think I'm going to do that for now and reopen #782. This is really weird behavior as it only happens with YouTube embeds, which leads me to believe there may be an underlying issue with react-player. The issue is hard to describe so I'm going to have to try to reproduce it in a testcase in jsfiddle and try and get to the bottom of it with the author of react-player.

https://github.com/meandavejustice/min-vid/issues/836#issuecomment-300862691

**Comment by 6a68** [comment]
This seems fixed by #1202. Closing
