### ISSUE TITLE
MinVid used to work and videos no longer load

### ISSUE THREAD

**Issue by sunraerae** [meandavejustice/min-vid#786]
Firefox -- 53.0, up to date, Shockwave Flash 25.0
Early 2015 MacBook Pro -- 8 GB 1867 MHz DDR3

Min Video is my favorite add-on for Firefox & makes work much more bearable.  Unfortunately, it has stopped working.  Now, when I click the pop out video button, it no longer loads the video.  The video I'm playing in the browser does pause as expected, and the player pops out, but it loads indefinitely. I did not encounter this issue until you guys introduced the queue system. I was excited to add a video to my queue and when I clicked the plus, the player crashed and has not worked since.

I have tried uninstalling just MinVid several times, and uninstalling Test Pilot, and restarting my computer, to no avail.  Below is an screenshot where you can see what the MinVid client looks like indefinitely rather than starting my video.  On the left-hand side of the screen, I'm hovering over the browser video and you can see that the popout video / add to queue options still display.  If I click those again, the video pauses again, but nothing changes with the mini video to the right.

<img width="1280" alt="screen shot 2017-04-27 at 3 38 38 pm" src="https://cloud.githubusercontent.com/assets/28115306/25501230/024b0a84-2b60-11e7-9e02-4c36e5fc3700.png">

Overall, this is a great feature in progress.  The other issue I've noted is that the video will randomly not stay in the foreground; sometimes it does, sometimes it doesn't.  

Thanks!  Let me know if you have any questions or ideas for me to try.

**Comment by SoftVision-PaulOiegas** [comment]
Hi @sunraerae and thanks for your report!  I have tried your steps on a MacBook Pro late 2015 but I could not reproduce your issue. Let's see how we can debug this together:
1. Can you please tell me what version of Min Vid and Test Pilot you have in "about:addons" page? After you reach the page, double click on Min Vid from the list, and you'll have the version displayed on top of the page. Do the same for Test Pilot please.

2. Have you tried to install Min Vid on a new profile? Maybe something from your Firefox configuration or an add-on that you have beside Min Vid is causing this issue.
[Here is a tutorial](https://goo.gl/PNe90E) for creating new profile, in case you don't know how. Please follow step 6.
If Min Vid is working ok on the new profile, then it's something related to your profile that is causing this.

Regarding the second issue. We are aware of this one already. It is logged in #619. Please follow the thread there for other details.

**Comment by sunraerae** [comment]
@SoftVision-PaulOiegas I think we interacted over email, but the first issue is resolved.  I commented on #619.
