### ISSUE TITLE
do we want to allow users to popout into a separate window?

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#79]
(a separate browser window)

**Comment by pdehaan** [comment]
I think this is a very cool feature, although I think it's orphaning some audio streams (bug incoming).

**Comment by meandavejustice** [comment]
@pdehaan I'm talking about a separate browser window solely for the player. not the send-to-tab feature.

**Comment by meandavejustice** [comment]
We may get this as an option for free with @6a68 's current dragging work.
