### ISSUE TITLE
Test pilot midvid not working in ubuntu 17.04

### ISSUE THREAD

**Issue by rishavanand** [meandavejustice/min-vid#791]
![screenshot from 2017-05-01 23-58-20](https://cloud.githubusercontent.com/assets/11771528/25596225/c608520a-2ee5-11e7-8adf-36d1d5abb0f4.png)

Mid-vid doesn't work on my Ubuntu 17.04. It always shows "Something's gone wrong with the video. Try again later".

User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0
Build ID: 20170418122848

**Comment by SoftVision-CiprianMuresan** [comment]
Hi @rishavanand, thanks for the report. 
Does this happen only with VEVO videos? (those have been marked as un-embedable and can't be played in Min Vid. See #785, #683, #377, #432 and #362 for more details)
Or are you unable to play any videos at all?

**Comment by jxn** [comment]
For what it's worth, I'm on 17.04 (54.0a2 (2017-04-18) (64-bit), gnome, wayland) and min-vid is working for me, so it doesn't seem to be all of 17.04.  Let me know if I can help diagnose.
