### ISSUE TITLE
Addon will become unusable after minimizing and moving

### ISSUE THREAD

**Issue by jaysonsantos** [meandavejustice/min-vid#792]
To reproduce it click on minimize and move the mini bar to the top of the screen and then click on maximize, it will grow upwards and you won't be able to move it downwards (at least on windows 10 with firefox nightly 55.0a1 (2017-05-01) (64-bit))

**Comment by SoftVision-CiprianMuresan** [comment]
Hi @jaysonsantos, thanks for reporting this. However we are tracking two similar scenarios in #499. 
Could you add this one there as well?
