### ISSUE TITLE
Figure out metrics story

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#8]
How are we going to collect metrics? What are we trying to ask?

**Comment by 6a68** [comment]
The first question we want to answer is: Will people actually use this?

The simplest way to answer the question is to measure actual usage. How about we count the number of videos watched using the viewer?

The second question is: Will people like this and recommend it to their friends?

We can get an answer to the second question by looking at the install count and churn rate that Test Pilot already measures for us.

**Comment by wresuolc** [comment]
Once we determine this it should live in a metrics readme doc in the repository.  @johngruen will probably have good ideas

**Comment by wresuolc** [comment]
https://github.com/meandavejustice/min-vid/blob/master/docs/metrics.md
