### ISSUE TITLE
add comment to explain why 'addEventListener` is called with truthy fourth argument in data/controls.js

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#82]
> _"When called with a truthy forth argument, listeners can be triggered potentially unsafely by untrusted code. **This requires careful review.**"_
> 
> &mdash; via https://travis-ci.org/meandavejustice/min-vid/builds/145055793#L338-L339

The code in question seems to be in [./data/controls.js:19-21](https://github.com/meandavejustice/min-vid/blob/7d17a3f3e35e92694f8165ee4dc046223140bd4c/data/controls.js#L19-L21):

```js
window.addEventListener('message', function(ev) {
  self.port.emit('message', ev.detail);
}, false, true);
```

---

```
> addons-linter dist/addon.xpi -o text

Validation Summary:

errors          0
notices         0
warnings        1

WARNINGS:

Code                    Message                    Description                                        File               Line   Column
EVENT_LISTENER_FOURTH   addEventListener` called   When called with a truthy forth argument,          data/controls.js   19     1
                        with truthy fourth         listeners can be triggered potentially unsafely
                        argument.                  by untrusted code. This requires careful review.
```

**Comment by meandavejustice** [comment]
@pdehaan this is on purpose to allow events pass from the `default.html` dom to the injected content script `data/controls.js`. I thought I had this documented in a comment. I'll update the title of this bug to add a comment with context to that snippet.
