### ISSUE TITLE
The "Add playlist" overlay is not entirely visible when displayed on minimized player

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#831]
[Affected versions]:
- Firefox v53.0.2 and up
- Min-Vid v. 0.3.6 (custom repo build)

[Affected Platforms]:
- All Windows
- All Linux
- All Mac OS

[Prerequisites]:
- Latest Min-Vid add-on was previously installed on a clean profile from custom repo build.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to any supported platform with videos.
3. Send a video to the player.
4. Minimize the player.
5. Send a playlist to the player.
6. Observe Min Vid's changes of the UI.

[Expected result]:
- The following items are reachable and correctly displayed:
"What would you like to do?"
"Add [first song from the playlist]"
"Add [the entire playlist]"
"Do nothing" button.

[Actual result]:
- "What would you like to do?" and "Do nothing" button are not visible nor reachable.

[Notes]
- This is also reproducible with the Test Pilot Min Vid version: https://goo.gl/Fesfv0
- Please see the screen cast attached:

![nimimize](https://cloud.githubusercontent.com/assets/26000308/25851702/7570ed08-34cf-11e7-9d33-00758f4de76d.gif)

**Comment by meandavejustice** [comment]
We should pop into maximized mode for this case, thanks for reporting @SoftVision-CarmenFat

**Comment by SoftVision-CarmenFat** [comment]
This issue is no longer reproducible on the latest Min-Vid version (built on 5/12/2017).
