### ISSUE TITLE
YouTube and Vimeo videos can be / are played together with SoundCloud songs, if the songs are sent in "Replay / Close" overlay

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [meandavejustice/min-vid#856]
**[Affected versions]:**
- Firefox v53.0 and up
- Min-Vid v0.3.6 (custom repo build)

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Latest Min-Vid add-on was previously installed on a clean profile from custom repo build.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to https://youtube.com or https;//vimeo.com  page.
2. Hover a video thumbnail and click the overlay "Play Now" button.
3. Fast forward the video almost at the end and wait for the "Replay /Close" overlay to appear.
4. Navigate to https://soundcloud.com and click on one of the suggested songs.
5. Hover it's album art and click the "Play Now" button.
6. Fast forward the song, then the previously played video.
7. After the "Replay / Close" overlay is re-displayed, click the "Replay" button and observe the behavior. 

**[Expected result]:**
- The SoundCloud song is replayed (only after the fix for #798 will land). 

**[Actual result]:**
- Vimeo: Both the SoundCloud song and Vimeo video are replayed simultaneously.
- YouTube: The SoundCloud sound is replayed but the video can be too. The player displays the video thumbnail with "Play" option.

**[Notes]:**
- The interesting part is that the video appears in queue but the song is only displayed in history even if it's replayed.
- The "Replay / Close" overlay is again displayed if the song or video ends before the other.
- This issue is related to #798 since the newly added song is inserted in queue beside the last played video that wasn't moved to history after it played.
- Here is a screen recording of the issue: https://goo.gl/0T31So (sound from headphones + mike).

**Comment by wresuolc** [comment]
We're dropping support for soundcloud and vimeo
