### ISSUE TITLE
Reattaching to original video in jwplayer

### ISSUE THREAD

**Issue by sivapvarma** [meandavejustice/min-vid#860]
Currently the video opens a new stream and plays from start. Opera does a great job with the pop-out video player - http://blogs.opera.com/desktop/2016/04/opera-beta-update-video-pop/

**Comment by meandavejustice** [comment]
@sivapvarma Can you provide a link to the video you were seeing this behavior on? I can figure out a solution quickest if I have a direct example.

**Comment by sivapvarma** [comment]
Actually I noticed just now that, even on youtube, the only option to go back to the browser from the player is to open the video in a new tab. Any youtube video can be an example.

**Comment by meandavejustice** [comment]
@sivapvarma ahh I see what you are saying now. We actually have an issue for that here #369 if you wanna add anything to it. closing now as duplicate
