### ISSUE TITLE
Add eslint-plugin-mozilla?

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#864]
In https://github.com/mozilla-services/screenshots/pull/2700 @Standard8 added the eslint-plugin-mozilla plugin so we could easily merge into moz-central (ref: https://github.com/mozilla-services/screenshots/issues/2365).

Not sure if we want to do something similar here, or if having matching code is important to us.

**Comment by meandavejustice** [comment]
@pdehaan I'd be happy to integrate the mozilla recommended plugin. Wanna open a pr?

**Comment by pdehaan** [comment]
@meandavejustice See #865 PR. Most were auto fixes via `eslint --fix`, but I had to hand tweak the nested terneries, which eslint-plugin-mozilla doesn't seem to like. I think I demoted a few other errors to warnings, so you may want to confirm the .eslintrc.yml file and the Travis warning logs.
