### ISSUE TITLE
Incompatible with 'media.autoplay.enabled' set to true?

### ISSUE THREAD

**Issue by teranex** [meandavejustice/min-vid#877]
I'm using Min Vid version 0.3.7 on Firefox 53.0.2 (64-bit) on Xubuntu 16.10.

I couldn't get any video to play inside the Min Vid window. After pausing the youtube time would say "NaN Invalid Time / 02:45" (in case of a 2:45 minute video).
After I reset the option 'media.autoplay.enabled' back to the default value (false), the problem was solved. So it seems Min Vid doesn't play nice with 'media.autoplay.enabled' set to `true`

**Comment by SoftVision-CarmenFat** [comment]
Hi and thanks for your report. 

I tried to reproduce the issue you described by following the steps to reproduce provided, using Ubuntu 16.04 LTS x64 and Windows 10 x64. 

These are my results: 
- having the "media.autoplay.enabled" pref set with the default "true" value (in my case) and sending a Youtube video to the player with "Play now" button works correctly and no error is displayed when the video is paused; 
- after changing the pref's value to "false" and sending a Youtube video to the player with "Play now" button then pausing it, displays the following error: "NaN Invalid Date / < playback time >".

Attached a screen recording of the issue: https://goo.gl/ROmqmC

**Comment by wolfblake** [comment]
I just installed this test pilot extension today and when I click the min-vid button, I get the little pop-out window that always says "Loading video from youtube.com" I have media.autoplay.enabled set to true. Is there anything else I am missing?

**Comment by SoftVision-CarmenFat** [comment]
Hi @wolfblake,

I also installed Min Vid through Test Pilot website, but the videos were correctly sent and played in the mini player, without any loading issues. Must mention that the "media.autoplay.enabled" pref was set to "true" by default and this was tested on the latest Firefox release v.54.0.1 using Ubuntu 16.04 x64. 

Can you please set the pref value to "false" and try to reproduce the issue this way?
Also, can you provide information about your OS and Firefox version?

Thanks!

**Comment by wolfblake** [comment]
Thanks for getting back to me @SoftVision-CarmenFat,
Whether I have "media.autoplay.enabled" set to true or false the mini player says "Something's gone wrong with this video. Try again later" I have tried multiple videos after changing the config setting, but nothing is working.

I currently using Firefox 56.0a1 (2017-07-05) (64-bit) on Windows 10 Pro (build 16232)

**Comment by SoftVision-CiprianMuresan** [comment]
@wolfblake, could you post a few links of the videos that are not working for you?

**Comment by wolfblake** [comment]
sure @SoftVision-CiprianMuresan 
https://www.youtube.com/watch?v=4AAuGcDt1B4
https://www.youtube.com/watch?v=K0a9a8PUPrA
https://www.youtube.com/watch?v=X-bJLGqRTeM

**Comment by meandavejustice** [comment]
Did some digging, and this is a bug in firefox. Here is a link to the lengthy discussion https://bugzilla.mozilla.org/show_bug.cgi?id=1382574

Closing for now. I hope we can get this autoplay blocking working right in the near future.
