### ISSUE TITLE
Poor control contrast when viewing videos with light backgrounds

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#88]
```sh
$ git rev-parse HEAD # bc4abd73a0f2cf089c147b9cfa0dbbe0d8824430
```

---

Semi-related to #85, but noticed this edge case in #87 screenshot.

### Steps to reproduce:
1. Build and install add-on locally.
1. Navigate to https://www.reddit.com/r/videos and find a video from "(youtube.com)".
1. Right-click the link and select "Send to mini-player" from context menu.  I tested using https://www.youtube.com/watch?v=yceGT6lrn1Y
1. Play the video and start watching.
1. Regularly move your mouse around to show the video controls.

### Actual results:
In places where the video background is white, the background vs controls contrast is poor. We may want to think about having a black background behind all the controls which give a bit more contrast.

![_r_videos](https://cloud.githubusercontent.com/assets/557895/16960564/dc2f8a68-4d9e-11e6-8c84-90072651cc78.png)

**Comment by meandavejustice** [comment]
see also #71
