### ISSUE TITLE
If a YouTube/Vimeo video is sent to the Player with "Play Now" while a SoundCloud song is playing, the SoundCloud song continues playing

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#882]
[Affected versions]:
- Firefox 53.0.3 and up
- Min-Vid 0.3.7-dev (built on 5/30/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.soundcloud.com.
2. Send a song to Min Vid with the "Play Now" option.
3. Navigate to YouTube and send a Video to the player with the "Play Now" option.
4. Hover and observe the Player.

[Expected result]:
- The YouTube video starts playing.

[Actual result]:
- The SoundCloud song is still playing (audio only), but the YouTube video stream starts playback (no audio) and the progress bar fast forwards through the video.

[Notes]:
- The issue is also reproducible with Vimeo videos, but in this case both audio streams can be heard and the progress bar is not fast forwarded.
- Attached a screen recording of the issue:
![youtube after soundcloud](https://cloud.githubusercontent.com/assets/18304511/26581725/a96409ec-4546-11e7-85d4-debfe9d18d8a.gif)

**Comment by meandavejustice** [comment]
fixed in #875

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest version of Min Vid (built on 2017/14/08).
