### ISSUE TITLE
[SoundCloud] Visualizations stutter if the Play Queue/History is open and there are more than 10 items in Queue/History 

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#883]
[Affected versions]:
- Firefox 53.0.3 and up
- Min-Vid 0.3.7-dev (built on 5/30/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on was previously installed on a clean profile.
- Play Queue and History have more than 10 items in them.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.soundcloud.com.
2. Send a song to Min Vid with the "Play Now" option.
3. Click the "Open Queue" button and observe the visualization in the background.

[Expected result]:
- The visualization playback is smooth.

[Actual result]:
- The visualization playback stutters.

[Notes]:
- The issue is also reproducible while the History section is opened and it also has more than 10 items.
- Attached a screen recording of the issue:
![soundcloud visualization stutter](https://cloud.githubusercontent.com/assets/18304511/26584543/cfd80d16-4551-11e7-8455-e8c5b8440ed2.gif)

**Comment by wresuolc** [comment]
We're dropping support for soundcloud and vimeo
