### ISSUE TITLE
Tooltips are prefixed with tooltip_...

### ISSUE THREAD

**Issue by Synj24** [meandavejustice/min-vid#897]
[Affected version]
- FF Developer Edition 55.0
- Min-Vid 0.3.8 (Last Updated 08/06/17

[Affected Platform]
- Windows 7

[Prerequisites]
- locale is [en-gb] (not sure if this effects it)

[Steps to reproduce]
1. Open browser
2. Send Playlist to Min Vid with "Play Now"
3. Hover over buttons

[result]
- tool tips are prefixed with _tooltip__ 
![image](https://user-images.githubusercontent.com/13753370/27289520-208887a8-5502-11e7-86fa-53500c91ea3c.png)

[Notes]
- Issue persists after closing and re opening Min Vid
- could be a localisation problem ? ¯\\\_(ツ)\_/¯ I'm using [en-gb] and i can only see a [en-us]
- I also thought I saw the loading message when a video is sent to Min Vid displaying incorrectly as well

**Comment by meandavejustice** [comment]
cc/ @flodolo

**Comment by flodolo** [comment]
It's working fine here (Italian), and what you're seeing it's actually the string identifier
https://github.com/meandavejustice/min-vid/blob/master/locales/en-US/addon.properties#L6

I'm not exactly sure why it wouldn't fall back to en-US, given that en-GB is not available as a localization.

**Comment by meandavejustice** [comment]
@flodolo we _do_ have german it's just under `de`. https://github.com/meandavejustice/min-vid/blob/master/locales/de/addon.properties

**Comment by flodolo** [comment]
> we do have german it's just under de

Why are we talking about German?

**Comment by meandavejustice** [comment]
@flodolo Hmm, yeah looks like the fallback isn't working. I'll dig into this

**Comment by meandavejustice** [comment]
No longer seeing this issue after changing my language to en-gb, restarting. 

This is on nightly running linux
