### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#9]
figure out privacy policy and add to repo

**Comment by wresuolc** [comment]
@ckprice owns the legal parts, but I can't seem to assign this to him

**Comment by meandavejustice** [comment]
@wresuolc I will add him as a collaborator

**Comment by meandavejustice** [comment]
@wresuolc Just added him as a collaborator

**Comment by meandavejustice** [comment]
@ckprice Do you need anything from me for this?

**Comment by ckprice** [comment]
@meandavejustice @clouserw is this document final? https://github.com/meandavejustice/min-vid/blob/master/docs/metrics.md

**Comment by meandavejustice** [comment]
@ckprice Metrics.md should be final. Do you need anything else from us on this?

**Comment by wresuolc** [comment]
Draft is in review

**Comment by wresuolc** [comment]
This is finalized and approved.  Thanks everyone.  It'll appear in the left-side column in the Test Pilot listing.
