### ISSUE TITLE
[SoundCloud] Min-Vid throws error when trying to play a playlist from SoundCloud

### ISSUE THREAD

**Issue by Synj24** [meandavejustice/min-vid#900]
[Affected versions]:

- FF Developer Edition 55.0b3
- Min-Vid 0.3.8 (Last Updated 08/06/17

[Affected Platforms]:

- Windows 7

[Steps to reproduce]:

- Navigate to soundcloud and find a playlist, [such as this one.](https://soundcloud.com/snaketownrecords/sets/lovepark-21-12-ep)
- Send the playlist to Min-Vid using the _Play Now_ icon.
![image](https://user-images.githubusercontent.com/13753370/27442835-411e8de6-5769-11e7-87d6-99fa3a462fee.png)

[Expected result]:
- Min-Vid plays the playlist or shows a dialog as it does with YouTube playlists:
![image](https://user-images.githubusercontent.com/13753370/27443235-4fa4109c-576a-11e7-86d8-820775afc09d.png)

[Actual result]:
- Min-Vid throws _error_sc_not_track_ with an error link to the [URL](https://soundcloud.com/snaketownrecords/sets/lovepark-21-12-ep) of the playlist on SoundCloud
![image](https://user-images.githubusercontent.com/13753370/27442990-b5908440-5769-11e7-980f-8d04c7929f08.png)

[Notes]:
- Apologies if this feature has simply not been added yet.
- Not 100% sure but i think the problem lies in [lib/get-soundcloud-url.js](https://github.com/meandavejustice/min-vid/blob/bd2d991e84f088cb7dd2ee5e03a090f45f87d3da/lib/get-soundcloud-url.js#L26) not referencing the JSON kind [playlist](https://developers.soundcloud.com/docs/api/reference#playlists) from the api?

**Comment by SoftVision-PaulOiegas** [comment]
Hi @Synj24 and thanks for the report. Yes, we (QA) were aware of this issue and I think this functionality was not yet implemented. Here is a PR that looks like to be related #875.

**Comment by wresuolc** [comment]
We're dropping support for soundcloud and vimeo
