### ISSUE TITLE
min-vid not working in youtube beta

### ISSUE THREAD

**Issue by ghaspias** [meandavejustice/min-vid#917]
If using the beta (https://www.youtube.com/new) the overlay on the video thumbnails does not show up when hovering, neither does the min-vid section in the pop-up menu (when right-clicked). It still does appear on the main video element. Switching back to classic youtube restores the functionality.

**Comment by Softvision-VladBacia** [comment]
@ghaspias , thank you for reporting this.

Unfortunately this issue is a dupe of #521 .
