### ISSUE TITLE
Closing any window closes the minvid player

### ISSUE THREAD

**Issue by 6a68** [meandavejustice/min-vid#925]
1. open minvid player in SDK branch
2. open the browser console
3. close the browser console
4. minvid player also closes

observed on Mac

**Comment by 6a68** [comment]
Also happens if you close a regular browser window in step 2 of description

**Comment by meandavejustice** [comment]
Not seeing this in dev, may be specific to nightly. Unfortunately I cannot test that right now, since I can't load the addon in nightly today :(
