### ISSUE TITLE
MinVid not working anymore in Firefox Nightly 56.0a1

### ISSUE THREAD

**Issue by AgentSteel** [meandavejustice/min-vid#926]
It has been a few nightly builds (roughly one week of nightlies, so since 2017-07-21 maybe)  MinVid does not appear anymore in youtube and vimeo.

Using Nightly (2017-07-28) (64-bit) right now.

No MinVid icon showing in video thumbnails nor when playing a video.

Anybody can confirm the same?

**Comment by Softvision-VladBacia** [comment]
@AgentSteel , I've installed Min-Vid from Test Pilot and everything works fine. I am on Windows 8.1 x64 using Nightly 64-bit Build ID: 20170728100358. 

Please provide more details regarding this issue::
- OS
- are you using www.youtube.com new UI or the old one?
- what version of Min-Vid do you have installed

**Comment by AgentSteel** [comment]
Here is my setup:

- Debian Buster (testing) 64bit
- youtube.com old UI
- MinVid was the 14th of July build

Today I did the following:

- completely delete old nightly installation, download and use nightly build 56.0a1 (2017-07-30) (64-bit)
- start nightly with a completely new, fresh profile with no addons
- go to https://testpilot.firefox.com/experiments/min-vid/ and click on install button
- TestPilot installs fine

But MinVid does not install, button stuck on "installing..." forever. Even if I restart Nightly and try again.

So unable to install MinVid right now!

**Comment by Softvision-VladBacia** [comment]
@AgentSteel do you have any Antivirus or a Firewall installed on the system ? or other blocking rules regarding https protocol?

**Comment by AgentSteel** [comment]
It's Linux so no antivirus. No firewall enabled.

I did test with latest Firefox ESR 52.2.1 and MinVid installs and works fine.

So it must be Nightly-related. But it changes so much and so fast I guess it's hard to keep up!

**Comment by SoftVision-PaulOiegas** [comment]
It seems that this is a general breakage that occurred in Nightly for the whole Test Pilot platform. After Vlad did some testing on your issue, he figured this out and logged https://github.com/mozilla/testpilot/issues/2689 on the Test Pilot repository. You can follow the progress there.

Thanks for your report and please bear with us until this gets fixed.
