### ISSUE TITLE
Default height and width are now the minimum

### ISSUE THREAD

**Issue by marcusbrothers** [meandavejustice/min-vid#932]
In the latest update, code was added to the index.js script making the default values the minimum values that can be used to resize the window. Please remove this constraint as I like to have my Min Vid smaller (180x320) than the minimum allowed (260x400). I have to temporarily use my own edited version of the add-on in the mean time.

**Comment by meandavejustice** [comment]
fixed in https://github.com/meandavejustice/min-vid/commit/a6e7ff69536a1494f37fa07577f16ceea75739ff
