### ISSUE TITLE
"NaN:Invalid Date" is displayed instead of the elapsed time after changing video position while it is paused

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#935]
[Affected versions]:
- Firefox 53.0.3 and up
- Min-Vid 1.0.10

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a supported platform.
2. Send a video to the Min Vid player with the Play Now option.
3. Pause the video.
4. Click at random on the video progress bar.
5. Move the mouse cursor outside the Min-Vid window.
6. Move the mouse cursor in the Min-Vid window.

[Expected result]:
- Video position is correctly displayed at the custom setting.

[Actual result]:
- NaN:Invalid Date is displayed instead of the elapsed time. 

[Notes]:
- Attached a screen recording of the issue:

![elapsed time](https://user-images.githubusercontent.com/9248513/28874922-72bb4b52-779c-11e7-92a8-881df33732e4.gif)

**Comment by meandavejustice** [comment]
Moving this out of the sdk milestone, Definitely an edgecase and I suspect this has been an issue prior since none of this code has been touched.

**Comment by 6a68** [comment]
Can't repro this bug using STR, closing.
