### ISSUE TITLE
Min Vid icon and description are not displayed on "about:addons" page

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#938]
Affected versions]:
- Firefox 54.0.1 and up
- Min-Vid 1.0.10

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on (1.0.10) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate about:addons page.
2. Click on "Extensions" from the left side of the screen.
3. Observe Min Vid's elements.

[Expected result]:
- Min Vid's specific icon and description are displayed.

[Actual result]:
- There is no text description nor the specific icon of Min Vid.

[Notes]:
- Attached a screenshot of the issue:
![icon and description](https://user-images.githubusercontent.com/26000308/28878369-c4783d14-77a7-11e7-9871-595a182e9d54.png)

**Comment by meandavejustice** [comment]
fixed in https://github.com/meandavejustice/min-vid/commit/d9ff5419c774d7aca79e3ba447194d3bdb67a09d

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible on the latest master version (built on 7/8/2017).
