### ISSUE TITLE
"This is DUMB" message is displayed instead of "Loading video/audio from <platform>"

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#939]
Affected versions]:
- Firefox 54.0.1 and up
- Min-Vid 1.0.10

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on (1.0.10) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate one of the supported platforms (e.g www.youtube.com).
2. Send a video to the Min Vid player with the Play Now option.
3. Observe the message displayed just before the video starts playing. 

[Expected result]:
- "Loading video from youtube.com" message is displayed.

[Actual result]:
- "This is DUMB "message is displayed.

[Notes]:
- This happens every time the player is opened using "Play now" or "Add to queue", with or without videos in queue.
- Attached a screen cast of the issue:

![this is dumb](https://user-images.githubusercontent.com/26000308/28880649-5cebe018-77ae-11e7-91c9-abe1f933f48d.gif)

**Comment by meandavejustice** [comment]
fixed in https://github.com/meandavejustice/min-vid/commit/27c5e040748034f63ad75a1fd267eb897f86cd58

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible on the latest master version (built on 7/8/2017).
