### ISSUE TITLE
Cannot play videos from Vimeo channels

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#943]
[Affected versions]:
- Firefox 53.0.3 and up
- Min-Vid 1.0.10

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to https://vimeo.com/channels/staffpicks .
2. Send a video to the Min Vid player with the Play Now option.

[Expected result]:
- Video starts playing without issues.

[Actual result]:
- Videos from Vimeo cannot be played. "Something's gone wrong ..." error is displayed in the vide player.

[Notes]:
- If the same video is displayed on the homepage and it is sent to the mini player then the video will play.
- Attached a screen recording of the issue:

![vimeo videos cannot be played](https://user-images.githubusercontent.com/9248513/28924950-1354ef6c-786c-11e7-9e7d-fa4927d7be60.gif)

**Comment by meandavejustice** [comment]
@Softvision-VladBacia Thanks for reporting, I've moved this into the [vimeo-integration-cleanup](https://github.com/meandavejustice/min-vid/milestone/5) milestone.

**Comment by wresuolc** [comment]
We're dropping support for soundcloud and vimeo
