### ISSUE TITLE
"Now Playing" marker from the Play Queue is not displayed 

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#944]
[Affected versions]:
- Firefox 54.0.1 and up
- Min-Vid 1.0.10

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on (1.0.10) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to one of the supported platforms (e.g www.youtube.com).
2. Send a video to the Min Vid player with the "Play Now" option.
3. Click the "Open Queue" button.
4. Observe the marker that indicates that the video is currently playing.

[Expected result]:
- "Now Playing" marker (blue arrow pointing right) is displayed on the left side of the item.

[Actual result]:
- "Now Playing" marker (blue arrow pointing right) is not displayed on the left side of the item.

[Notes]:
- Attached a screen cast of the issue:

![now playing button](https://user-images.githubusercontent.com/26000308/28925481-b41e8948-786d-11e7-876c-9c535eaeac5b.gif)

**Comment by meandavejustice** [comment]
fixed in https://github.com/meandavejustice/min-vid/commit/589ece225ba3b1e0c777acddc6ac30c50f496ebb

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible on the latest master version (built on 7/8/2017).
