### ISSUE TITLE
Min Vid player resolution is wrong

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#945]
[Affected versions]:
- Firefox 54.0.1 and up
- Min-Vid 1.0.10

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on (1.0.10) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to one of the supported platforms (e.g www.youtube.com).
2. Send a video to the Min Vid player.
3. Observe player's resolution. 

[Expected result]:
- Default resolution is 260x400.

[Actual result]:
- Current resolution is 349x279.

[Notes]:
- Attached a screenshot of the issue:

![resolution](https://user-images.githubusercontent.com/26000308/28928716-a24c2604-7876-11e7-831e-dc0b4d62ebe6.png)

**Comment by meandavejustice** [comment]
Should have been fixed in https://github.com/meandavejustice/min-vid/commit/a5011ab2071492f98a4d1a0e9b2546c0be33e4cf looks like this is fixed on my platform (linux) feel free to reopen if you continue to see this issue.

**Comment by SoftVision-CarmenFat** [comment]
This issue was verified with latest Min-Vid v 1.0.10 from replace-sdk branch and it is no longer reproducible. The default resolution is now the correct one: 260x400.
