### ISSUE TITLE
"Add to Queue" marker from the player History is not displayed

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#946]
[Affected versions]:
- Firefox 54.0.1 and up
- Min-Vid 1.0.10

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on (1.0.10) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to one of the supported platforms (e.g www.youtube.com).
2. Send multiple videos to the Min Vid player with the "Play Now" option.
3. Click "Next" button in order to add items to player History.
4. Click on "Open Queue" button and go to "History".
5. Hover items from History.

[Expected result]:
- "Add to Queue" marker (white +) is displayed on the left side of the item.

[Actual result]:
- "Add to Queue" marker (white +) is missing.

[Notes]:
- Attached a screen cast of the issue:

![add to queue is missing](https://user-images.githubusercontent.com/9248513/28930205-e5b6d110-787a-11e7-9259-db60e7487e5b.gif)

**Comment by meandavejustice** [comment]
fixed in https://github.com/meandavejustice/min-vid/commit/589ece225ba3b1e0c777acddc6ac30c50f496ebb
