### ISSUE TITLE
Vimeo videos are wrongly scaled on Min Vid player

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#947]
[Affected versions]:
- Firefox 54.0.1 and up
- Min-Vid 1.0.10

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on (1.0.10) was previously installed on a clean profile.
- Play queue is empty.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.vimeo.com
2. Send a video to the Min Vid player (e.g. https://vimeo.com/81268438).
3. Pay attention to how the video frames are scaled inside de player.

[Expected result]:
- Video images are properly scaled and completely visible.

[Actual result]:
- The right part of the video is not scaled correctly and seems to be "cut".

[Notes]:
- If a Youtube video was previously sent to the Player (properly scaled), the Vimeo video will also scale correctly.
- If a Vimeo video or a SoundCloud audio was previously sent to the Player (wrongly scaled), the Vimeo video will also wrongly scale.
- Attached a screen cast of the issue:

![scaled issue](https://user-images.githubusercontent.com/26000308/28931069-91314ce4-787d-11e7-87c2-42586f880852.gif)

- Please see the attached screenshot of the issue for a better understanding:

![scale](https://user-images.githubusercontent.com/26000308/28931101-adde65a2-787d-11e7-98b6-c64c154d2f59.png)

**Comment by meandavejustice** [comment]
@SoftVision-CarmenFat It looks like this is actually the way the video was created. With the black frame around the animation. Feel free to reopen if you find another example

**Comment by SoftVision-CarmenFat** [comment]
Hi Dave,

Maybe I wasn't too clear when describing this issue, but I will try to explain better now:
- The issue with the Vimeo videos is that a part of the **right** side is not displayed when playing them with the Min Vid player;
- With the right side of the video missing, the impression the user gets is that the video was "cut";
- Attaching a new screenshot in order to show the problem I'm describing: 
- on the left side of the photo, the Vimeo original player is pictured;
- on the right side of the photo, the Min Vid player is pictured, but, as I pointed, the right part of the video is not displayed.

![hjsfjadl](https://user-images.githubusercontent.com/26000308/29030696-a53064ae-7b94-11e7-9727-e1b27d4c8ccc.png)


Please let me know if you have any questions related to this issue :)
Links to the videos that I tested:
https://vimeo.com/227668954
https://vimeo.com/116240987

**Comment by meandavejustice** [comment]
@SoftVision-CarmenFat I'm not seeing this on my linux machine. Lets see if we can get @6a68 to reproduce it on mac

**Comment by meandavejustice** [comment]
Not even seeing any upstream bugs regarding this in https://github.com/CookPete/react-player

**Comment by SoftVision-CarmenFat** [comment]
This issue was verified with latest Min-Vid v 1.0.10 from replace-sdk branch and it is no longer reproducible, so I think it's safe to close it.
