### ISSUE TITLE
Cannot drag the player to another position while it is in "Replay/Close" screen

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#949]
[Affected versions]:
- Firefox 54.0.1 and up
- Min-Vid 1.0.10

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on (1.0.10) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to one of the supported platforms (e.g www.youtube.com).
2. Send a video video to the Min Vid player and wait to end.
3. Drag&Drop the player to another position from desktop.

[Expected result]:
- The min-Vid player can be dragged to any custom position.

[Actual result]:
- The Min-Vid player cannot be dragged while it is in "Replay/Close" screen.

[Notes]:
- Attached a screen cast of the issue:

![cannot drag player to other position when in no more items screen](https://user-images.githubusercontent.com/9248513/28932794-68f3607c-7883-11e7-946d-66959c424817.gif)

**Comment by meandavejustice** [comment]
Although this is annoying, it's not a park of the sdk refactor. Will plan to fix this in a follow up update.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest version of Min Vid built on 8/18/2017. Marking as verified.
