### ISSUE TITLE
Cannot change the resolution of the Min-Vid player

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#953]
[Affected versions]:
- Firefox 54.0.1 and up
- Min-Vid 1.0.10

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on (1.0.10) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to one of the supported platforms (e.g www.youtube.com).
2. Open a new tab and go to about:addons -> Extensions page.
3. Double click on Min-Vid extension.
4. Change the resolution of the player and click "Save"
5. Send a video to the player and observe the resolution change.

[Expected result]:
- The Min-Vid player is opened and has the new resolution.

[Actual result]:
- The Min-Vid player has the default resolution. Any change made to the resolution is not applied.

**Comment by Softvision-VladBacia** [comment]
This issue impacts #942 .

**Comment by meandavejustice** [comment]
Should have been fixed in https://github.com/meandavejustice/min-vid/commit/a5011ab2071492f98a4d1a0e9b2546c0be33e4cf looks like this is fixed on my platform (linux) feel free to reopen if you continue to see this issue.

**Comment by Softvision-VladBacia** [comment]
This issue has been verified with latest Min-Vid v 1.0.10 from replace-sdk branch and it is no longer reproducible.
