### ISSUE TITLE
[Soundcloud] An infinite loading animation is displayed when sending an unsupported track to the player

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#954]
[Affected versions]:
- Firefox 54.0.1 and up
- Min-Vid 1.0.10

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on (1.0.10) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.soundcloud.com
2. Send an unsupported track to the Min Vid player (e.g. https://soundcloud.com/678carti/magnolia-1)
3. Observe what happens next.

[Expected result]:
- The Player is opened and displays the following elements:
-> "The publisher of this track has restricted access to third parties, try another track." message centered in the player window.
-> "Open in new tab" link under the above message, also centered in the Player window.

[Actual result]:
- An infinite loading animation is displayed.

[Notes]:
- Please see the following screen cast of the issue:

![infinite loading](https://user-images.githubusercontent.com/26000308/28969477-68c244e2-792d-11e7-9099-b6a86124c27b.gif)

**Comment by electron0zero** [comment]
I am Having same issue in YouTube, It was working fine the day before.

My User Agent String is 
`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0`

**Comment by meandavejustice** [comment]
fixed in https://github.com/meandavejustice/min-vid/commit/21a7ef5327151079a1c3ee1f8ec526b17a43c644

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible on the latest master version (built on 7/8/2017).
