### ISSUE TITLE
Host the XPI and update.rdf files for auto-updating add-on

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#96]
Currently the only way I can get this add-on to install is to download or build the XPI myself, and then drag it into the about:addons page.

It'd be super neat if we had a hosted version of the XPI on people.mozilla.org or GitHub or S3 or something so we could have a nice one-click install and auto-updating functionality.

Activity Stream does a pretty cool job if it by offering two add-ons:

1. https://moz-activity-streams-dev.s3.amazonaws.com/dist/latest.html &mdash; Updated with every commit via Travis-CI integration and is meant as a developer/Nightly thing.
1. https://moz-activity-streams.s3.amazonaws.com/dist/latest.html &mdash; Manually updated every ~2 weeks during manual deploys to prod. This is our regular old "release" build which is the same build that Test Pilot points to, IIRC.

Once we have a hosted XPI and RDF file, we can add this module to something like testpilot.dev.mozaws.net so cutting edge users can easily install the add-on (developer or release channel) and play along at home.

**Comment by pdehaan** [comment]
Ref: #13 
Ref: #23

**Comment by pdehaan** [comment]
FWIW, we have "https://testpilot.cdn.mozilla.net/nomore404s/nomore404s.json" for hosting a CDN-ified version of the XPI and JSON file for NoMore404s web-extension. Not sure if we want to host our files there, or if you're using your own bucket (or people.mozilla.org).

**Comment by meandavejustice** [comment]
@pdehaan I would love to host our files there. I need to get my aws creds fixed up today

**Comment by Mte90** [comment]
any news for this?

**Comment by meandavejustice** [comment]
@Mte90 I still need to dig into issues with amo signing api. I'll try and get a manually signed addon up somewhere today so it can be easily installed.

**Comment by meandavejustice** [comment]
Finally figured out what my issue was with the signing api. There was a `install.rdf` file still hanging around in my local copy of the repo with an old version in it. Apparently jpm gives precedence to the install.rdf over the package.json. Seems like an upstream bug. The plan for this going forward is to sign the addon with the script I am adding(should be in a pr tomorrow) and then just hand it off to @clouserw until we get prod s3 access after launch. Then we can hookup travis or circleci to run the signing and upload to s3

**Comment by meandavejustice** [comment]
These are being hosted in the testpilot s3 bucket now
