### ISSUE TITLE
Player position is changed when sending a video if previously the player was minimized and closed

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#961]
[Affected versions]:
- Firefox 54.0.1 and up
- Min-Vid 1.0.10

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on (1.0.10) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to one of the supported platforms (e.g www.youtube.com).
2. Send a video to the player.
3. Move the player near the bottom of the screen. 
4. Minimize and Close the Min-Vid player.
5. Send another video to the player.
6. Minimize and Close the Min-Vid player.
7. Repeat steps 5 & 6 until the player disappears out of the screen.

[Expected result]:
- Min-Vid player keeps it's position when another video is sent to the player if it was minimized and closed.

[Actual result]:
- Every time a video is sent to the player after it was minimized and closed, the position is changed. The player is moved to the bottom of the screen and beyond.

[Notes]:
- Multiple warnings are displayed in the Browser Console when performing the action from the above steps:
```
"Warning: Unknown props `minimized`, `loaded`, `error`, `currentTime`, `exited`, `duration`, 
`strings`, `visual`, `confirm`, `confirmContent`, `queue`, `history`, `set`, `videoId`, 
`launchUrl`, `domain`, `trackAdded` on <div> tag. Remove these props from 
the element. 
For details, see https://fb.me/react-unknown-prop
    in div (created by ReactPlayer)
    in ReactPlayer (created by Player)
    in div (created by Player)
    in Player (created by AppView)
    in div (created by AppView)
    in div (created by AppView)
    in AppView"  frontend.bundle.js:357:7
Warning: a `div` tag (owner: `ReactPlayer`) was passed a numeric string value for CSS 
property `width` (value: `400`) which will be treated as a unitless number in a future 
version of React.  frontend.bundle.js:357:7
Warning: a `div` tag (owner: `ReactPlayer`) was passed a numeric string value for CSS 
property `height` (value: `260`) which will be treated as a unitless number in a future 
version of React.
```

- Attached a screen recording of the issue:

![minimize and close the player](https://user-images.githubusercontent.com/9248513/29080497-941568f2-7c68-11e7-80f2-57178c69135d.gif)

**Comment by SoftVision-PaulOiegas** [comment]
This seems to be a dupe of one of my logged issues (#862). Am I right?

**Comment by Softvision-VladBacia** [comment]
close as dupe of #862
