### ISSUE TITLE
Player resolution can be setted above the max resolution

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#962]
[Affected versions]:
- Firefox 54.0.1 and up
- Min-Vid 1.0.10

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on (1.0.10) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to one of the supported platforms (e.g www.youtube.com).
2. Open a new tab and go to about:addons -> Extensions page.
3. Double click on Min-Vid extension.
4. Change the resolution of the player to 3000px X 3000px and click "Save"
5. Send a video to the player and observe the resolution change.

[Expected result]:
- The user cannot set a resolution above the maximum resolution.

[Actual result]:
- The resolution is saved although the resolution value box has it is marked with red. After the change is made the Min-Vid player is opened with the new resolution

[Notes]:
- Attaching a screen recording of the issue:

![player resolution](https://user-images.githubusercontent.com/9248513/29081194-85148dd6-7c6a-11e7-909e-405654301572.gif)

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest version of Min Vid built on 8/22/2017.
