### ISSUE TITLE
Overlay icon visible in fullscreen

### ISSUE THREAD

**Issue by pietroalbini** [meandavejustice/min-vid#964]
When you open a video in fullscreen, the overlay is always visible at the top corner of the screen, and it's a bit annoying. I saw the issue was fixed a year ago but it's showing up again.

Firefox Nightly on Ubuntu 14.04 LTS

**Comment by meandavejustice** [comment]
refs #185

**Comment by Silvery-Corgan** [comment]
Happens to me as well in Firefox 55.0.1 x64

**Comment by meandavejustice** [comment]
* css detection when the _browser_ is fullscreen https://developer.mozilla.org/en-US/docs/Web/CSS/:fullscreen
* events to listen for when detecting with js https://stackoverflow.com/questions/24389115/how-can-i-detect-when-an-iframe-goes-fullscreen#24389627

**Comment by LoveIsGrief** [comment]
![Example](https://user-images.githubusercontent.com/2829538/29474266-4e3e349e-845b-11e7-9f61-126bfe019a12.png)

**Comment by SoftVision-PaulOiegas** [comment]
@meandavejustice This was fixed on the old YouTube UI but it's still present in the new UI. Want me to log a new issue or reopen this one?

**Comment by meandavejustice** [comment]
@SoftVision-PaulOiegas  opened https://github.com/meandavejustice/min-vid/issues/1042

**Comment by chylex** [comment]
I would like to mention that a lot of times I go into fullscreen faster than the overlay loads, and MinVid does not detect fullscreen correctly when it loads, so it places the overlay into fullscreen anyway. Exiting fullscreen and re-entering it fixes the issue, but it'd still be nice to fix this edge case.

**Comment by SoftVision-PaulOiegas** [comment]
@chylex Thanks for the addition, can you copy your comment in the issue that is still opened for the YouTube overlay problem? Here it is #1042. When that will be fixed, the dev team will take your scenario in consideration too.

Thanks!
