### ISSUE TITLE
Default resolution is displayed instead of the customized one, if the page is refreshed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [meandavejustice/min-vid#969]
[Notes]:
- The Min Vid player has the customized resolution, even if the default resolution is displayed after refresh on "about:addons" page.

[Affected versions]:
- Firefox 55.0 and up
- Min-Vid 1.0.10

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on (1.0.10) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to one of the supported platforms (e.g www.youtube.com).
2. Open a new tab and go to about:addons -> Extensions page.
3. Double click on Min-Vid extension.
4. Change the resolution of the player to 3000px X 3000px and click "Save"
5. Refresh the page and observe the resolution.

[Expected result]:
- The customized resolution is still displayed.

[Actual result]:
- Default resolution is re-displayed.

[Additional Notes]:
- Attaching a screen recording of the issue:
![customized resolution1](https://user-images.githubusercontent.com/19226534/29170028-7fa23760-7ddf-11e7-9aae-d58aa8e89cfb.gif)

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest version of Min Vid built on 8/22/2017.
