### ISSUE TITLE
Min-Vid player is not closed and the "X" button is not working, if the add-on is removed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [meandavejustice/min-vid#970]
[Affected versions]:
- Firefox 55.0 and up
- Min-Vid 1.0.10

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on (1.0.10) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to one of the supported platforms (e.g www.youtube.com).
2. Send a video video to the Min Vid player.
3. Open a new tab and go to about:addons -> Extensions page.
4. Remove the Min-Vid add-on.
5. Observe the Min-Vid player.

[Expected result]:
- The add-on is removed and the Min-Vid player is closed.

[Actual result]:
- The add-on is removed, but the Min-Vid player remains opened and the the "X" button is not working.

[Notes]:
- Attaching a screen recording of the issue:
![min vid removed](https://user-images.githubusercontent.com/19226534/29171465-5ed41b42-7de5-11e7-9ad1-5e2dffb12e76.gif)

**Comment by meandavejustice** [comment]
Listen for the uninstall event and close the window in this case

**Comment by meandavejustice** [comment]
https://github.com/mozilla-services/screenshots/blob/master/addon/bootstrap.js#L136

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest version of Min-Vid built on 8/18/2017. Marking as verified.
