### ISSUE TITLE
One second of the previously Vimeo video played can be observed when sending another video/track while on Replay/Close screen

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#973]
[Affected versions]:
- Firefox 55.0 and up
- Min-Vid 1.0.10

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on (1.0.10) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.vimeo.com
2. Send a video to the Min Vid player and wait to end.
3. Send another video to the player from "Play now" button and observe what happens.

[Expected result]:
- The last video/track sent to the player starts playback.

[Actual result]:
- Before the last sent video/track starts playback, one second of the previously played Vimeo video is displayed.

[Notes]:
- Attaching a screen recording of the issue:

![vimeo one second](https://user-images.githubusercontent.com/26000308/29178443-441a1346-7dfa-11e7-8505-c41abf64db6c.gif)

**Comment by wresuolc** [comment]
We're dropping support for soundcloud and vimeo
