### ISSUE TITLE
[Linux] Resizing the Min-Vid player window with drag&drop breaks the UI

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#975]
[Affected versions]:
- Firefox 54.0.1 and up
- Min-Vid 1.0.10

[Affected Platforms]:
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on (1.0.10) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to one of the supported platforms (e.g www.youtube.com).
2. Send a video to the Min-Vid player with "Play Now" option.
3. Move the mouse cursor over the bottom-right corner of the Min-Vid player window. 
4. Drag&Drop the Min-Vid window in order to resize it.
5. Minimize the player.
6. Move the mouse cursor over the bottom-right corner of the Min-Vid player window. 
7. Drag&Drop the Min-Vid window in order to resize it.

[Expected result]:
5. The new size of the Min-Vid player window is saved and it is kept when minimizing/maximizing or when sending other videos to the player.
7. The whole UI is resized, but only in length.

[Actual result]:
5. When minimizing/maximizing or sending other videos to the player, the player window is automatically resized to the initial state.
7. When the player is minimized and it is resized downwards, the video will appear in the lower part of the player window.

[Notes]:
- [Here](https://drive.google.com/open?id=0B6QogV2AJFKicGhDSTFIb2U2M1E) is a screen recording of the issue.

**Comment by meandavejustice** [comment]
resizing with this method isn't officially supported
