### ISSUE TITLE
no min-vid icon in toolbar and on video canvas (nightly 57a1)

### ISSUE THREAD

**Issue by zticky** [meandavejustice/min-vid#980]
Installed min-vid and no icon shows in toolbar and on video canvas despite addon is on/activated.
No min-vid icon available in customize settings

**Comment by meandavejustice** [comment]
Hey @zticky would you mind letting us know which firefox version you are running? You can access this by visiting  `about:` in the address bar

**Comment by zticky** [comment]
Version 	57.0a1
Build ID 	20170814100258

**Comment by mathearts** [comment]
Same problem here, 57a1, latest min-vid from test pilot.

**Comment by daufinsyd** [comment]
Version 57.0a1 from 20170816 also affected.

**Comment by Softvision-VladBacia** [comment]
please see comments from issue #967

**Comment by meandavejustice** [comment]
Just pushed a fix for this. Thanks for everyone's patience :)
