### ISSUE TITLE
The Queue can't be opened while in the "Replay/Close" screen

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#995]
[Affected versions]:
- Firefox 55 and up
- Min-Vid 0.4.1 (built on 8/18/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on (0.4.1) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to one of the supported platforms (e.g www.youtube.com).
2. Send a video video to the Min Vid player and wait for it to end.
3. Click the "Open Queue" button and observe the behavior.
Bonus Round:
4. Click the "Minimize" button and observe the behavior.

[Expected result]:
- Step 3: Queue is opened.
- Step 4: "Minimize" button is behind the queue and can't be clicked.

[Actual result]:
- Step 3: Nothing happens.
- Step 4: The player is minimized and the queue is opened.

[Notes]:
- Attached a screen cast of the issue:
![queue cannot be opened while in the replay close screen](https://user-images.githubusercontent.com/18304511/29459670-78b51b80-842d-11e7-863f-d3652b1f336b.gif)

**Comment by meandavejustice** [comment]
This is happening because at this point there isn't any items actually in the the queue(it's a phony empty item to keep the window open). We should either change the queue view to show the queue as empty in this case when opened or not show the queue icon as available in this view.

**Comment by SoftVision-CiprianMuresan** [comment]
Reopening this because the Replay and Close buttons are displayed while the Queue is open.

![image](https://user-images.githubusercontent.com/18304511/29873824-6ad593e0-8d9d-11e7-85f2-87b31b789751.png)
